import type browserslist from 'browserslist';

import { generatedFileExists, } from './generated-file-exists.ts';

//region Types: dependency import shapes and injectable IO

/**
 * Readonly Browserslist options subset needed by this config helper.
 *
 * @example
 * ```ts
 * const options: BrowserslistOptions = { path: process.cwd() };
 * ```
 */
export type BrowserslistOptions = {
  /**
   * File or directory path used by Browserslist to find configuration.
   */
  readonly path?: string;
};

/**
 * Callable resolver shape used from the `browserslist` package.
 *
 * @example
 * ```ts
 * const resolveBrowserslist: BrowserslistResolver = browserslist;
 * ```
 */
export type BrowserslistResolver = (
  queries?: Parameters<typeof browserslist>[0],
  opts?: BrowserslistOptions,
) => string[];

/**
 * Namespace shapes returned by importing Browserslist from ESM runtimes.
 *
 * @example
 * ```ts
 * const imported: BrowserslistImport = { default: browserslist };
 * ```
 */
export type BrowserslistImport = BrowserslistResolver | {
  readonly default: BrowserslistResolver;
};

/**
 * Target runtime family selected by a tsdown preset.
 *
 * @example
 * ```ts
 * const runtime: TsdownTargetRuntime = 'browser';
 * ```
 */
export type TsdownTargetRuntime = 'browser' | 'node';

/**
 * Predicate used before importing generated JSON.
 *
 * @example
 * ```ts
 * const exists: FileExists = generatedFileExists;
 * ```
 */
export type FileExists = (fileUrl: URL) => Promise<boolean>;

/**
 * Dynamic JSON importer used for generated Browserslist targets.
 *
 * @example
 * ```ts
 * const importJson: JsonImporter = importGeneratedJson;
 * ```
 */
export type JsonImporter = (fileUrl: URL) => Promise<unknown>;

/**
 * Dynamic Browserslist importer used when generated JSON is absent.
 *
 * @example
 * ```ts
 * const importBrowserslist: BrowserslistImporter = importBrowserslistPackage;
 * ```
 */
export type BrowserslistImporter = () => Promise<BrowserslistImport>;

/**
 * Options for selecting generated or live Browserslist targets.
 *
 * @example
 * ```ts
 * const targets = await browserslistTargets({});
 * ```
 */
export type BrowserslistTargetsOptions = {
  /**
   * URL to root-local JSON generated by file-enforcer.
   */
  readonly generatedFileUrl?: URL;
  /**
   * Predicate allowing tests to bypass real filesystem access.
   */
  readonly exists?: FileExists;
  /**
   * Importer allowing tests to bypass real JSON module loading.
   */
  readonly importJson?: JsonImporter;
  /**
   * Importer allowing tests to bypass real Browserslist package loading.
   */
  readonly importBrowserslist?: BrowserslistImporter;
  /**
   * Runtime family whose targets should be returned.
   */
  readonly runtime?: TsdownTargetRuntime;
};

/**
 * Arguments for validating dynamically imported target arrays.
 *
 * @example
 * ```ts
 * const args: StringArrayAssertionArgs = { source: 'generated JSON', value: [] };
 * ```
 */
type StringArrayAssertionArgs = {
  /**
   * Value loaded from generated JSON or dynamic fallback.
   */
  readonly value: unknown;
  /**
   * Human-readable source included in validation failures.
   */
  readonly source: string;
};

/**
 * Arguments for reading default export from dynamic module namespace.
 *
 * @example
 * ```ts
 * const args: JsonModuleDefaultArgs = { imported: { default: [] }, source: 'json' };
 * ```
 */
type JsonModuleDefaultArgs = {
  /**
   * Runtime module namespace to inspect.
   */
  readonly imported: unknown;
  /**
   * Human-readable source included in validation failures.
   */
  readonly source: string;
};

/**
 * Parsed Browserslist target pieces.
 *
 * @example
 * ```ts
 * const parts: BrowserslistTargetParts = {
 *   browser: 'firefox',
 *   original: 'firefox 140',
 *   version: '140',
 * };
 * ```
 */
type BrowserslistTargetParts = {
  /**
   * Browser identifier emitted by Browserslist.
   */
  readonly browser: string;
  /**
   * Version identifier emitted by Browserslist.
   */
  readonly version: string;
  /**
   * Original target string used in validation failures.
   */
  readonly original: string;
};

/**
 * Rolldown-compatible target pieces after Browserslist name mapping.
 *
 * @example
 * ```ts
 * const parts: RolldownTargetParts = {
 *   browser: 'firefox',
 *   original: 'and_ff 150',
 *   version: '150',
 * };
 * ```
 */
type RolldownTargetParts = {
  /**
   * Browser identifier accepted by Rolldown.
   */
  readonly browser: string;
  /**
   * Version identifier accepted by Rolldown.
   */
  readonly version: string;
  /**
   * Original Browserslist target used in validation failures.
   */
  readonly original: string;
};

/**
 * Arguments for comparing version strings.
 *
 * @example
 * ```ts
 * const args: VersionComparisonArgs = { left: '140', right: '150' };
 * ```
 */
type VersionComparisonArgs = {
  /**
   * Left-hand version string.
   */
  readonly left: string;
  /**
   * Right-hand version string.
   */
  readonly right: string;
};

/**
 * Arguments for choosing lower target within one browser family.
 *
 * @example
 * ```ts
 * const args: LowerTargetArgs = { current, candidate };
 * ```
 */
type LowerTargetArgs = {
  /**
   * Existing target selected for browser family.
   */
  readonly current: RolldownTargetParts;
  /**
   * Candidate target being compared against existing target.
   */
  readonly candidate: RolldownTargetParts;
};

/**
 * Arguments for runtime-family target filtering.
 *
 * @example
 * ```ts
 * const args: RuntimeTargetArgs = { runtime: 'browser', target };
 * ```
 */
type RuntimeTargetArgs = {
  /**
   * Runtime family requested by tsdown preset.
   */
  readonly runtime: TsdownTargetRuntime;
  /**
   * Target pieces being checked against runtime family.
   */
  readonly target: RolldownTargetParts;
};

/**
 * Arguments for normalizing raw Browserslist output.
 *
 * @example
 * ```ts
 * const args: NormalizeTargetsArgs = { runtime: 'browser', targets: [] };
 * ```
 */
type NormalizeTargetsArgs = {
  /**
   * Runtime family requested by tsdown preset.
   */
  readonly runtime: TsdownTargetRuntime;
  /**
   * Raw target strings returned by Browserslist.
   */
  readonly targets: readonly string[];
};

//endregion Types: dependency import shapes and injectable IO

//region Constants: generated file location and target mappings

/**
 * Root-local Browserslist resolution generated by file-enforcer.
 *
 * @example
 * ```ts
 * const href = GENERATED_BROWSERSLIST_URL.href;
 * ```
 */
const GENERATED_BROWSERSLIST_URL = new URL(
  '../../../../.browserslistrc.resolved.local.json',
  import.meta.url,
);

/**
 * Browserslist browser identifiers mapped to Rolldown target names.
 *
 * @example
 * ```ts
 * const chromeTarget = ROLLDOWN_BROWSER_NAMES.and_chr;
 * ```
 */
const ROLLDOWN_BROWSER_NAMES = {
  and_chr: 'chrome',
  and_ff: 'firefox',
  android: 'chrome',
  chrome: 'chrome',
  edge: 'edge',
  firefox: 'firefox',
  ios: 'ios',
  ios_saf: 'ios',
  node: 'node',
  op_mob: 'chrome',
  opera: 'opera',
  safari: 'safari',
  samsung: 'chrome',
} as const;

/**
 * Sentinel returned by `String.indexOf` when separator is absent.
 *
 * @example
 * ```ts
 * const missing = NOT_FOUND_INDEX;
 * ```
 */
const NOT_FOUND_INDEX = -1;

//endregion Constants: generated file location and target mappings

//region IO helpers: generated JSON and package fallback

/**
 * Extracts default export from dynamic JSON module namespace.
 *
 * @param imported - Runtime module namespace to inspect.
 *
 * @param source - Human-readable source included in validation failures.
 *
 * @returns Default export value.
 *
 * @throws TypeError when module namespace has no default export.
 *
 * @example
 * ```ts
 * const value = jsonModuleDefault({ imported: { default: [] }, source: 'json' });
 * ```
 */
function jsonModuleDefault({
  imported,
  source,
}: JsonModuleDefaultArgs,): unknown {
  if ((typeof imported) !== 'object')
    throw new TypeError(`${source} must provide a default export.`,);

  if (imported === null)
    throw new TypeError(`${source} must provide a default export.`,);

  if (!('default' in imported))
    throw new TypeError(`${source} must provide a default export.`,);

  return imported.default;
}

/**
 * Imports generated Browserslist target JSON, reading the default export
 * out via {@link jsonModuleDefault}.
 *
 * @param fileUrl - Generated JSON file URL to import.
 *
 * @returns Default export from JSON module namespace.
 *
 * @example
 * ```ts
 * const imported = await importGeneratedJson(new URL('file:///tmp/targets.json'));
 * ```
 */
async function importGeneratedJson(fileUrl: URL,): Promise<unknown> {
  /**
   * JSON namespace loaded through import attributes.
   */
  const imported: unknown = await import(
    fileUrl.href,
    { with: { type: 'json', }, },
  );

  return jsonModuleDefault({
    imported,
    source: fileUrl.href,
  },);
}

/**
 * Imports Browserslist package for live target resolution.
 *
 * @returns Browserslist package namespace from dynamic import.
 *
 * @example
 * ```ts
 * const imported = await importBrowserslistPackage();
 * ```
 */
async function importBrowserslistPackage(): Promise<BrowserslistImport> {
  /**
   * CommonJS package namespace exposed through ESM dynamic import.
   */
  const imported = await import('browserslist') as BrowserslistImport;

  return imported;
}

//endregion IO helpers: generated JSON and package fallback

//region Validation helpers: imported target shape

/**
 * Checks whether value is a string.
 *
 * @param value - Value being narrowed.
 *
 * @returns Whether value is a string.
 *
 * @example
 * ```ts
 * isString('firefox 140');
 * ```
 */
function isString(value: unknown,): value is string {
  return (typeof value) === 'string';
}

/**
 * Checks whether value is an array of strings.
 *
 * @param value - Value being narrowed.
 *
 * @returns Whether value is an array of strings.
 *
 * @example
 * ```ts
 * isStringArray(['firefox 140']);
 * ```
 */
function isStringArray(value: unknown,): value is string[] {
  return (Array.isArray(value,))
    && (value.every(function isStringItem(item,): boolean {
      return isString(item,);
    },));
}

/**
 * Asserts that imported targets are represented as a string array.
 *
 * @param value - Value loaded from generated JSON or dynamic fallback.
 *
 * @param source - Human-readable source included in validation failures.
 *
 * @returns String array when validation succeeds.
 *
 * @throws TypeError when value is not a string array.
 *
 * @example
 * ```ts
 * const targets = assertStringArray({ source: 'generated JSON', value: ['firefox 140'] });
 * ```
 */
function assertStringArray({
  value,
  source,
}: StringArrayAssertionArgs,): string[] {
  if (isStringArray(value,))
    return value;

  throw new TypeError(`${source} must default-export a string array.`,);
}

/**
 * Splits Browserslist target string into browser and version pieces.
 *
 * @param target - Browserslist target string to split.
 *
 * @returns Parsed browser, version, and original target.
 *
 * @throws TypeError when target cannot be split into browser and version.
 *
 * @example
 * ```ts
 * const parts = splitBrowserslistTarget('firefox 140');
 * ```
 */
function splitBrowserslistTarget(target: string,): BrowserslistTargetParts {
  /**
   * Index of separator between browser identifier and version string.
   */
  const separatorIndex = target.indexOf(' ',);

  if (separatorIndex === NOT_FOUND_INDEX)
    throw new TypeError(`Browserslist target is missing version: ${target}`,);

  /**
   * Browser identifier before first space.
   */
  const browser = target.slice(
    0,
    separatorIndex,
  );
  /**
   * Version identifier after first space.
   */
  const version = target.slice((separatorIndex + 1),);

  if (version.length === 0)
    throw new TypeError(`Browserslist target is missing version: ${target}`,);

  return {
    browser,
    original: target,
    version,
  };
}

/**
 * Checks whether browser identifier has a Rolldown target mapping.
 *
 * @param browser - Browserslist browser identifier.
 *
 * @returns Whether identifier can be converted to a Rolldown target name.
 *
 * @example
 * ```ts
 * hasRolldownBrowserName('and_chr');
 * ```
 */
function hasRolldownBrowserName(
  browser: string,
): browser is keyof typeof ROLLDOWN_BROWSER_NAMES {
  return Object.hasOwn(
    ROLLDOWN_BROWSER_NAMES,
    browser,
  );
}

/**
 * Converts Browserslist browser identifier to Rolldown target name.
 *
 * @param parts - Parsed Browserslist target pieces.
 *
 * @returns Rolldown target browser name.
 *
 * @throws TypeError when browser identifier is unsupported by this mapping.
 *
 * @example
 * ```ts
 * const browser = rolldownBrowserName({ browser: 'and_chr', original: 'and_chr 148', version: '148' });
 * ```
 */
function rolldownBrowserName(parts: BrowserslistTargetParts,): string {
  if (hasRolldownBrowserName(
    parts.browser,
  ))
    return ROLLDOWN_BROWSER_NAMES[parts.browser];

  throw new TypeError(
    `Browserslist target is unsupported by tsdown target mapping: ${parts.original}`,
  );
}

/**
 * Compares dot-separated numeric version strings.
 *
 * @param left - Left-hand version string.
 *
 * @param right - Right-hand version string.
 *
 * @returns Negative when left is lower, positive when right is lower, zero when equal.
 *
 * @example
 * ```ts
 * compareVersions({ left: '140', right: '150' });
 * ```
 */
function compareVersions({
  left,
  right,
}: VersionComparisonArgs,): number {
  /**
   * Left version split into numeric-looking segments.
   */
  const leftParts = left.split('.',);
  /**
   * Right version split into numeric-looking segments.
   */
  const rightParts = right.split('.',);
  /**
   * Segment count needed to compare every present version component.
   */
  const length = Math.max(
    leftParts.length,
    rightParts.length,
  );

  for (let loopIndex = 0; loopIndex < length; loopIndex += 1) {
    /**
     * Left segment number, defaulting absent trailing segments to zero.
     */
    const leftNumber = Number(leftParts[loopIndex] ?? '0',);
    /**
     * Right segment number, defaulting absent trailing segments to zero.
     */
    const rightNumber = Number(rightParts[loopIndex] ?? '0',);

    if (Number.isNaN(leftNumber,))
      return left.localeCompare(right,);

    if (Number.isNaN(rightNumber,))
      return left.localeCompare(right,);

    if (leftNumber < rightNumber)
      return -1;

    if (leftNumber > rightNumber)
      return 1;
  }

  return 0;
}

/**
 * Chooses lower target version within one Rolldown browser family.
 *
 * @param current - Existing target selected for browser family.
 *
 * @param candidate - Candidate target being compared against existing target.
 *
 * @returns Lower-version target.
 *
 * @example
 * ```ts
 * const lower = lowerTarget({ current, candidate });
 * ```
 */
function lowerTarget({
  current,
  candidate,
}: LowerTargetArgs,): RolldownTargetParts {
  /**
   * Version comparison where negative means candidate is lower.
   */
  const comparison = compareVersions({
    left: candidate.version,
    right: current.version,
  },);

  if (comparison < 0)
    return candidate;

  return current;
}

/**
 * Converts one Browserslist target string to Rolldown target pieces by
 * splitting it with {@link splitBrowserslistTarget} and mapping the browser
 * identifier through {@link rolldownBrowserName}.
 *
 * @param target - Browserslist target string to convert.
 *
 * @returns Rolldown target pieces accepted by tsdown.
 *
 * @example
 * ```ts
 * normalizeBrowserslistTarget('and_chr 148');
 * ```
 */
function normalizeBrowserslistTarget(target: string,): RolldownTargetParts {
  /**
   * Parsed target pieces used for name mapping and formatting.
   */
  const parts = splitBrowserslistTarget(target,);
  /**
   * Rolldown target browser identifier.
   */
  const browser = rolldownBrowserName(parts,);

  return {
    browser,
    original: parts.original,
    version: parts.version,
  };
}

/**
 * Formats Rolldown target pieces as tsdown target string.
 *
 * @param target - Rolldown target pieces to format.
 *
 * @returns Target string accepted by tsdown.
 *
 * @example
 * ```ts
 * const target = formatRolldownTarget({ browser: 'firefox', original: 'firefox 140', version: '140' });
 * ```
 */
function formatRolldownTarget(target: RolldownTargetParts,): string {
  return `${target.browser}${target.version}`;
}

/**
 * Selects lowest version for each Rolldown browser family.
 *
 * @param targets - Rolldown target pieces to collapse by browser family.
 *
 * @returns Map keyed by browser family with lowest selected target.
 *
 * @example
 * ```ts
 * const targetMap = lowestTargetsByBrowser([]);
 * ```
 */
function lowestTargetsByBrowser(
  targets: readonly RolldownTargetParts[],
): Map<string, RolldownTargetParts> {
  /**
   * Mutable target map scoped to this reduction.
   */
  const targetMap = new Map<string, RolldownTargetParts>();

  for (const candidate of targets) {
    /**
     * Current target selected for this browser family, if any.
     */
    const current = targetMap.get(candidate.browser,);

    targetMap.set(
      candidate.browser,
      current === undefined
        ? candidate
        : lowerTarget({
          candidate,
          current,
        },),
    );
  }

  return targetMap;
}

/**
 * Checks whether normalized target belongs to requested runtime family.
 *
 * @param runtime - Runtime family requested by tsdown preset.
 *
 * @param target - Target pieces being checked.
 *
 * @returns Whether target should be used for runtime family.
 *
 * @example
 * ```ts
 * targetMatchesRuntime({ runtime: 'node', target });
 * ```
 */
function targetMatchesRuntime({
  runtime,
  target,
}: RuntimeTargetArgs,): boolean {
  if (runtime === 'node')
    return target.browser === 'node';

  return target.browser !== 'node';
}

/**
 * Throws when runtime filtering removes every target.
 *
 * @param runtime - Runtime family requested by tsdown preset.
 *
 * @param targets - Runtime-filtered target pieces.
 *
 * @returns Same targets when non-empty.
 *
 * @throws TypeError when runtime family has no matching targets.
 *
 * @example
 * ```ts
 * const targets = assertRuntimeTargets({ runtime: 'browser', targets: [target] });
 * ```
 */
function assertRuntimeTargets({
  runtime,
  targets,
}: {
  readonly runtime: TsdownTargetRuntime;
  readonly targets: readonly RolldownTargetParts[];
},): readonly RolldownTargetParts[] {
  if (targets.length > 0)
    return targets;

  throw new TypeError(`Browserslist config produced no ${runtime} targets for tsdown.`,);
}

/**
 * Converts Browserslist output to unique Rolldown-compatible targets,
 * collapsing each browser family to its lowest version via
 * {@link lowestTargetsByBrowser}.
 *
 * @param targets - Raw target strings returned by Browserslist.
 *
 * @param runtime - Runtime family requested by tsdown preset.
 *
 * @returns Unique tsdown target strings.
 *
 * @example
 * ```ts
 * const targets = normalizeBrowserslistTargets({ runtime: 'browser', targets: ['and_chr 148'] });
 * ```
 */
function normalizeBrowserslistTargets({
  runtime,
  targets,
}: NormalizeTargetsArgs,): string[] {
  /**
   * Rolldown target pieces in Browserslist output order.
   */
  const mappedTargets = targets.map(function normalizeTarget(target,): RolldownTargetParts {
    return normalizeBrowserslistTarget(target,);
  },);
  /**
   * Rolldown target pieces matching requested runtime family.
   */
  const runtimeTargets = assertRuntimeTargets({
    runtime,
    targets: mappedTargets.filter(function filterRuntimeTarget(target,): boolean {
      return targetMatchesRuntime({
        runtime,
        target,
      },);
    },),
  },);
  /**
   * Map holding lowest target pieces per Rolldown browser family.
   */
  const lowestTargetMap = lowestTargetsByBrowser(runtimeTargets,);
  /**
   * Lowest target pieces per Rolldown browser family.
   */
  const lowestTargets = [...lowestTargetMap.values(),];

  return lowestTargets.map(function formatTarget(target,): string {
    return formatRolldownTarget(target,);
  },);
}

/**
 * Extracts resolver function from possible Browserslist import shapes.
 *
 * @param imported - Browserslist dynamic import namespace or callable export.
 *
 * @returns Browserslist resolver function.
 *
 * @example
 * ```ts
 * const resolveBrowserslist = browserslistResolver({ default: browserslist });
 * ```
 */
function browserslistResolver(imported: BrowserslistImport,): BrowserslistResolver {
  if ((typeof imported) === 'function')
    return imported;

  return imported.default;
}

//endregion Validation helpers: imported target shape

//region Public API: target resolution

/**
 * Resolves tsdown target strings from generated JSON, falling back to
 * Browserslist, normalizing either source via
 * {@link normalizeBrowserslistTargets}.
 *
 * @param generatedFileUrl - Generated JSON file URL.
 *
 * @param exists - Filesystem predicate used before importing generated JSON.
 *
 * @param importJson - Dynamic JSON importer.
 *
 * @param importBrowserslist - Dynamic Browserslist package importer.
 *
 * @param runtime - Runtime family whose targets should be returned.
 *
 * @returns Resolved Browserslist target strings for tsdown.
 *
 * @example
 * ```ts
 * const target = await browserslistTargets();
 * ```
 */
export async function browserslistTargets({
  generatedFileUrl = GENERATED_BROWSERSLIST_URL,
  exists = generatedFileExists,
  importJson = importGeneratedJson,
  importBrowserslist = importBrowserslistPackage,
  runtime = 'browser',
}: BrowserslistTargetsOptions = {},): Promise<string[]> {
  if (await exists(generatedFileUrl,)) {
    /**
     * Generated JSON default export.
     */
    const importedTargets = await importJson(generatedFileUrl,);

    return normalizeBrowserslistTargets({
      runtime,
      targets: assertStringArray({
        source: generatedFileUrl.href,
        value: importedTargets,
      },),
    },);
  }

  /**
   * Browserslist package namespace imported when generated JSON is absent.
   */
  const importedBrowserslist = await importBrowserslist();
  /**
   * Resolver extracted from runtime-specific dynamic import shape.
   */
  const resolveBrowserslist = browserslistResolver(importedBrowserslist,);

  return normalizeBrowserslistTargets({
    runtime,
    targets: resolveBrowserslist(
      undefined,
      { path: process.cwd(), },
    ),
  },);
}

//endregion Public API: target resolution
