/**
 * Node-side HTML emitter for the deck.gl scene control panel.
 *
 * Pure string-builder: returns an HTML fragment ready for embedding in
 * the page generated by `./render-html.ts`. No DOM access, no scripts —
 * those live in `./scripts/controller.ts` and are bundled into a
 * separate `<script>` block.
 *
 * Output IDs match what `./scripts/controller.ts` queries:
 * `dim-<channel>`, `range-<channel>-<min|max>`, `toggle-<key>` (radio
 * names), `search`, `display-*`, `name-labels`, `visibility-counter`,
 * `reset`. Channel/toggle rows carry `data-channel` / `data-toggle`
 * attributes so the controller can wire handlers via `querySelectorAll`.
 *
 * @example
 * ```ts
 * import { renderControls } from './render-controls.ts';
 * const fragment = renderControls({ probes, state: defaultState({ probes }) });
 * ```
 */

import type { PackageProbe, } from './probe.ts';
import {
  acceptsDim,
  DIM_DISPLAY_NAMES,
  TOGGLE_LABELS,
} from './dim-meta.ts';
import {
  type ChannelKey,
  type DataDimKey,
  extractDim,
  type ToggleKey,
  type ToggleValue,
} from './scripts/filter.ts';
import {
  type AppState,
  TOGGLE_KEYS,
} from './scripts/state.ts';

//region Constants

/** All ten data dims, fixed order for dropdown rendering. */
const DIM_KEYS: readonly DataDimKey[] = [
  'logSourceBytes',
  'logDaysStale',
  'logInstallSize',
  'logDownloads',
  'tsRatio',
  'runtimeDepCount',
  'transitiveDepCount',
  'logPackageAge',
  'isLeafNumeric',
  'licenseClassNumeric',
];

/** Channels in their dropdown render order. */
const CHANNEL_KEYS: readonly ChannelKey[] = [
  'x',
  'y',
  'z',
  'color',
  'shape',
  'size',
];

/** Three-state toggle radio values, fixed order. */
const TOGGLE_VALUES: readonly ToggleValue[] = [
  'any',
  'yes',
  'no',
];

/** Name-labels select options, fixed order. */
const NAME_LABEL_OPTIONS: readonly ('none' | 'topN' | 'all')[] = [
  'none',
  'topN',
  'all',
];

/** Slider step in displayed-value units; fine enough for log-scale dims. */
const RANGE_STEP = 0.01;

/** Display-channel labels for the dim picker rows. */
const CHANNEL_LABELS: Record<ChannelKey, string> = {
  x: 'x',
  y: 'y',
  z: 'z',
  color: 'color',
  shape: 'shape',
  size: 'size',
};

//endregion Constants

//region Helpers

/**
 * Escapes runtime-controlled strings for embedding in HTML attribute
 * values. Currently only the search field's initial value reaches the
 * renderer with user-controlled content (via URL-hash bookmark).
 *
 * Order is critical: `&` must be replaced first or other replacements
 * would double-escape it.
 *
 * @param raw - Source string from state.
 *
 * @returns Escaped string safe for double-quoted attribute embedding.
 */
function escapeAttr(raw: string,): string {
  return raw
    .replaceAll('&', '&amp;',)
    .replaceAll('"', '&quot;',)
    .replaceAll('<', '&lt;',)
    .replaceAll('>', '&gt;',);
}

/**
 * Computes inclusive `[min, max]` for one dim across the probe array,
 * skipping unknowns. Falls back to `[0, 0]` when no probe has a known
 * value so the slider can still render.
 *
 * @param probes - Source probes.
 * @param dim - Dim whose extent to compute.
 *
 * @returns Inclusive `[min, max]` bounds.
 */
function computeChannelExtent(
  {
    probes,
    dim,
  }: {
    probes: readonly PackageProbe[];
    dim: DataDimKey;
  },
): readonly [number, number,] {
  const values = probes
    .map(function pluck(probe,) {
      return extractDim({
        probe,
        dim,
      },);
    },)
    .filter(function nonNull(value,): value is number {
      return value !== null;
    },);
  if (values.length === 0) return [0, 0,];
  return [
    Math.min(...values,),
    Math.max(...values,),
  ];
}

//endregion Helpers

//region Dim dropdowns

/**
 * Renders one `<select>` element binding a channel to its data dim.
 *
 * Options the channel doesn't accept (per {@link acceptsDim}) still
 * render — but with the `disabled` attribute — so users can see what
 * exists without reading docs.
 *
 * @param channel - Channel being bound (x, y, z, color, shape, size).
 * @param selectedDim - Currently mapped dim.
 *
 * @returns HTML fragment for one dim row.
 *
 * @example
 * ```ts
 * renderDimDropdown({ channel: 'x', selectedDim: 'logSourceBytes' });
 * ```
 */
function renderDimDropdown(
  {
    channel,
    selectedDim,
  }: {
    channel: ChannelKey;
    selectedDim: DataDimKey;
  },
): string {
  const options = DIM_KEYS.map(function renderOption(dim,) {
    const accepted = acceptsDim({
      channel,
      dim,
    },);
    const selected = dim === selectedDim ? ' selected' : '';
    const disabled = accepted ? '' : ' disabled';
    return `<option value="${dim}"${selected}${disabled}>${DIM_DISPLAY_NAMES[dim]}</option>`;
  },).join('',);
  return `<div class="dim-row" data-channel="${channel}">
      <label for="dim-${channel}">${CHANNEL_LABELS[channel]}</label>
      <select id="dim-${channel}">${options}</select>
    </div>`;
}

//endregion Dim dropdowns

//region Toggle rows

/**
 * Renders one 3-state radio group for a boolean filter toggle.
 *
 * @param key - Toggle key (identifies the boolean attribute).
 * @param current - Currently selected value.
 *
 * @returns HTML fragment for one toggle row.
 *
 * @example
 * ```ts
 * renderToggleRow({ key: 'isLeaf', current: 'any' });
 * ```
 */
function renderToggleRow(
  {
    key,
    current,
  }: {
    key: ToggleKey;
    current: ToggleValue;
  },
): string {
  const radios = TOGGLE_VALUES.map(function renderRadio(value,) {
    const checked = value === current ? ' checked' : '';
    return `<label><input type="radio" name="toggle-${key}" value="${value}"${checked}>${value}</label>`;
  },).join('',);
  return `<fieldset class="toggle-row" data-toggle="${key}">
      <legend>${TOGGLE_LABELS[key]}</legend>${radios}
    </fieldset>`;
}

//endregion Toggle rows

//region Range sliders

/**
 * Renders one min/max range-slider pair for a channel.
 *
 * Slider `min`/`max` attributes use the full data extent; `value`
 * attributes use the current state. On first render both pairs coincide;
 * after URL-hash restore they typically diverge.
 *
 * @param channel - Channel being filtered.
 * @param fullExtent - Full data extent (slider bounds).
 * @param current - Currently set `[min, max]` (initial handle positions).
 *
 * @returns HTML fragment for one range row.
 *
 * @example
 * ```ts
 * renderRangeRow({ channel: 'x', fullExtent: [0, 6], current: [0, 6] });
 * ```
 */
function renderRangeRow(
  {
    channel,
    fullExtent,
    current,
  }: {
    channel: ChannelKey;
    fullExtent: readonly [number, number,];
    current: readonly [number, number,];
  },
): string {
  const [
    fullMin,
    fullMax,
  ] = fullExtent;
  const [
    curMin,
    curMax,
  ] = current;
  const minAttr = fullMin.toString();
  const maxAttr = fullMax.toString();
  const stepAttr = RANGE_STEP.toString();
  return `<div class="range-row control-row" data-channel="${channel}">
      <label>${CHANNEL_LABELS[channel]} range</label>
      <div class="range-track">
        <input type="range" id="range-${channel}-min" min="${minAttr}" max="${maxAttr}" step="${stepAttr}" value="${curMin.toString()}">
        <input type="range" id="range-${channel}-max" min="${minAttr}" max="${maxAttr}" step="${stepAttr}" value="${curMax.toString()}">
      </div>
    </div>`;
}

//endregion Range sliders

//region Display section

/**
 * Renders the display-toggle section (4 checkboxes plus a `name-labels`
 * `<select>`).
 *
 * @param state - Current state (drives initial checked/selected state).
 *
 * @returns HTML fragment for the display section.
 *
 * @example
 * ```ts
 * renderDisplaySection({ state: defaultState({ probes }) });
 * ```
 */
function renderDisplaySection(
  { state, }: { state: AppState; },
): string {
  const dt = state.displayToggles;
  const wireframe = dt.showWireframe ? ' checked' : '';
  const planes = dt.showThresholdPlanes ? ' checked' : '';
  const axisLabels = dt.showAxisLabels ? ' checked' : '';
  const unknown = dt.showUnknownCluster ? ' checked' : '';
  const nameOptions = NAME_LABEL_OPTIONS.map(function renderOption(value,) {
    const selected = dt.nameLabels === value ? ' selected' : '';
    return `<option value="${value}"${selected}>${value}</option>`;
  },).join('',);
  return `<section class="controls-section" data-section="display">
      <h2>Display</h2>
      <label><input type="checkbox" id="display-wireframe"${wireframe}>Wireframe</label>
      <label><input type="checkbox" id="display-planes"${planes}>Threshold planes</label>
      <label><input type="checkbox" id="display-axis-labels"${axisLabels}>Axis labels</label>
      <label><input type="checkbox" id="display-unknown"${unknown}>Unknown cluster</label>
      <label>Name labels <select id="name-labels">${nameOptions}</select></label>
    </section>`;
}

//endregion Display section

//region Public API

/**
 * Renders the full control-panel HTML fragment.
 *
 * Output is meant to be inserted into `<body>` by `./render-html.ts`,
 * sitting alongside the deck.gl canvas. The controller script (also
 * embedded by render-html.ts) wires every control after the page loads.
 *
 * @param probes - Source probes; drives the per-channel slider extents.
 * @param state - Initial state; every control's initial value reflects this.
 *
 * @returns HTML fragment containing the complete control panel.
 *
 * @example
 * ```ts
 * const fragment = renderControls({ probes, state });
 * // … embedded in render-html.ts's final HTML string …
 * ```
 */
export function renderControls(
  {
    probes,
    state,
  }: {
    probes: readonly PackageProbe[];
    state: AppState;
  },
): string {
  const dimRows = CHANNEL_KEYS.map(function dropdownFor(channel,) {
    return renderDimDropdown({
      channel,
      selectedDim: state.dimMapping[channel],
    },);
  },).join('',);
  const toggleRows = TOGGLE_KEYS.map(function toggleFor(key,) {
    return renderToggleRow({
      key,
      current: state.toggles[key],
    },);
  },).join('',);
  const rangeRows = CHANNEL_KEYS.map(function rangeFor(channel,) {
    return renderRangeRow({
      channel,
      fullExtent: computeChannelExtent({
        probes,
        dim: state.dimMapping[channel],
      },),
      current: state.ranges[channel],
    },);
  },).join('',);
  const total = probes.length.toString();
  const searchAttr = escapeAttr(state.search,);
  return `<aside id="controls" class="controls">
    <section class="controls-section" data-section="camera">
      <h2>Camera</h2>
      <dl class="camera-help">
        <dt>Drag</dt><dd>rotate</dd>
        <dt>Shift + drag</dt><dd>pan</dd>
        <dt>Scroll</dt><dd>zoom</dd>
        <dt>Double-click</dt><dd>reset view</dd>
      </dl>
    </section>
    <section class="controls-section" data-section="dim">
      <h2>Dimensions</h2>${dimRows}
    </section>
    <section class="controls-section" data-section="toggles">
      <h2>Filters</h2>${toggleRows}
    </section>
    <section class="controls-section" data-section="ranges">
      <h2>Range filters</h2>${rangeRows}
    </section>
    <section class="controls-section" data-section="search">
      <h2>Search</h2>
      <input type="text" id="search" placeholder="substring or /regex/" value="${searchAttr}">
    </section>
    ${renderDisplaySection({
    state,
  },)}
    <section class="controls-section" data-section="info">
      <span id="visibility-counter">${total} of ${total} visible</span>
      <button id="reset" type="button">Reset filters</button>
    </section>
  </aside>`;
}

//endregion Public API
