/**
 * Build script: generates a single self-contained HTML wc text-stats tool.
 *
 * Reads the pre-bundled client JS from tsdown output, then assembles
 * HTML/CSS/JS into a single file.
 *
 * Requires `mise run build:js:client` to have run first so
 * `dist/client/main.js` exists.
 */
import { Buffer, } from 'node:buffer';
import {
  mkdir,
  readFile,
  writeFile,
} from 'node:fs/promises';
import { join, } from 'node:path';

import {
  renderFaviconPngBase64,
  renderFaviconSvg,
} from './favicon.ts';
import { renderPage, } from './page.ts';
import { renderStyles, } from './styles.ts';

export {};

/**
 * Absolute path to this package's root directory
 */
const PACKAGE_DIR: string = new URL(
  '..',
  import.meta.url,
)
  .pathname;

/**
 * Output directory for the generated site
 */
const DIST_DIR = join(
  PACKAGE_DIR,
  'dist',
  'final',
);

console.error('[wc] building...',);

/**
 * Subsetted Inter variable font (produced by `mise run format:fonts`),
 * base64-encoded for inlining as a data URI
 */
const fontWoff2Base64 = (await readFile(
  join(
    PACKAGE_DIR,
    'public',
    'inter.woff2',
  ),
))
  .toString('base64',);

/**
 * Minified CSS stylesheet, generated by {@link renderStyles}
 */
const css = renderStyles({ fontWoff2Base64, },);

/**
 * Client-side input handling and rendering script, pre-bundled by tsdown
 */
const js = await readFile(
  join(
    PACKAGE_DIR,
    'dist',
    'client',
    'main.js',
  ),
  'utf8',
);

/**
 * Vector favicon markup, base64-encoded for inlining as a data URI
 */
const faviconSvgBase64 = Buffer.from(renderFaviconSvg(),)
  .toString('base64',);

/**
 * Complete self-contained HTML document, assembled by {@link renderPage}
 */
const html = renderPage(
  {
    css,
    js,
    faviconSvgBase64,
    faviconPngBase64: await renderFaviconPngBase64(),
  },
);

await mkdir(
  DIST_DIR,
  { recursive: true, },
);
await writeFile(
  join(
    DIST_DIR,
    'index.html',
  ),
  html,
  'utf8',
);

console.error(`[wc] wrote ${
  join(
    DIST_DIR,
    'index.html',
  )
}`,);
