[tasks.build]
extends = "build"

[tasks.'build:js']
extends = "build:js"

[tasks.'build:js:node']
extends = "build:js:node"

[tasks."watch:build"]
extends = "watch:build"

[tasks."watch:build:js"]
extends = "watch:build:js"

[tasks."watch:build:js:node"]
extends = "watch:build:js:node"

[tasks.lint]
extends = "lint"

[tasks."lint:oxlint"]
extends = "lint:oxlint"

[tasks."format:oxlint"]
description = "Auto-fix with Oxlint (type-aware)"
run = """
{{vars.monorepo_root_setup}}
{{vars.ensure_oxlint_config}}
{{vars.workspace_node_dispatch}}
run_workspace_node $root packages/dev-script/task-util oxlint-wrapper --type-aware --fix
"""

[tasks."lint:types"]
extends = "lint:types"
hide = true
