name: test building themes

on:
- push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
    - uses: cargo-bins/cargo-binstall@main

    - name: install non-npm dependency static web server
      run: cargo binstall --no-confirm static-web-server

    - name: install other non-npm dependencies
      run: |
        sudo apt-get install graphviz imagemagick patch plantuml librsvg2-2 librsvg2-bin librsvg2-common unzip zstd

    - uses: actions/checkout@main

    - name: setup correct npm dependencies package manager version
      run: yarn set version stable

    - name: setup correct node version and npm dependencies package manager cache
      uses: actions/setup-node@main
      with:
        node-version-file: 'package.json'
        cache: 'yarn'

    - name: install npm dependencies
      run: yarn

    - name: test building subtle theme
      run: yarn run -T -B monochromatic build
      working-directory: ./packages/theme/subtle

    - uses: actions/upload-artifact@main
      with:
        name: build
        path: ./packagegs/theme/subtle/monochromatic.log
        retention-days: 7

  windows:
    runs-on: windows-latest

    steps:
    - uses: cargo-bins/cargo-binstall@main

    - name: install non-npm dependency static web server
      run: cargo binstall --no-confirm static-web-server

    - name: install non-npm dependency rsvg-convert
      run: |
        choco feature enable -n=allowGlobalConfirmation
        choco install rsvg-convert
      shell: pwsh

    - name: install scoop (to install some non-npm dependencies)
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
      shell: pwsh

    - name: add scoop buckets (to install some non-npm dependencies)
      run: |
        scoop bucket add extras
        scoop bucket add java

    - name: use scoop to install some non-npm dependencies
      run: |
        scoop install temurin-lts-jre graphviz imagemagick patch plantuml unzip zstd

    - uses: actions/checkout@main

    - name: setup correct npm dependencies package manager version
      run: yarn set version stable

    - name: setup correct node version and npm dependencies package manager cache
      uses: actions/setup-node@main
      with:
        node-version-file: 'package.json'
        cache: 'yarn'

    - name: install npm dependencies
      run: yarn

    - name: test building subtle theme
      run: yarn run -T -B monochromatic build
      working-directory: ./packages/theme/subtle

    - uses: actions/upload-artifact@main
      with:
        name: build
        path: ./packagegs/theme/subtle/monochromatic.log
        retention-days: 7

  devcontainer:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@main

    - uses: devcontainers/ci@v0.3.1900000349
      with:
        cacheFrom: ghcr.io/aquaticat/monochromatic
        push: never
        runCmd: |
          cd packages/theme/subtle/
          yarn run -T -B monochromatic build
