cloneConcurrency: 4

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableMessageNames: false

enableTelemetry: false

enableTimers: false

httpTimeout: 6000

logFilters:
  - level: discard
    text: ESM support for PnP uses the experimental loader API and is therefore experimental
  - level: discard
    text: Completed
  - level: discard
    pattern: "* must be built because it never has been before or the last one failed"

nmMode: hardlinks-local

pnpEnableEsmLoader: true

pnpEnableInlining: false

preferReuse: true

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

winLinkType: symlinks

yarnPath: .yarn/releases/yarn-4.2.2.cjs

packageExtensions:
  "postcss@*":
    peerDependencies:
      postcss-value-parser: "*"
