logLevel = 'warn'
telemetry = false

[test]
coverageSkipTestFiles = true

[install]
auto = 'disable'
scopes.jsr = 'https://npm.jsr.io'
saveTextLockfile = true

[run]
# Always use Bun's shell
shell = 'bun'

# Auto alias node to Bun
bun = true

silent = true
