# vale Vale.Repetition = NO #
logLevel = 'warn'
telemetry = false

# Not using Bun's test runner
# [test]
# coverage = true

[install]
auto = 'disable'
scopes.jsr = 'https://npm.jsr.io'
saveTextLockfile = true

[run]
# Always use Bun's shell
shell = 'bun'

# Auto alias node to Bun
bun = true

silent = true
# vale Vale.Repetition = YES #
