# CoPy Files from Dependencies

['.+']
'README\.md' = false
'package\.json' = false

# We don't wanna tsconfig in workspace root.
'tsconfig\.json' = false
'example\.tsconfig\.json' = false
'api-extractor\.json' = false
'example\.api-extractor\.json' = false

['.+'.'.+']
'README\.md' = false
'package\.json' = false
'tsconfig\.json' = false
'example\.tsconfig\.json' = false
'api-extractor\.json' = false
'example\.api-extractor\.json' = false

['@monochromatic\.dev'.'.+']
'\.\w+ignore' = true
'example\.(\.?\w+\.\w+(?:\.\w+)?)' = '$1'
'\.editorconfig' = true
'\.npmrc' = true
'\.browserslistrc' = true
