# CoPy Files from Dependencies

['.+']
'README\.md' = false
'package\.json' = false

['.+'.'.+']
'README\.md' = false
'package\.json' = false

['@monochromatic\.dev'.'.+']
'\.\w+ignore' = true
'\.\w+config' = true
'\.\w+rc' = true
'\.\w+rc\.json' = true
'\.\w+rc\.toml' = true

'dprint\.json' = true

'example\.(\w+)' = '$1'
