version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '4110:4110'
    - '4111:4111'
    environment:
    - SERVICE_FQDN_EXA_4110=${EXA_FQDN:-https://exa.aquati.cat}
    - SERVICE_FQDN_MASTRA_4111=${MASTRA_FQDN:-https://mastra.aquati.cat}
    - NODE_ENV=${NODE_ENV:-production}
    - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
    - pnpm-store:/root/.local/share/pnpm/store/v10
    labels:
    - 'coolify.managed=true'
    - 'coolify.type=application'

volumes:
  pnpm-store:
