version: '3.8'

x-shared-config: &shared-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
  - pnpm-store:/root/.local/share/pnpm/store/v10
  labels:
  - 'coolify.managed=true'
  - 'coolify.type=application'
  environment:
  - NODE_ENV=${NODE_ENV:-production}

services:
  caddy:
    <<: *shared-config
    command: moon run startCaddy
    ports:
    - '4110:4110'
    environment:
    - SERVICE_FQDN_EXA_SEARCH_4110=${EXA_SEARCH_FQDN:-https://exa.aquati.cat}

  ai-proxy:
    <<: *shared-config
    command: moon run ai-proxy:start
    ports:
    - '4111:4111'
    environment:
    - SERVICE_FQDN_AI_PROXY_4111=${AI_PROXY_FQDN:-https://ai-proxy.aquati.cat}
    - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

volumes:
  pnpm-store:
