import {
  cat,
  overwrite,
  overwriteEach,
  overwriteIfNotExists,
} from '@monochromatic-dev/dev-script-file-enforcer/ts';
import { glob, } from 'node:fs/promises';
import { homedir, } from 'node:os';
import { join, } from 'node:path';

/**
 * Generates mise.toml from mise.no-env.toml with a dynamic [env] section
 * containing _.path entries for all workspace package bin directories.
 */
async function generateMiseToml(): Promise<void> {
  const envSection = `[env]
# .env file is optional - mise silently ignores missing files
# https://github.com/jdx/mise/blob/main/src/config/env_directive/file.rs#L155-L163
_.file = [{ path = ".env", redact = true }, { path = ".env.local", redact = true }]
_.path = [
${
    [
      'node_modules/.bin',
      ...(await Array.fromAsync(glob('packages/*/*/node_modules/.bin',),)),
    ]
      .map(function quote(dir,): string {
        return `"${dir}"`;
      },)
      .join(',\n',)
  }
]
`;
  await overwrite(
    './mise.toml',
    `# Generated from mise.no-env.toml by file-enforcer.
${await cat(['./mise.no-env.toml',],)}
${envSection}`,
  );
}

/**
 * Generates `forbidden-strings.local.txt` by concatenating the committed
 * example ruleset with a per-repo append file. The append file is
 * gitignored and seeded with a comment-only header on first run; the
 * developer adds per-repo deny-list literals into it directly so those
 * literals never enter version control.
 *
 * Why two files? `forbidden-strings.local.example.txt` is the ported
 * betterleaks baseline (sane defaults, regenerated by
 * `mise.port-betterleaks.ts`). `forbidden-strings.append.local.txt` is
 * the place to put repo-specific rules (codenames, partner identifiers,
 * etc.) that must not leak into git history. The scanner reads the
 * combined `forbidden-strings.local.txt` at runtime.
 */
async function generateForbiddenStringsRules(): Promise<void> {
  // Seed the append file (gitignored) with a comment header only; the
  // file is the place developers add per-repo deny-list literals (e.g.
  // codenames, customer names) that must not be committed. We never
  // write a literal into this committed config -- otherwise the
  // scanner would self-match against the seed string here.
  await overwriteIfNotExists(
    './forbidden-strings.append.local.txt',
    `# forbidden-strings per-repo appendix (gitignored).
# Add literal substrings or /PATTERN/FLAGS regex rules below; one per line.
# This file is concatenated onto forbidden-strings.local.example.txt by
# file-enforcer to produce the runtime forbidden-strings.local.txt.
`,
  );
  await overwrite(
    './forbidden-strings.local.txt',
    `# Generated from forbidden-strings.local.example.txt + forbidden-strings.append.local.txt by file-enforcer.
# Do not edit manually. To change baseline rules, edit
# packages/dev-script/forbidden-strings/src/mise.port-betterleaks.ts and re-run it.
# To add per-repo rules, edit forbidden-strings.append.local.txt.

${
      await cat([
        './forbidden-strings.local.example.txt',
        './forbidden-strings.append.local.txt',
      ],)
    }`,
  );
}

/**
 * Mirrors canonical skills from .agents/skills/ to .factory/skills/ and .claude/skills/
 * for legacy consumers.
 */
async function mirrorSkills(): Promise<void> {
  const skills = await cat('./.agents/skills/*/*.md',);
  await Promise.all([
    overwriteEach(
      './.factory/skills/*/*.md',
      skills,
    ),
    overwriteEach(
      './.claude/skills/*/*.md',
      skills,
    ),
  ],);
}

await Promise.all([
  // CLAUDE.md must literally contain AGENTS.md content (Claude Code's @include is unreliable)
  overwrite(
    './CLAUDE.md',
    `Generated from AGENTS.md by file-enforcer.
    
    ### Spawning child Claude sessions

General purpose agents are banned because of bugs.

Use \`spawn-claude\` outside sandbox to launch steerable child Claude Code sessions in visible terminal windows.
The child session runs independently; results are forwarded back to the parent automatically via hooks.

\`\`\`bash
spawn-claude "implement feature X"
spawn-claude --cwd /some/path "fix the bug in module Y"
spawn-claude --extra-arguments "--model sonnet" "refactor this module"
\`\`\`

The command prints \`{"spawnId":"<uuid>"}\` on success.
Completed child results are injected into context automatically between tool calls.

${await cat(['./AGENTS.md',],)}`,
  ),

  generateMiseToml(),

  generateForbiddenStringsRules(),

  mirrorSkills(),
  // Oxlint config: root oxlint.config.ts imports @monochromatic-dev/config-oxlint and adds jsPlugins.
  // JS plugins (tsdoc, no-restricted-syntax, stylistic) are referenced by path from the root config.
],);
