import { glob, } from 'node:fs/promises';
import { join, } from 'node:path';

import {
  cat,
  manageLsp4ijServerSettings,
  overwrite,
  overwriteEach,
  overwriteIfNotExists,
} from '@monochromatic-dev/dev-script-file-enforcer/ts';

import type browserslist from 'browserslist';

/**
 * Resolver function exported by the `browserslist` package.
 *
 * @example
 * ```ts
 * const resolveBrowserslist = await importBrowserslist();
 * ```
 */
type BrowserslistResolver = typeof browserslist;

/**
 * Imports Browserslist at runtime so generators use the installed package data.
 *
 * @returns Browserslist resolver from dynamic package import.
 *
 * @example
 * ```ts
 * const resolveBrowserslist = await importBrowserslist();
 * ```
 */
async function importBrowserslist(): Promise<BrowserslistResolver> {
  /**
   * CommonJS package namespace exposed through ESM dynamic import.
   */
  const browserslistModule = await import('browserslist') as {
    readonly default: BrowserslistResolver;
  };

  return browserslistModule.default;
}

/**
 * Generates mise.toml from mise.no-env.toml with a dynamic [env] section
 * containing _.path entries for all workspace package bin directories.
 */
async function generateMiseToml(): Promise<void> {
  /**
   * Dynamic [env] block appended after the static mise.no-env.toml content; wires PATH to every workspace bin dir.
   */
  const envSection = `[env]
# .env file is optional - mise silently ignores missing files
# https://github.com/jdx/mise/blob/main/src/config/env_directive/file.rs#L155-L163
_.file = [{ path = ".env", redact = true }, { path = ".env.local", redact = true }]
_.path = [
${
    [
      'node_modules/.bin',
      ...(await Array.fromAsync(glob('packages/*/*/node_modules/.bin',),)),
    ]
      .map(function quote(dir,): string {
        return `  "${dir}"`;
      },)
      .join(',\n',)
  },
]

# Enables Slint's experimental builtins (e.g. FlexboxLayout) in slint-lsp when it
# is launched through mise (e.g. the JetBrains plugin's external LSP set to run
# "mise exec -- slint-lsp"). slint-lsp exposes no CLI flag for this; the compiler
# reads this env var at runtime (internal/compiler/lib.rs) and the LSP relies on
# that path (tools/lsp/main.rs). The two desktop-app packages already set it for
# their builds; setting it at the repo root also covers the editor LSP whose cwd
# is the monorepo root. mise [env] is directory-activated, so it only reaches the
# LSP process when mise launches it.
SLINT_ENABLE_EXPERIMENTAL_FEATURES = "1"
`;
  await overwrite({
    dest: './mise.toml',
    content: `# Generated from mise.no-env.toml by file-enforcer.
${await cat(['./mise.no-env.toml',],)}
${envSection}`,
  },);
}

/**
 * Generates `forbidden-strings.local.txt` by concatenating three sources:
 * the committed example baseline, a committed shared appendix, and a
 * gitignored sensitive appendix. The sensitive appendix is seeded with a
 * comment-only header on first run; the developer adds private deny-list
 * literals into it directly so those literals never enter version control.
 *
 * Why three files? `forbidden-strings.local.example.txt` is the ported
 * betterleaks baseline (sane defaults, regenerated by
 * `mise.port-betterleaks.ts`). `forbidden-strings.append.txt` is checked
 * in and holds non-sensitive repo-wide rules (e.g. AGENTS.md shortcode
 * collisions) so every clone and CI share them.
 * `forbidden-strings.append.local.txt` is gitignored and holds sensitive
 * rules (codenames, partner identifiers, politically-charged literals)
 * that must not leak into git history. The scanner reads the combined
 * `forbidden-strings.local.txt` at runtime.
 */
async function generateForbiddenStringsRules(): Promise<void> {
  // Seed the gitignored sensitive appendix with a comment header only;
  // the file is where developers add private deny-list literals (e.g.
  // codenames, customer names) that must not be committed. We never
  // write a literal into this committed config; otherwise the
  // scanner would self-match against the seed string here.
  await overwriteIfNotExists({
    dest: './forbidden-strings.append.local.txt',
    content: `# forbidden-strings per-repo appendix (gitignored).
# Sensitive deny-list rules that must NOT enter version control: codenames,
# customer names, partner identifiers, politically-charged literals, etc.
# Add literal substrings or /PATTERN/FLAGS regex rules below; one per line.
# This file is concatenated onto forbidden-strings.local.example.txt and
# forbidden-strings.append.txt by file-enforcer to produce the runtime
# forbidden-strings.local.txt. Non-sensitive shared rules belong in the
# checked-in forbidden-strings.append.txt instead.
`,
  },);
  await overwrite({
    dest: './forbidden-strings.local.txt',
    content:
      `# Generated from forbidden-strings.local.example.txt + forbidden-strings.append.txt + forbidden-strings.append.local.txt by file-enforcer.
# Do not edit manually. To change baseline rules, edit
# packages/cli/forbidden-strings/src/mise.port-betterleaks.ts and re-run it.
# To add shared (non-sensitive) rules, edit forbidden-strings.append.txt.
# To add sensitive rules, edit forbidden-strings.append.local.txt.

${await cat([
        './forbidden-strings.local.example.txt',
        './forbidden-strings.append.txt',
        './forbidden-strings.append.local.txt',
      ],)}`,
  },);
}

/**
 * Generates resolved Browserslist targets for build tools that cannot resolve
 * `.browserslistrc` directly.
 *
 * @example
 * ```ts
 * await generateResolvedBrowserslistTargets();
 * ```
 */
async function generateResolvedBrowserslistTargets(): Promise<void> {
  /**
   * Browserslist resolver loaded lazily so file-enforcer uses real package data.
   */
  const resolveBrowserslist = await importBrowserslist();
  /**
   * Target strings selected by the root `.browserslistrc` file.
   */
  const targets = resolveBrowserslist(
    undefined,
    { path: process.cwd(), },
  );

  await overwrite({
    dest: './.browserslistrc.resolved.local.json',
    content: `${JSON.stringify(
      targets,
      null,
      2,
    )}\n`,
  },);
}

/**
 * Mirrors canonical skills from .agents/skills/ to .factory/skills/ and .claude/skills/
 * for legacy consumers.
 */
async function mirrorSkills(): Promise<void> {
  /**
   * Concatenated SKILL.md contents from the canonical .agents/skills tree, mirrored verbatim to legacy consumer dirs.
   */
  const skills = await cat('./.agents/skills/*/*.md',);
  await Promise.all([
    overwriteEach({
      destGlob: './.factory/skills/*/*.md',
      files: skills,
    },),
    overwriteEach({
      destGlob: './.claude/skills/*/*.md',
      files: skills,
    },),
  ],);
}

/**
 * Builds a flat patch disabling the given Harper linter rules.
 *
 * @param rules - Harper rule names to disable.
 *
 * @returns Patch mapping each `harper-ls.linters.<rule>` key to false.
 *
 * @example
 * ```ts
 * harperLintersDisabled(['SplitWords']);
 * ```
 */
function harperLintersDisabled(rules: readonly string[],): Record<string, false> {
  return Object.fromEntries(rules.map(function toDisabledEntry(rule,): readonly [
    string,
    false,
  ] {
    return [
      `harper-ls.linters.${rule}`,
      false,
    ];
  },),);
}

/**
 * Syncs this repo's Harper LSP4IJ writing-style policy into the latest IntelliJ
 * IDEA config: disables prose rules globally, excludes the caveman-style agent
 * docs from the main server, and registers a second Harper server scoped to
 * AGENTS.md and CLAUDE.md with extra rules disabled.
 *
 * @example
 * ```ts
 * await manageHarperLsp4ij();
 * ```
 */
async function manageHarperLsp4ij(): Promise<void> {
  await manageLsp4ijServerSettings({
    productPrefixes: [
      'IntelliJIdea',
      'IdeaIC',
    ],
    baseServerMatch: {
      commandLineIncludes: 'harper-ls',
      serverNameEquals: 'Harper Language Server',
      templateId: 'harper-ls',
    },
    baseConfig: {
      set: harperLintersDisabled([
        'UseTitleCase',
        'SplitWords',
        'PhrasalVerbAsCompoundNoun',
      ],),
      arrayUnion: {
        'harper-ls.excludePatterns': [
          '**/AGENTS.md',
          '**/CLAUDE.md',
          join(
            process.cwd(),
            'AGENTS.md',
          ),
          join(
            process.cwd(),
            'CLAUDE.md',
          ),
        ],
      },
    },
    schemaDefaults: {
      'harper-ls.linters.UseTitleCase': {
        type: 'boolean',
        default: true,
        description: 'Prompts you to use title case in relevant headings.',
      },
    },
    scopedServers: [
      {
        id: 'harper-ls-agents-claude-md',
        name: 'Harper Language Server (AGENTS.md and CLAUDE.md)',
        fileNames: [
          'AGENTS.md',
          'CLAUDE.md',
        ],
        languageId: 'markdown',
        copyOptions: [
          'commandLine',
          'installAlreadyDone',
          'installerConfigurationContent',
          'serverUrl',
          'templateId',
          'workingDir',
          'workspaceFolderStrategyConfiguration',
        ],
        configOmitKeys: ['harper-ls.excludePatterns',],
        config: { set: harperLintersDisabled([
          'MissingTo',
          'LongSentences',
          'OxfordComma',
        ],), },
      },
    ],
  },);
}

await Promise.all([
  // CLAUDE.md must literally contain AGENTS.md content (Claude Code's @include is unreliable)
  overwrite({
    dest: './CLAUDE.md',
    content: `Generated from AGENTS.md by file-enforcer.
    
    ### Spawning child Claude sessions

General purpose agents are banned because of bugs.

Use \`spawn-claude\` outside sandbox to launch steerable child Claude Code sessions in visible terminal windows.
The child session runs independently; results are forwarded back to the parent automatically via hooks.

Use \`terminal-exec -- <command> ...\` outside sandbox for arbitrary commands that need a visible terminal window, including Codex. \`spawn-claude\` is only for Claude Code child sessions.

\`\`\`bash
spawn-claude "implement feature X"
spawn-claude --cwd /some/path "fix the bug in module Y"
spawn-claude --extra-arguments "--model sonnet" "refactor this module"
terminal-exec -- codex exec --cd /some/path "investigate issue Z"
\`\`\`

The command prints \`{"spawnId":"<uuid>"}\` on success.
Completed child results are injected into context automatically between tool calls.

${await cat(['./AGENTS.md',],)}`,
  },),

  generateMiseToml(),

  generateForbiddenStringsRules(),

  generateResolvedBrowserslistTargets(),

  manageHarperLsp4ij(),

  mirrorSkills(),
  // Oxlint config: root oxlint.config.ts imports @monochromatic-dev/config-oxlint and adds jsPlugins.
  // JS plugins (tsdoc, no-restricted-syntax, stylistic) are referenced by path from the root config.
],);
