import { existsSync, } from 'node:fs';
import { readFile, } from 'node:fs/promises';

import { overwrite, } from '@monochromatic-dev/dev-script-file-enforcer/ts';

import {
  type MiseRoleFile,
  type MiseTaskName,
  miseRoleFiles,
  miseTaskBodies,
  type TaskBody,
} from './mise-packages.bodies.config.ts';
import {
  type MiseFlavor,
  type MisePackageEntry,
  misePackages,
} from './mise-packages.config.ts';

/**
 * Canonical build-flavor order; the only disk-derived axis of generation.
 * A flavor is present iff `tsdown.{flavor}.config.ts` exists in the package.
 */
const FLAVORS: readonly MiseFlavor[] = [
  'node',
  'browser',
  'client',
];

/**
 * Build aggregators emitted (in this order) when a flavored package keeps the
 * standard set; irregular packages override the set via `entry.buildAggregators`.
 */
const STANDARD_AGGREGATORS: readonly string[] = [
  'build',
  'build:js',
  'watch:build',
  'watch:build:js',
];

/**
 * Header marking each generated `mise.toml` as managed output. The task bodies live
 * in shared mise-shared/*.toml files pulled in via `[task_config].includes`; only
 * irregular leaves a role file cannot express are inlined.
 */
const GENERATED_HEADER = `# Generated by file-enforcer from mise-packages.config.ts; do not hand-edit.
# Build flavors derive from tsdown.{node,browser,client}.config.ts presence.
# Boilerplate task bodies live in ../../../mise-shared/*.toml (generated from
# mise-packages.bodies.config.ts); bespoke tasks live in
# mise-packages/<category>/<package>.toml.`;

/**
 * Header marking each generated shared role file as managed output.
 */
const SHARED_HEADER = `# Generated by file-enforcer from mise-packages.bodies.config.ts; do not hand-edit.
# Included by per-package mise.toml via [task_config].includes; root [vars] interpolate here.`;

/**
 * Relative prefix from any package (all sit at repo depth 3) to the shared role files.
 */
const SHARED_INCLUDE_PREFIX = '../../../mise-shared/';

/**
 * Splits a space-separated manifest field into its task names, treating the
 * empty string as the empty list (an explicit "none", distinct from `undefined`).
 *
 * @param value - Space-separated task names, or empty string for none
 *
 * @returns Task names in declared order
 *
 * @example
 * ```ts
 * splitWords('build build:js'); // ['build', 'build:js']
 * splitWords(''); // []
 * ```
 */
function splitWords(value: string,): readonly string[] {
  return value.length === 0 ? [] : value.split(' ',);
}

/**
 * Quotes a task name for a `[tasks.X]` header: names containing `:` need TOML
 * quoting, bare alphanumeric names do not.
 *
 * @param name - Task name to place in a table header
 *
 * @returns Header-safe key, double-quoted when it contains a colon
 *
 * @example
 * ```ts
 * quoteTaskKey('build'); // 'build'
 * quoteTaskKey('build:js'); // '"build:js"'
 * ```
 */
function quoteTaskKey(name: string,): string {
  return name.includes(':',) ? `"${name}"` : name;
}

/**
 * Renders a TOML string value: a multi-line basic string when the value spans
 * lines (mirroring the source `[task_templates.*]` bodies), else a single-line
 * basic string with `\` and `"` escaped.
 *
 * @param value - Raw string to serialize
 *
 * @returns TOML-quoted scalar
 *
 * @example
 * ```ts
 * renderTomlValue('tsdown'); // '"tsdown"'
 * renderTomlValue('a\nb'); // '"""\na\nb\n"""'
 * ```
 */
function renderTomlValue(value: string,): string {
  if (!value.includes('\n',))
    return `"${value.replaceAll('\\', '\\\\',).replaceAll('"', '\\"',)}"`;

  return `"""\n${value}\n"""`;
}

/**
 * Ordered body fields rendered as `key = value`, skipping absent optional fields;
 * `run` is always present. Shared by the bare-entry and `[tasks.X]` renderers.
 *
 * @param body - Boilerplate task body
 *
 * @returns Field name and serialized value pairs in canonical order
 *
 * @example
 * ```ts
 * bodyFields({ run: 'tsdown', }); // [['run', '"tsdown"']]
 * ```
 */
function bodyFields(body: TaskBody,): readonly (readonly [string, string])[] {
  return [
    ...body.description === undefined ? [] : [['description', renderTomlValue(body.description,),] as const,],
    ...body.usage === undefined ? [] : [['usage', renderTomlValue(body.usage,),] as const,],
    ...body.shell === undefined ? [] : [['shell', renderTomlValue(body.shell,),] as const,],
    ['run', renderTomlValue(body.run,),] as const,
  ];
}

/**
 * Renders one boilerplate task into a shared role file as bare dotted-key entries
 * (`"name".field = value`), the only full-body format mise resolves inside an
 * included file.
 *
 * @param name - Task name owning the body
 *
 * @param body - Boilerplate body to serialize
 *
 * @returns Newline-joined dotted-key assignments
 *
 * @example
 * ```ts
 * renderSharedEntry({ name: 'build:js:node', body: { run: 'tsdown', }, });
 * // '"build:js:node".run = "tsdown"'
 * ```
 */
function renderSharedEntry({ name, body, }: { readonly name: string; readonly body: TaskBody; },): string {
  return bodyFields(body,)
    .map(function toDottedKey([field, value,],): string {
      return `"${name}".${field} = ${value}`;
    },)
    .join('\n',);
}

/**
 * Renders one boilerplate task inline as a `[tasks.X]` section, used for the few
 * leaves an irregular package needs but no whole role file matches.
 *
 * @param name - Task name owning the body
 *
 * @param body - Boilerplate body to serialize
 *
 * @param hidden - Whether to append `hide = true`
 *
 * @returns TOML `[tasks.X]` block without trailing blank line
 *
 * @example
 * ```ts
 * renderInlineTask({ name: 'build:js:client', body: { run: 'tsdown', }, hidden: false, });
 * // '[tasks."build:js:client"]\nrun = "tsdown"'
 * ```
 */
function renderInlineTask(
  { name, body, hidden, }: { readonly name: string; readonly body: TaskBody; readonly hidden: boolean; },
): string {
  return [
    `[tasks.${quoteTaskKey(name,)}]`,
    ...bodyFields(body,).map(function toAssignment([field, value,],): string {
      return `${field} = ${value}`;
    },),
    ...hidden ? ['hide = true',] : [],
  ].join('\n',);
}

/**
 * Reads the disk-derived build flavors for a package from its tsdown configs.
 *
 * @param packageDir - Repo-relative package directory (e.g. `packages/cli/git`)
 *
 * @returns Present flavors in canonical order
 *
 * @example
 * ```ts
 * deriveFlavors({ packageDir: 'packages/module/logger', }); // ['node', 'browser']
 * ```
 */
export function deriveFlavors({ packageDir, }: { readonly packageDir: string; },): readonly MiseFlavor[] {
  return FLAVORS.filter(function flavorOnDisk(flavor,): boolean {
    return existsSync(`${packageDir}/tsdown.${flavor}.config.ts`,);
  },);
}

/**
 * Computes the ordered boilerplate task names a package exposes, from its derived
 * flavors and manifest entry: build aggregators interleaved with the flavor build
 * and watch leaves, followed by the declared lint/test tasks. Identical to the
 * extends renderer's task set, so the includes renderer reproduces the same graph.
 *
 * @param flavors - Disk-derived build flavors
 *
 * @param entry - Manifest entry declaring non-derivable boilerplate
 *
 * @returns Task names in canonical emission order
 *
 * @example
 * ```ts
 * computePackageTasks({ flavors: ['node'], entry: { lintTest: 'lint', }, });
 * // ['build', 'build:js', 'build:js:node', 'watch:build', 'watch:build:js', 'watch:build:js:node', 'lint']
 * ```
 */
export function computePackageTasks(
  { flavors, entry, }: { readonly flavors: readonly MiseFlavor[]; readonly entry: MisePackageEntry; },
): readonly MiseTaskName[] {
  /**
   * Aggregators to emit: manifest override when present, else the standard set
   * for flavored packages and none for flavor-less packages.
   */
  const aggregators = entry.buildAggregators === undefined
    ? (flavors.length === 0 ? [] : STANDARD_AGGREGATORS)
    : splitWords(entry.buildAggregators,);
  /**
   * Flavors whose `watch:build:js:{flavor}` leaf is intentionally absent.
   */
  const watchExcluded = new Set(splitWords(entry.noWatch ?? '',),);
  /**
   * Build flavors that keep their watch leaf.
   */
  const watchFlavors = flavors.filter(function keepsWatchLeaf(flavor,): boolean {
    return !watchExcluded.has(flavor,);
  },);
  /**
   * Ordered build/watch graph: aggregators interleaved with disk-derived leaves.
   */
  const buildNames = [
    ...aggregators.includes('build',) ? ['build',] : [],
    ...aggregators.includes('build:js',) ? ['build:js',] : [],
    ...flavors.map(function buildLeaf(flavor,): string {
      return `build:js:${flavor}`;
    },),
    ...aggregators.includes('watch:build',) ? ['watch:build',] : [],
    ...aggregators.includes('watch:build:js',) ? ['watch:build:js',] : [],
    ...watchFlavors.map(function watchLeaf(flavor,): string {
      return `watch:build:js:${flavor}`;
    },),
  ];
  /**
   * Full ordered task set: build graph followed by the lint/test boilerplate.
   */
  const taskNames = [
    ...buildNames,
    ...splitWords(entry.lintTest,),
  ];
  return taskNames.map(function assertKnown(name,): MiseTaskName {
    if (!(name in miseTaskBodies))
      throw new Error(`no boilerplate body for task: ${name}`,);

    return name as MiseTaskName;
  },);
}

/**
 * Renders the `[task_config].includes` block selecting the given shared role files
 * (paths relative to the package). dprint keeps a single entry inline and breaks
 * multiple entries one-per-line, so this matches that canonical shape.
 *
 * @param files - Shared role file names (e.g. `base.toml`) in include order
 *
 * @returns `[task_config]` block, or empty string when no role file matched
 *
 * @example
 * ```ts
 * renderIncludesBlock(['lint.toml']);
 * // '[task_config]\nincludes = ["../../../mise-shared/lint.toml"]'
 * ```
 */
function renderIncludesBlock(files: readonly string[],): string {
  if (files.length === 0)
    return '';

  /**
   * Quoted include paths from the package to each shared role file.
   */
  const paths = files.map(function toPath(file,): string {
    return `"${SHARED_INCLUDE_PREFIX}${file}"`;
  },);
  if (paths.length === 1)
    return `[task_config]\nincludes = [${paths[0]}]`;

  return `[task_config]\nincludes = [\n${
    paths.map(function indent(path,): string {
      return `  ${path},`;
    },).join('\n',)
  }\n]`;
}

/**
 * Renders the full `mise.toml` for one package from derived flavors, the manifest
 * entry, and the verbatim custom block, using mise `[task_config].includes` over the
 * shared role files. Tasks no whole role file can express are inlined; a hidden task
 * carried by a role file gets a bodyless `[tasks.X] hide = true` merge.
 *
 * @param flavors - Disk-derived build flavors
 *
 * @param entry - Manifest entry declaring non-derivable boilerplate
 *
 * @param custom - Verbatim bespoke TOML appended after generated blocks, or undefined
 *
 * @returns Complete `mise.toml` content with a single trailing newline
 *
 * @example
 * ```ts
 * renderPackageMiseToml({
 *   flavors: ['node'],
 *   entry: { lintTest: 'lint lint:types lint:oxlint', },
 *   custom: undefined,
 * });
 * ```
 */
export function renderPackageMiseToml(
  {
    flavors,
    entry,
    custom,
  }: {
    readonly flavors: readonly MiseFlavor[];
    readonly entry: MisePackageEntry;
    readonly custom: string | undefined;
  },
): string {
  /**
   * Ordered boilerplate tasks this package exposes.
   */
  const taskNames = computePackageTasks({ flavors, entry, },);
  /**
   * Membership set for role-file superset checks.
   */
  const taskSet = new Set<string>(taskNames,);
  /**
   * Task names carrying `hide = true`.
   */
  const hideSet = new Set(splitWords(entry.hide ?? '',),);
  /**
   * Role files whose whole task set the package has, plus the tasks they cover.
   */
  const covered = new Set<string>();
  const includedFiles = miseRoleFiles
    .filter(function packageHasWholeRole(role: MiseRoleFile,): boolean {
      return role.tasks.every(function present(task,): boolean {
        return taskSet.has(task,);
      },);
    },)
    .map(function recordCoverage(role: MiseRoleFile,): string {
      for (const task of role.tasks)
        covered.add(task,);

      return role.file;
    },);
  /**
   * Bodyless hide merges for hidden tasks a role file already defines.
   */
  const hideMerges = taskNames
    .filter(function hiddenAndCovered(name,): boolean {
      return hideSet.has(name,) && covered.has(name,);
    },)
    .map(function toMerge(name,): string {
      return `[tasks.${quoteTaskKey(name,)}]\nhide = true`;
    },);
  /**
   * Inline full bodies for tasks no whole role file covered.
   */
  const inlineTasks = taskNames
    .filter(function uncovered(name,): boolean {
      return !covered.has(name,);
    },)
    .map(function toInline(name,): string {
      return renderInlineTask({
        name,
        body: miseTaskBodies[name],
        hidden: hideSet.has(name,),
      },);
    },);
  /**
   * Generated and bespoke blocks in emission order; custom appended verbatim.
   */
  const blocks = [
    ...renderIncludesBlock(includedFiles,) === '' ? [] : [renderIncludesBlock(includedFiles,),],
    ...hideMerges,
    ...inlineTasks,
    ...custom === undefined ? [] : [custom.trimEnd(),],
  ];
  return `${GENERATED_HEADER}\n\n${blocks.join('\n\n',)}\n`;
}

/**
 * Reads the verbatim bespoke TOML for a package, if any.
 *
 * @param packageDir - Repo-relative package directory (e.g. `packages/cli/git`)
 *
 * @returns Custom TOML content, or undefined when the package has none
 *
 * @example
 * ```ts
 * await readCustom({ packageDir: 'packages/cli/git', });
 * ```
 */
async function readCustom({ packageDir, }: { readonly packageDir: string; },): Promise<string | undefined> {
  /**
   * Bespoke-task source path, mirroring the package path under mise-packages/.
   */
  const customPath = `./mise-packages/${packageDir.slice('packages/'.length,)}.toml`;
  if (!existsSync(customPath,))
    return undefined;

  return await readFile(customPath, 'utf8',);
}

/**
 * Generates the shared role files under mise-shared/, each carrying the boilerplate
 * task bodies for its role in bare full-body format. Whole-file `overwrite()` makes
 * regeneration idempotent.
 *
 * @example
 * ```ts
 * await generateSharedRoleFiles();
 * ```
 */
async function generateSharedRoleFiles(): Promise<void> {
  await Promise.all(
    miseRoleFiles.map(async function generateOne(role: MiseRoleFile,): Promise<void> {
      /**
       * Bare full-body entries for every task this role file owns.
       */
      const entries = role.tasks.map(function toEntry(name,): string {
        return renderSharedEntry({ name, body: miseTaskBodies[name], },);
      },);
      await overwrite({
        dest: `./mise-shared/${role.file}`,
        content: `${SHARED_HEADER}\n\n${entries.join('\n',)}\n`,
      },);
    },),
  );
}

/**
 * Generates the shared role files and every per-package `mise.toml` listed in the
 * manifest, deriving build flavors from disk and appending verbatim bespoke tasks.
 * Registered in the top-level `Promise.all` of file-enforcer.config.ts alongside the
 * other managed-output generators; `overwrite()` content-skips unchanged files so two
 * runs are a no-op.
 *
 * @example
 * ```ts
 * await generatePackageMiseTasks();
 * ```
 */
export async function generatePackageMiseTasks(): Promise<void> {
  await generateSharedRoleFiles();
  await Promise.all(
    Object.entries(misePackages,).map(async function generateOne([packageDir, entry,],): Promise<void> {
      /**
       * Disk-derived flavors for this package.
       */
      const flavors = deriveFlavors({ packageDir, },);
      /**
       * Verbatim bespoke TOML for this package, if any.
       */
      const custom = await readCustom({ packageDir, },);
      await overwrite({
        dest: `./${packageDir}/mise.toml`,
        content: renderPackageMiseToml({
          flavors,
          entry,
          custom,
        },),
      },);
    },),
  );
}
