import { existsSync, } from 'node:fs';
import { readFile, } from 'node:fs/promises';

import { overwrite, } from '@monochromatic-dev/dev-script-file-enforcer/ts';

import {
  type MiseFlavor,
  type MisePackageEntry,
  misePackages,
} from './mise-packages.config.ts';

/**
 * Canonical build-flavor order; the only disk-derived axis of generation.
 * A flavor is present iff `tsdown.{flavor}.config.ts` exists in the package.
 */
const FLAVORS: readonly MiseFlavor[] = [
  'node',
  'browser',
  'client',
];

/**
 * Build aggregators emitted (in this order) when a flavored package keeps the
 * standard set; irregular packages override the set via `entry.buildAggregators`.
 */
const STANDARD_AGGREGATORS: readonly string[] = [
  'build',
  'build:js',
  'watch:build',
  'watch:build:js',
];

/**
 * Header marking each generated `mise.toml` as managed output, mirroring the
 * `# Generated ... by file-enforcer` convention of the other managed files.
 */
const GENERATED_HEADER = `# Generated by file-enforcer from mise-packages.config.ts; do not hand-edit.
# Build flavors derive from tsdown.{node,browser,client}.config.ts presence.
# Bespoke tasks (if any) live in mise-packages/<category>/<package>.toml.`;

/**
 * Splits a space-separated manifest field into its task names, treating the
 * empty string as the empty list (an explicit "none", distinct from `undefined`).
 *
 * @param value - Space-separated task names, or empty string for none
 *
 * @returns Task names in declared order
 *
 * @example
 * ```ts
 * splitWords('build build:js'); // ['build', 'build:js']
 * splitWords(''); // []
 * ```
 */
function splitWords(value: string,): readonly string[] {
  return value.length === 0 ? [] : value.split(' ',);
}

/**
 * Quotes a task name for a `[tasks.X]` header: names containing `:` need TOML
 * quoting, bare alphanumeric names do not.
 *
 * @param name - Task name to place in a table header
 *
 * @returns Header-safe key, double-quoted when it contains a colon
 *
 * @example
 * ```ts
 * quoteTaskKey('build'); // 'build'
 * quoteTaskKey('build:js'); // '"build:js"'
 * ```
 */
function quoteTaskKey(name: string,): string {
  return name.includes(':',) ? `"${name}"` : name;
}

/**
 * Reads the disk-derived build flavors for a package from its tsdown configs.
 *
 * @param packageDir - Repo-relative package directory (e.g. `packages/cli/git`)
 *
 * @returns Present flavors in canonical order
 *
 * @example
 * ```ts
 * deriveFlavors({ packageDir: 'packages/module/logger', }); // ['node', 'browser']
 * ```
 */
export function deriveFlavors({ packageDir, }: { readonly packageDir: string; },): readonly MiseFlavor[] {
  return FLAVORS.filter(function flavorOnDisk(flavor,): boolean {
    return existsSync(`${packageDir}/tsdown.${flavor}.config.ts`,);
  },);
}

/**
 * Renders one `extends` task block, optionally hidden.
 *
 * @param name - Task name (also the extends target)
 *
 * @param hidden - Whether to append `hide = true`
 *
 * @returns TOML block without trailing blank line
 *
 * @example
 * ```ts
 * renderTaskBlock({ name: 'lint:types', hidden: true, });
 * // '[tasks."lint:types"]\nextends = "lint:types"\nhide = true'
 * ```
 */
function renderTaskBlock({ name, hidden, }: { readonly name: string; readonly hidden: boolean; },): string {
  /**
   * Optional hide line appended after the extends line for hidden tasks.
   */
  const hideLine = hidden ? '\nhide = true' : '';
  return `[tasks.${quoteTaskKey(name,)}]\nextends = "${name}"${hideLine}`;
}

/**
 * Renders the full `mise.toml` for one package from derived flavors, the manifest
 * entry, and the verbatim custom block. This is the extends-renderer; a sibling
 * worktree can swap it for an includes-renderer over the same manifest.
 *
 * @param flavors - Disk-derived build flavors
 *
 * @param entry - Manifest entry declaring non-derivable boilerplate
 *
 * @param custom - Verbatim bespoke TOML appended after generated blocks, or undefined
 *
 * @returns Complete `mise.toml` content with a single trailing newline
 *
 * @example
 * ```ts
 * renderPackageMiseToml({
 *   flavors: ['node'],
 *   entry: { lintTest: 'lint lint:types lint:oxlint', },
 *   custom: undefined,
 * });
 * ```
 */
export function renderPackageMiseToml(
  {
    flavors,
    entry,
    custom,
  }: {
    readonly flavors: readonly MiseFlavor[];
    readonly entry: MisePackageEntry;
    readonly custom: string | undefined;
  },
): string {
  /**
   * Task names carrying `hide = true`, looked up per emitted block.
   */
  const hideSet = new Set(splitWords(entry.hide ?? '',),);
  /**
   * Aggregators to emit: manifest override when present, else the standard set
   * for flavored packages and none for flavor-less packages.
   */
  const aggregators = entry.buildAggregators === undefined
    ? (flavors.length === 0 ? [] : STANDARD_AGGREGATORS)
    : splitWords(entry.buildAggregators,);
  /**
   * Flavors whose `watch:build:js:{flavor}` leaf is emitted (present minus noWatch).
   */
  const watchExcluded = new Set(splitWords(entry.noWatch ?? '',),);
  /**
   * Build flavors that keep their watch leaf.
   */
  const watchFlavors = flavors.filter(function keepsWatchLeaf(flavor,): boolean {
    return !watchExcluded.has(flavor,);
  },);
  /**
   * Ordered task names for the build/watch graph: aggregators interleaved with
   * the disk-derived flavor and watch leaves.
   */
  const buildNames = [
    ...aggregators.includes('build',) ? ['build',] : [],
    ...aggregators.includes('build:js',) ? ['build:js',] : [],
    ...flavors.map(function buildLeaf(flavor,): string {
      return `build:js:${flavor}`;
    },),
    ...aggregators.includes('watch:build',) ? ['watch:build',] : [],
    ...aggregators.includes('watch:build:js',) ? ['watch:build:js',] : [],
    ...watchFlavors.map(function watchLeaf(flavor,): string {
      return `watch:build:js:${flavor}`;
    },),
  ];
  /**
   * All generated task names: build graph followed by the lint/test boilerplate.
   */
  const taskNames = [
    ...buildNames,
    ...splitWords(entry.lintTest,),
  ];
  /**
   * Rendered generated blocks, each as an extends task.
   */
  const blocks = taskNames.map(function toBlock(name,): string {
    return renderTaskBlock({
      name,
      hidden: hideSet.has(name,),
    },);
  },);
  /**
   * Trimmed custom block, or empty when the package has no bespoke tasks.
   */
  const customBlock = custom === undefined ? '' : `\n\n${custom.trimEnd()}`;
  return `${GENERATED_HEADER}\n\n${blocks.join('\n\n',)}${customBlock}\n`;
}

/**
 * Reads the verbatim bespoke TOML for a package, if any.
 *
 * @param packageDir - Repo-relative package directory (e.g. `packages/cli/git`)
 *
 * @returns Custom TOML content, or undefined when the package has none
 *
 * @example
 * ```ts
 * await readCustom({ packageDir: 'packages/cli/git', });
 * ```
 */
async function readCustom({ packageDir, }: { readonly packageDir: string; },): Promise<string | undefined> {
  /**
   * Bespoke-task source path, mirroring the package path under mise-packages/.
   */
  const customPath = `./mise-packages/${packageDir.slice('packages/'.length,)}.toml`;
  if (!existsSync(customPath,))
    return undefined;

  return await readFile(customPath, 'utf8',);
}

/**
 * Generates every per-package `mise.toml` listed in the manifest, deriving build
 * flavors from disk and appending verbatim bespoke tasks. Registered in the
 * top-level `Promise.all` of file-enforcer.config.ts alongside the other
 * managed-output generators; `overwrite()` content-skips unchanged files so two
 * runs are a no-op.
 *
 * @example
 * ```ts
 * await generatePackageMiseTasks();
 * ```
 */
export async function generatePackageMiseTasks(): Promise<void> {
  await Promise.all(
    Object.entries(misePackages,).map(async function generateOne([packageDir, entry,],): Promise<void> {
      /**
       * Disk-derived flavors for this package.
       */
      const flavors = deriveFlavors({ packageDir, },);
      /**
       * Verbatim bespoke TOML for this package, if any.
       */
      const custom = await readCustom({ packageDir, },);
      await overwrite({
        dest: `./${packageDir}/mise.toml`,
        content: renderPackageMiseToml({
          flavors,
          entry,
          custom,
        },),
      },);
    },),
  );
}
