packages:
- packages/*/*
autoInstallPeers: false
catalog:
  browserslist: '*'
  zod: '*'
  dprint: '*'
  esbuild: '*'
  husky: '*'
  oxlint: '*'
  stylelint: '*'
  stylelint-config-standard: '*'
  typescript: '*'
  '@ungap/structured-clone': '*'
  find-up: '*'
  glob: '*'
  oxc-resolver: '*'
  smol-toml: '*'
  zod-opts: '*'
  '@kazupon/gunshi': jsr:*
  '@types/bun': '*'
  postcss-html: '*'
  '@types/mdx': '*'
  vite: '>=6.3.5'
  vite-plugin-singlefile: '*'
  '@csstools/postcss-color-function': '*'
  '@csstools/postcss-color-mix-function': '*'
  '@csstools/postcss-contrast-color-function': '*'
  '@csstools/postcss-extract': '*'
  '@csstools/postcss-gradients-interpolation-method': '*'
  '@csstools/postcss-light-dark-function': '*'
  '@csstools/postcss-oklab-function': '*'
  '@csstools/postcss-relative-color-syntax': '*'
  '@csstools/custom-units': '*'
  postcss-calc: '*'
  postcss-color-functional-notation: '*'
  postcss-color-hex-alpha: '*'
  postcss-convert-values: '*'
  postcss-custom-properties: '*'
  postcss-custom-media: '*'
  postcss-custom-selectors: '*'
  postcss-discard-comments: '*'
  postcss-discard-duplicates: '*'
  postcss-discard-empty: '*'
  postcss-discard-overridden: '*'
  postcss-discard-unused: '*'
  postcss-merge-idents: '*'
  postcss-merge-longhand: '*'
  postcss-merge-rules: '*'
  postcss-minify-font-values: '*'
  postcss-minify-gradients: '*'
  postcss-minify-params: '*'
  postcss-minify-selectors: '*'
  postcss-mixins: '*'
  postcss-nesting: '*'
  postcss-normalize-charset: '*'
  postcss-normalize-display-values: '*'
  postcss-normalize-positions: '*'
  postcss-normalize-repeat-style: '*'
  postcss-normalize-string: '*'
  postcss-normalize-timing-functions: '*'
  postcss-normalize-unicode: '*'
  postcss-normalize-url: '*'
  postcss-normalize-whitespace: '*'
  postcss-ordered-values: '*'
  '@figma/plugin-typings': '*'
  lfi: '*'
  lightningcss: '*'
  postcss: '*'
  '@logtape/logtape': '>=0.9.1'
  '@logtape/file': '>=0.9.1'
  type-fest: '*'
  execa: '*'
  nano-spawn: '*'
  astro: '*'
  '@astrojs/mdx': '*'
  '@astrojs/rss': '*'
  '@shikijs/transformers': '>=3.3.0'
  '@vitejs/plugin-basic-ssl': '*'
  unified: '*'
  to-vfile: '*'
  remark-github-blockquote-alert: '*'
  remark-sectionize: '*'
  rehype-stringify: '*'
  rehype-slug-custom-id: '*'
  rehype-preset-minify: '*'
  rehype-parse: '*'
  rehype-autolink-headings: '*'
  rambdax: '*'
  ses: '*'
  the-new-css-reset: '*'
  TODS: github:clagnut/TODS
  '@mdx-js/vue': '*'
  vue: '*'
  '@cspotcode/outdent': jsr:*
  # To look inside the error and see the stack trace
  serialize-error: '*'
  # Promising fp lib that supports concurrency.
  '@fxts/core': '*'
  # Fast, concurrent testing framework
  vitest: '>=3.1.3'
  # Type checker used by Vitest that supports Vue
  'vue-tsc': '>=2.2.10'
  '@vitest/coverage-v8': '*'
  '@types/postcss-mixins': '*'
childConcurrency: 16
dedupeDirectDeps: true
disallowWorkspaceCycles: true
hoist: false
hoistWorkspacePackages: false
includeWorkspaceRoot: true
linkWorkspacePackages: true
managePackageManagerVersions: false
nodeLinker: isolated
onlyBuiltDependencies:
- dprint
- esbuild
- sharp
- husky
overrides:
  tsconfck>typescript: '*'
  zod-to-ts>typescript: '*'
packageExtensions:
  astro:
    dependencies:
      typescript: '*'
preferWorkspacePackages: true
resolutionMode: highest
savePrefix: ''
saveWorkspaceProtocol: false
shellEmulator: true
strictDepBuilds: true
strictPeerDependencies: true
supportedArchitectures:
  os: [win32, darwin, linux, current]
  cpu: [x64, arm64, current]
  libc: [glibc, musl, current]
# Too slow, disabled.
# verifyDepsBeforeRun: install
