packages:
- packages/*/*

autoInstallPeers: false

catalog:
  browserslist: '*'
  zod: 3.25.71
  dprint: '*'
  esbuild: '*'
  oxlint: '>=1.1.0'
  stylelint: '*'
  stylelint-config-standard: '*'
  typescript: '>=5.9.1'
  '@ungap/structured-clone': '*'
  find-up: '*'
  glob: '*'
  tinyglobby: '*'
  oxc-resolver: '*'
  eslint-plugin-tsdoc: '*'
  exa-js: '*'
  smol-toml: '*'
  zod-opts: '*'
  '@typescript-eslint/parser': '*'
  '@kazupon/gunshi': jsr:*
  '@types/bun': '*'
  postcss-html: '*'
  '@types/mdx': '*'
  vite: 'npm:rolldown-vite@>=7.0.12'
  vite-plugin-singlefile: '*'
  '@csstools/postcss-color-function': '*'
  '@csstools/postcss-color-mix-function': '*'
  '@csstools/postcss-contrast-color-function': '*'
  '@csstools/postcss-remove': '*'
  '@csstools/postcss-gradients-interpolation-method': '*'
  '@csstools/postcss-light-dark-function': '*'
  '@csstools/postcss-oklab-function': '*'
  '@csstools/postcss-relative-color-syntax': '*'
  '@csstools/custom-units': '*'
  postcss-calc: '*'
  postcss-color-functional-notation: '*'
  postcss-color-hex-alpha: '*'
  postcss-convert-values: '*'
  postcss-custom-properties: '*'
  postcss-custom-media: '*'
  postcss-custom-selectors: '*'
  postcss-discard-comments: '*'
  postcss-discard-duplicates: '*'
  postcss-discard-empty: '*'
  postcss-discard-overridden: '*'
  postcss-discard-unused: '*'
  postcss-merge-idents: '*'
  postcss-merge-longhand: '*'
  postcss-merge-rules: '*'
  postcss-minify-font-values: '*'
  postcss-minify-gradients: '*'
  postcss-minify-params: '*'
  postcss-minify-selectors: '*'
  postcss-mixins: '*'
  postcss-nesting: '*'
  postcss-normalize-charset: '*'
  postcss-normalize-display-values: '*'
  postcss-normalize-positions: '*'
  postcss-normalize-repeat-style: '*'
  postcss-normalize-string: '*'
  postcss-normalize-timing-functions: '*'
  postcss-normalize-unicode: '*'
  postcss-normalize-url: '*'
  postcss-normalize-whitespace: '*'
  minimatch: '*'
  postcss-ordered-values: '*'
  '@csstools/css-tokenizer': '>=3.0.3'
  '@figma/plugin-typings': '*'
  lfi: '*'
  lightningcss: '*'
  postcss: '>=8.5.5'
  '@logtape/logtape': jsr:>=0.9.2
  '@logtape/file': jsr:>=0.9.2
  type-fest: '*'
  execa: '>=9.5.3'
  nano-spawn: '*'
  astro: '*'
  meilisearch: '*'
  '@astrojs/mdx': '*'
  '@astrojs/rss': '*'
  '@shikijs/transformers': '>=3.3.0'
  '@vitejs/plugin-basic-ssl': '*'
  unified: '*'
  to-vfile: '*'
  rolldown-vite: '>=7.0.11'
  remark-github-blockquote-alert: '*'
  remark-sectionize: '*'
  rehype-stringify: '*'
  rehype-slug-custom-id: '*'
  rehype-preset-minify: '*'
  rehype-parse: '*'
  rehype-autolink-headings: '*'
  rambdax: '*'
  ses: '*'
  '@openrouter/ai-sdk-provider': '*'
  '@mastra/core': '*'
  openapi-types: '*'
  react: '*'
  the-new-css-reset: '*'
  TODS: github:clagnut/TODS
  '@mdx-js/vue': '*'
  '@typescript-eslint/utils': '*'
  vue: '*'
  '@cspotcode/outdent': jsr:*
  '@typescript-eslint/scope-manager': '*'
  serialize-error: '*'
  '@fxts/core': '*'
  '@typescript-eslint/types': '*'
  vitest: '>=4.0.0-beta.8'
  vue-tsc: '>=2.2.10'
  '@vitest/browser': '>=4.0.0-beta.8'
  playwright: '>=1.52.0'
  '@vitest/coverage-v8': '>=4.0.0-beta.8'
  '@vitest/ui': '>=4.0.0-beta.8'
  '@vitest/coverage-istanbul': '>=4.0.0-beta.8'
  '@total-typescript/ts-reset': '*'
  '@types/postcss-mixins': '*'
  '@typescript-eslint/eslint-plugin': '*'
  '@elysiajs/static': '*'
  ts-pattern: '*'
  oxc-minify: '*'
  mdx2vast: '*'
  memfs: '>=4.17.2'
  happy-opfs: '>=1.8.6'
  eslint-p: '>=0.23.0'
  eslint-plugin-oxlint: '>=0.16.11'
  jiti: '>=2.4.2'
  eslint: '>=9.29.0'
  '@eslint/js': '>=9.29.0'
  typescript-eslint: '>=8.32.1'
  vite-plugin-json5: '>=1.1.9'
  happy-rusty: '*'
  eslint-plugin-jsdoc: '>=50.6.17'
  eslint-plugin-n: '>=17.18.0'
  '@vitest/eslint-plugin': '>=1.2.1'
  eslint-plugin-unicorn: '>=59.0.1'
  feedsmith: '*'
  istanbul-lib-report: '*'
  eslint-plugin-astro: '>=1.3.1'
  eslint-plugin-jsx-a11y: '>=6.10.2'
  '@eslint/core': '*'
  '@eslint/plugin-kit': '>=0.3.4'
  '@moonrepo/cli': '>=1.36.3'
  sugarss: '*'
  '@types/node': ^24.0.10
  rollup: '*'
  elysia: '*'
  file-type: '>=20.0.0'
  '@aws-crypto/sha256-js': '*'
  '@typers/react': '*'
  '@elysiajs/swagger': '*'
  ai: '*'
  '@ai-sdk/react': '*'
  'swr': '*'
  'use-sync-external-store': '*'
  remark-cli: '*'
  remark-lint-blockquote-indentation: '*'
  remark-lint-checkbox-character-style: '*'
  remark-lint-code-block-style: '*'
  remark-lint-definition-case: '*'
  remark-lint-definition-spacing: '*'
  remark-lint-emphasis-marker: '*'
  remark-lint-fenced-code-flag: '*'
  remark-lint-fenced-code-marker: '*'
  remark-lint-file-extension: '*'
  remark-lint-final-definition: '*'
  remark-lint-final-newline: '*'
  remark-lint-hard-break-spaces: '*'
  remark-lint-heading-increment: '*'
  remark-lint-heading-style: '*'
  remark-lint-link-title-style: '*'
  remark-lint-list-item-bullet-indent: '*'
  remark-lint-list-item-content-indent: '*'
  remark-lint-list-item-indent: '*'
  remark-lint-list-item-spacing: '*'
  remark-lint-maximum-heading-length: '*'
  remark-lint-maximum-line-length: '*'
  remark-lint-no-blockquote-without-marker: '*'
  remark-lint-no-consecutive-blank-lines: '*'
  remark-lint-no-duplicate-definitions: '*'
  remark-lint-no-duplicate-headings: '*'
  remark-lint-no-emphasis-as-heading: '*'
  remark-lint-no-file-name-articles: '*'
  remark-lint-no-file-name-consecutive-dashes: '*'
  remark-lint-no-file-name-irregular-characters: '*'
  remark-lint-no-file-name-mixed-case: '*'
  remark-lint-no-file-name-outer-dashes: '*'
  remark-lint-no-heading-content-indent: '*'
  remark-lint-no-heading-punctuation: '*'
  remark-lint-no-literal-urls: '*'
  remark-lint-no-multiple-toplevel-headings: '*'
  remark-lint-no-shell-dollars: '*'
  remark-lint-no-shortcut-reference-image: '*'
  remark-lint-no-shortcut-reference-link: '*'
  remark-lint-no-table-indentation: '*'
  remark-lint-no-undefined-references: '*'
  remark-lint-no-unused-definitions: '*'
  remark-lint-ordered-list-marker-style: '*'
  remark-lint-ordered-list-marker-value: '*'
  remark-lint-rule-style: '*'
  remark-lint-strong-marker: '*'
  remark-lint-table-cell-padding: '*'
  remark-lint-table-pipe-alignment: '*'
  remark-lint-table-pipes: '*'
  remark-lint-unordered-list-marker-style: '*'
  '@anthropic-ai/sdk': '*'
  socket: '*'
  '@vue/runtime-dom': '*'
  '@vue/server-renderer': '*'
  'preact': '*'
  'preact-render-to-string': '*'
  'happy-dom': "*"
  'chokidar': '*'
  'watcher': '*'

catalogMode: strict

childConcurrency: 16

dedupeDirectDeps: true

enableGlobalVirtualStore: true

hoist: false

hoistWorkspacePackages: false

includeWorkspaceRoot: true

linkWorkspacePackages: true

managePackageManagerVersions: false

nodeLinker: isolated

onlyBuiltDependencies:
- '@moonrepo/cli'
- dprint
- esbuild
- protobufjs
- sharp

overrides:
  typescript: 'catalog:'
  vite: 'catalog:'
  vitest: 'catalog:'
  rollup: 'catalog:'
  postcss: 'catalog:'
  sugarss: 'catalog:'
  esbuild: 'catalog:'
  astro: 'catalog:'
  react: 'catalog:'
  rolldown-vite: 'catalog:'
  vue: 'catalog:'

packageExtensions:
  vitest:
    dependencies:
      strip-literal: '>=3.0.0'
  '@vitest/browser':
    peerDependencies:
      vite: '*'
  stylelint:
    dependencies:
      postcss-html: '*'
  vite-plugin-json5:
    dependencies:
      rollup: '*'
  vite-plugin-singlefile:
    dependencies:
      rollup: '*'
  '@types/bun':
    dependencies:
      '@types/react': '*'
  elysia:
    dependencies:
      file-type: '*'
  '@openrouter/ai-sdk-provider':
    dependencies:
      ai: '*'
  ai:
    dependencies:
      react: '*'
  'swr':
    dependencies:
      react: '*'
  'use-sync-external-store':
    dependencies:
      react: '*'

packageImportMethod: hardlink

peerDependencyRules:
  allowedVersions:
    '@vitejs/plugin-basic-ssl>vite': '*'
    vite-plugin-singlefile>vite: '*'
    vite-plugin-json5>vite: '*'
    '@typescript-eslint/project-service>typescript': '*'
    '@typescript-eslint/tsconfig-utils>typescript': '*'
    '@typescript-eslint/type-utils>typescript': '*'

preferWorkspacePackages: true

resolutionMode: highest

resolvePeersFromWorkspaceRoot: false

savePrefix: ''

saveWorkspaceProtocol: false

shellEmulator: false

strictDepBuilds: true

strictPeerDependencies: true

supportedArchitectures:
  os: [darwin, linux, current]
  cpu: [x64, arm64, current]
  libc: [glibc, musl, current]
