packages:
- packages/*/*
autoInstallPeers: false
catalog:
  browserslist: '*'
  zod: '>=3.25.67'
  dprint: '*'
  esbuild: '*'
  oxlint: '>=1.1.0'
  stylelint: '*'
  stylelint-config-standard: '*'
  typescript: '*'
  '@ungap/structured-clone': '*'
  find-up: '*'
  glob: '*'
  tinyglobby: '*'
  oxc-resolver: '*'
  eslint-plugin-tsdoc: '*'
  exa-js: '*'
  smol-toml: '*'
  zod-opts: '*'
  '@typescript-eslint/parser': '*'
  '@kazupon/gunshi': jsr:*
  '@types/bun': '*'
  postcss-html: '*'
  '@types/mdx': '*'
  vite: 'npm:rolldown-vite'
  vite-plugin-singlefile: '*'
  '@csstools/postcss-color-function': '*'
  '@csstools/postcss-color-mix-function': '*'
  '@csstools/postcss-contrast-color-function': '*'
  '@csstools/postcss-remove': '*'
  '@csstools/postcss-gradients-interpolation-method': '*'
  '@csstools/postcss-light-dark-function': '*'
  '@csstools/postcss-oklab-function': '*'
  '@csstools/postcss-relative-color-syntax': '*'
  '@csstools/custom-units': '*'
  postcss-calc: '*'
  postcss-color-functional-notation: '*'
  postcss-color-hex-alpha: '*'
  postcss-convert-values: '*'
  postcss-custom-properties: '*'
  postcss-custom-media: '*'
  postcss-custom-selectors: '*'
  postcss-discard-comments: '*'
  postcss-discard-duplicates: '*'
  postcss-discard-empty: '*'
  postcss-discard-overridden: '*'
  postcss-discard-unused: '*'
  postcss-merge-idents: '*'
  postcss-merge-longhand: '*'
  postcss-merge-rules: '*'
  postcss-minify-font-values: '*'
  postcss-minify-gradients: '*'
  postcss-minify-params: '*'
  postcss-minify-selectors: '*'
  postcss-mixins: '*'
  postcss-nesting: '*'
  postcss-normalize-charset: '*'
  postcss-normalize-display-values: '*'
  postcss-normalize-positions: '*'
  postcss-normalize-repeat-style: '*'
  postcss-normalize-string: '*'
  postcss-normalize-timing-functions: '*'
  postcss-normalize-unicode: '*'
  postcss-normalize-url: '*'
  postcss-normalize-whitespace: '*'
  minimatch: '*'
  postcss-ordered-values: '*'
  '@csstools/css-tokenizer': '>=3.0.3'
  '@figma/plugin-typings': '*'
  lfi: '*'
  lightningcss: '*'
  postcss: '>=8.5.5'
  '@logtape/logtape': jsr:>=0.9.2
  '@logtape/file': jsr:>=0.9.2
  type-fest: '*'
  execa: '>=9.5.3'
  nano-spawn: '*'
  astro: '*'
  meilisearch: '*'
  '@astrojs/mdx': '*'
  '@astrojs/rss': '*'
  '@shikijs/transformers': '>=3.3.0'
  '@vitejs/plugin-basic-ssl': '*'
  unified: '*'
  to-vfile: '*'
  remark-github-blockquote-alert: '*'
  remark-sectionize: '*'
  rehype-stringify: '*'
  rehype-slug-custom-id: '*'
  rehype-preset-minify: '*'
  rehype-parse: '*'
  rehype-autolink-headings: '*'
  rambdax: '*'
  ses: '*'
  the-new-css-reset: '*'
  TODS: github:clagnut/TODS
  '@mdx-js/vue': '*'
  '@typescript-eslint/utils': '*'
  vue: '*'
  '@cspotcode/outdent': jsr:*
  '@typescript-eslint/scope-manager': '*'
  serialize-error: '*'
  '@fxts/core': '*'
  '@typescript-eslint/types': '*'
  vitest: '>=4.0.0-beta.2'
  vue-tsc: '>=2.2.10'
  '@vitest/browser': '>=4.0.0-beta.2'
  playwright: '>=1.52.0'
  '@vitest/coverage-v8': '>=4.0.0-beta.2'
  '@vitest/ui': '>=4.0.0-beta.2'
  '@vitest/coverage-istanbul': '>=4.0.0-beta.2'
  '@total-typescript/ts-reset': '*'
  '@types/postcss-mixins': '*'
  '@typescript-eslint/eslint-plugin': '*'
  ts-pattern: '*'
  oxc-minify: '*'
  'mdx2vast': '*'
  memfs: '>=4.17.2'
  happy-opfs: '>=1.8.6'
  eslint-p: '>=0.23.0'
  eslint-plugin-oxlint: '>=0.16.11'
  jiti: '>=2.4.2'
  eslint: '>=9.29.0'
  '@eslint/js': '>=9.29.0'
  typescript-eslint: '>=8.32.1'
  vite-plugin-json5: '>=1.1.9'
  happy-rusty: '*'
  eslint-plugin-jsdoc: '>=50.6.17'
  eslint-plugin-n: '>=17.18.0'
  '@vitest/eslint-plugin': '>=1.2.1'
  eslint-plugin-unicorn: '>=59.0.1'
  istanbul-lib-report: '*'
  eslint-plugin-astro: '>=1.3.1'
  eslint-plugin-jsx-a11y: '>=6.10.2'
  '@moonrepo/cli': '>=1.36.3'
  rollup: '*'
catalogs:
  vitest:
    vite: '>=7.0.0'
childConcurrency: 16
dedupeDirectDeps: true
disallowWorkspaceCycles: true
hoist: false
resolvePeersFromWorkspaceRoot: false
hoistWorkspacePackages: false
includeWorkspaceRoot: true
linkWorkspacePackages: true
managePackageManagerVersions: false
nodeLinker: isolated
onlyBuiltDependencies:
- '@moonrepo/cli'
- dprint
- esbuild
- sharp
overrides:
  tsconfck>typescript: 'catalog:'
  zod-to-ts>typescript: 'catalog:'
  astro>typescript: 'catalog:'
  vite>postcss: 'catalog:'
  vite: 'catalog:'
  vitest: 'catalog:'
  rollup: 'catalog:'
  postcss: 'catalog:'
packageExtensions:
  vitest:
    dependencies:
      'strip-literal': '>=3.0.0'
  '@vitest/browser':
    peerDependencies:
      vite: '*'
  stylelint:
    dependencies:
      'postcss-html': '*'
  vite-plugin-json5:
    dependencies:
      rollup: '*'
  vite-plugin-singlefile:
    dependencies:
      rollup: '*'
peerDependencyRules:
  allowedVersions:
    '@vitejs/plugin-basic-ssl>vite': '*'
    'vite-plugin-singlefile>vite': '*'
    'vite-plugin-json5>vite': '*'
preferWorkspacePackages: true
resolutionMode: highest
savePrefix: ''
saveWorkspaceProtocol: false
shellEmulator: false
strictDepBuilds: true
strictPeerDependencies: true
supportedArchitectures:
  os: [win32, darwin, linux, current]
  cpu: [x64, arm64, current]
  libc: [glibc, musl, current]
enableGlobalVirtualStore: true
catalogMode: strict
