/**
 * Perf test data loader.
 *
 * Reads pre-generated perf test inputs from disk at module load time.
 * Data files are generated by the mise.generate-*.ts scripts in this directory;
 * they are not checked into git (gitignored) and regenerated on demand.
 *
 * Only inputs are loaded; the perf test measures execution speed, not output
 * correctness (the correctness container handles that separately).
 *
 * Stak perf data is not included here because it lives in src/stak/ alongside
 * the reference interpreter and other Stak-specific test cases.
 */
import { readFile, } from 'node:fs/promises';

/**
 * Reads a data file from this directory.
 * @param filename - file name relative to this directory
 * @returns file content as a string
 */
async function readDataFile(filename: string,): Promise<string> {
  return readFile(new URL(`./${filename}`, import.meta.url,), 'utf8',);
}

/** Large CSV input: 2000 rows with quoted fields, embedded commas, escaped quotes, newlines */
export const CSV_PERF_INPUT: string = await readDataFile('csv-perf-input.txt',);

/** 5000 arithmetic expressions covering all operator/precedence combinations */
export const EXPR_PERF_INPUT: string = await readDataFile('expr-perf-input.txt',);

/** Large CSS with 20 mixins and 500 rule blocks using @apply */
export const CSS_MIXIN_PERF_INPUT: string = await readDataFile(
  'css-mixin-perf-input.txt',
);
