"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("@monochromatic-dev/module-es/logtape.ts"), exports);
__exportStar(require("./fixture.array.0to999.ts"), exports);
__exportStar(require("./fixture.generator.0to999.ts"), exports);
__exportStar(require("./fixture.promises.0to999.ts"), exports);
__exportStar(require("./any.echo.ts"), exports);
__exportStar(require("./any.toExport.ts"), exports);
__exportStar(require("./any.typeOf.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.at.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.chunks.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.entries.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.every.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.everyFail.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.map.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.none.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.noneFail.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.of.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.partition.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.ints.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.intsTo10.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.intsTo22.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.intsTo48.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.mapTo.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.maybe.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.tuple.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./arrayLike.type.withoutFirst.ts"), exports);
// TODO: Write joinArrayLike. The speced one uses ',' as the sep, which could be surprising.
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./boolean.equal.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./boolean.not.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./error.assert.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./error.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./error.throw.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./error.throws.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./function.curry.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./function.equals.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./function.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./function.nary.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./function.pipe.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./numeric.add.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./numeric.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./numeric.type.abs.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./numeric.type.nan.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./numeric.type.negative.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./promise.awaits.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./promise.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./promise.some.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./promise.type.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./promise.wait.ts"), exports);
__exportStar(require("./string.capitalize.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./string.concat.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./string.is.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./string.join.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./string.trim.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./string.type.ts"), exports);
/* @__NO_SIDE_EFFECTS__ */ __exportStar(require("./testing.ts"), exports);
