/**
 * Pure CLI helpers for spawn-pi.
 *
 * @module
 */

import type {
  PidMapping,
  SpawnState,
} from './paths.ts';
import { splitWhitespace, } from './text-scan.ts';

//region Constants

/**
 * Number of spawn-id characters shown in terminal title.
 */
const SPAWN_ID_TITLE_LENGTH = 8;

//endregion Constants

//region Types

/**
 * Parsed arguments used by spawn-pi launcher.
 */
type SpawnPiArgs = {
  /**
   * Additional Pi CLI arguments encoded like spawn-claude's extra arguments.
   */
  readonly extraArguments?: string;
  /**
   * Initial prompt sent to child Pi process.
   */
  readonly prompt: string;
};

/**
 * Built terminal-exec invocation.
 */
type TerminalInvocation = {
  /**
   * Executable name used to launch visible terminal.
   */
  readonly command: 'terminal-exec';
  /**
   * Arguments passed to terminal-exec.
   */
  readonly args: readonly string[];
};

//endregion Types

//region State construction

/**
 * Builds initial spawn state from parent identity and CLI arguments.
 *
 * @param spawnId - UUID generated by CLI.
 *
 * @param identity - resolved parent Pi session identity.
 *
 * @param cwd - working directory selected for child process.
 *
 * @returns spawn state ready for disk persistence.
 *
 * @example
 * ```typescript
 * initialSpawnState({ spawnId: 'abc', identity, cwd: '/repo' });
 * ```
 */
function initialSpawnState(
  {
    spawnId,
    identity,
    cwd,
  }: {
    readonly spawnId: string;
    readonly identity: PidMapping;
    readonly cwd: string;
  },
): SpawnState {
  return {
    spawnId,
    sessionId: '',
    sessionFile: '',
    parentSessionId: identity.sessionId,
    parentSessionFile: identity.sessionFile,
    cwd,
    status: 'running',
    lastMessage: '',
  };
}

//endregion State construction

//region Argument construction

/**
 * Builds optional child Pi extension arguments from parent mapping.
 *
 * @param identity - resolved parent Pi session identity.
 *
 * @returns `--extension` arguments when parent exposed extension path.
 *
 * @example
 * ```typescript
 * extensionArguments({ identity });
 * ```
 */
function extensionArguments(
  {
    identity,
  }: {
    readonly identity: PidMapping;
  },
): readonly string[] {
  /**
   * Extension path inherited from parent session mapping.
   */
  const { extensionPath, } = identity;

  return extensionPath.length > 0
    ? [
      '--extension',
      extensionPath,
    ]
    : [];
}

/**
 * Builds Pi command arguments passed after terminal-exec delimiter.
 *
 * @param args - parsed spawn-pi arguments.
 *
 * @param identity - resolved parent Pi session identity.
 *
 * @returns argv for child `pi` invocation.
 *
 * @example
 * ```typescript
 * piCommandArguments({ args: { prompt: 'work' }, identity });
 * ```
 */
function piCommandArguments(
  {
    args,
    identity,
  }: {
    readonly args: SpawnPiArgs;
    readonly identity: PidMapping;
  },
): readonly string[] {
  /**
   * Extra Pi CLI arguments split using spawn-claude-compatible whitespace semantics.
   */
  const extraArgs = splitWhitespace(args.extraArguments ?? '',);

  return [
    'pi',
    ...extensionArguments({ identity, },),
    ...extraArgs,
    args.prompt,
  ];
}

/**
 * Builds terminal-exec invocation for visible child Pi session.
 *
 * @param spawnId - UUID generated by CLI.
 *
 * @param args - parsed spawn-pi arguments.
 *
 * @param identity - resolved parent Pi session identity.
 *
 * @returns terminal-exec command and arguments.
 *
 * @example
 * ```typescript
 * terminalInvocation({ spawnId: 'abc', args: { prompt: 'work' }, identity });
 * ```
 */
function terminalInvocation(
  {
    spawnId,
    args,
    identity,
  }: {
    readonly spawnId: string;
    readonly args: SpawnPiArgs;
    readonly identity: PidMapping;
  },
): TerminalInvocation {
  /**
   * Short spawn identifier shown in terminal title.
   */
  const titleSpawnId = spawnId.slice(
    0,
    SPAWN_ID_TITLE_LENGTH,
  );

  return {
    command: 'terminal-exec',
    args: [
      `--title=spawn-pi ${titleSpawnId}`,
      '--',
      ...piCommandArguments({
        args,
        identity,
      },),
    ],
  };
}

//endregion Argument construction

export {
  extensionArguments,
  initialSpawnState,
  piCommandArguments,
  SPAWN_ID_TITLE_LENGTH,
  terminalInvocation,
};

export type {
  SpawnPiArgs,
  TerminalInvocation,
};
