/**
 * Shared counter domain for the Electron hello-world app.
 *
 * The renderer, main-process title observer, unit tests, and Wayland boundary
 * test all share these pure functions so UI text and observed state cannot drift.
 *
 * @example
 * ```ts
 * const next = incrementCount({ current: 0 });
 * console.log(formatCount({ count: next }));
 * ```
 *
 * @packageDocumentation
 */

/**
 * Initial counter value used when a new renderer document starts.
 *
 * @example
 * ```ts
 * console.log(INITIAL_COUNT);
 * ```
 */
export const INITIAL_COUNT = 0;

/**
 * Human-readable application title prefix shared by the window and document.
 *
 * @example
 * ```ts
 * console.log(APP_TITLE_PREFIX);
 * ```
 */
export const APP_TITLE_PREFIX = 'Monochromatic ESM TS Counter';

/**
 * Separator between the title prefix and machine-observable count value.
 *
 * @example
 * ```ts
 * console.log(TITLE_COUNT_SEPARATOR);
 * ```
 */
const TITLE_COUNT_SEPARATOR = ' :: count=';

/**
 * Sentinel returned when a document title is not one of this app's counter titles.
 *
 * @example
 * ```ts
 * console.log(typeof UNPARSEABLE_DOCUMENT_TITLE);
 * ```
 */
export const UNPARSEABLE_DOCUMENT_TITLE: unique symbol = Symbol(
  'Renderer page did not publish a parseable count suffix for Monochromatic counter',
);

/**
 * Text shown next to the counter button.
 *
 * @param count - Value to display to a user.
 *
 * @returns Human-readable counter label.
 *
 * @example
 * ```ts
 * formatCount({ count: 2 });
 * ```
 */
export function formatCount({ count, }: { readonly count: number; },): string {
  return `Count: ${count}`;
}

/**
 * Computes the next counter value after one activation.
 *
 * @param current - Current counter value before activation.
 *
 * @returns Incremented counter value.
 *
 * @example
 * ```ts
 * incrementCount({ current: 4 });
 * ```
 */
export function incrementCount({ current, }: { readonly current: number; },): number {
  return current + 1;
}

/**
 * Formats the document title so the main process can observe renderer state
 * without enabling Node.js integration or a preload bridge.
 *
 * @param count - Current renderer counter value.
 *
 * @returns Document title containing a parseable count suffix.
 *
 * @example
 * ```ts
 * formatDocumentTitle({ count: 3 });
 * ```
 */
export function formatDocumentTitle({ count, }: { readonly count: number; },): string {
  return `${APP_TITLE_PREFIX}${TITLE_COUNT_SEPARATOR}${count}`;
}

/**
 * Parses a counter value out of a document title produced by
 * {@link formatDocumentTitle}.
 *
 * @param title - Document title observed from Electron's main process.
 *
 * @returns Parsed count, or {@link UNPARSEABLE_DOCUMENT_TITLE} when title was not generated by this app.
 *
 * @example
 * ```ts
 * parseDocumentTitle({ title: 'Monochromatic ESM TS Counter :: count=5' });
 * ```
 */
export function parseDocumentTitle(
  { title, }: { readonly title: string; },
): number | typeof UNPARSEABLE_DOCUMENT_TITLE {
  /**
   * Prefix that must be present before a count suffix is considered ours.
   */
  const expectedPrefix = `${APP_TITLE_PREFIX}${TITLE_COUNT_SEPARATOR}`;

  if (!title.startsWith(expectedPrefix,))
    return UNPARSEABLE_DOCUMENT_TITLE;

  /**
   * Raw decimal count suffix after the known title prefix.
   */
  const countText = title.slice(expectedPrefix.length,);

  if (countText.length === 0)
    return UNPARSEABLE_DOCUMENT_TITLE;

  /**
   * Parsed numeric count from the renderer title.
   */
  const count = Number(countText,);

  return Number.isSafeInteger(count,)
    ? count
    : UNPARSEABLE_DOCUMENT_TITLE;
}
