[tasks.run]
description = "Run mvm CLI"
usage = 'arg "[args]" var=#true help="Subcommand and arguments"'
run = "bun src/cli.ts ...($env.usage_args? | default '' | split row ' ' | where {|part| $part != '' })"

[tasks.lint]
extends = "lint"

[tasks.'lint:types']
extends = "lint:types"

[tasks.'lint:oxlint']
extends = "lint:oxlint"
