import { configDependencyPaths, } from '../context.ts';
import type { TrackedGlob, } from '../tracker.ts';
import { destinationStamps, } from './staleness-destinations.ts';
import {
  registerFreshPaths,
  stampsAreFresh,
} from './staleness-freshness.ts';
import {
  loadManifest,
  writeManifest,
} from './staleness-manifest.ts';
import { hashSourceSet, } from './staleness-hash.ts';
import {
  normalizeGlobStamps,
  readFileStamps,
} from './staleness-stamps.ts';
import {
  ABSENT_FILE_STAMPS,
  type StalenessDestination,
  type StalenessEntry,
  type StalenessEntryKind,
} from './staleness-types.ts';

export type {
  StalenessDestination,
  StalenessEntryKind,
  StalenessOptions,
} from './staleness-types.ts';
export {
  resolveManifestPath,
  stalenessKeyForDest,
  stalenessKeyForDestGlob,
} from './staleness-manifest.ts';

/**
 * Checks whether a cached manifest entry, loaded via {@link loadManifest}, is
 * fresh per {@link stampsAreFresh} and registers its tracked paths with
 * {@link registerFreshPaths}.
 *
 * @param manifestPath - Resolved manifest path.
 *
 * @param key - Manifest key to inspect.
 *
 * @param kind - Expected entry kind.
 *
 * @returns Whether the builder can be skipped.
 *
 * @example
 * ```ts
 * const fresh = await freshStalenessEntryExists({ manifestPath, key, kind: 'single' });
 * ```
 */
export async function freshStalenessEntryExists(
  {
    manifestPath,
    key,
    kind,
  }: {
    readonly manifestPath: string;
    readonly key: string;
    readonly kind: StalenessEntryKind;
  },
): Promise<boolean> {
  /**
   * Persisted entry for this builder.
   */
  const entry = (await loadManifest(manifestPath,))
    .entries[key];
  if (entry === undefined)
    return false;
  if (entry.kind !== kind)
    return false;

  /**
   * Whether filesystem metadata still matches the entry.
   */
  const fresh = await stampsAreFresh({
    sourceFiles: entry.sourceFiles,
    sourceGlobs: entry.sourceGlobs,
    destinationFiles: entry.destinationFiles,
  },);
  if (!fresh)
    return false;

  registerFreshPaths({
    sourceFiles: entry.sourceFiles,
    destinationFiles: entry.destinationFiles,
  },);
  return true;
}

/**
 * Builds source metadata for a manifest entry: stats {@link configDependencyPaths}
 * plus `trackedReads` via {@link readFileStamps}.
 *
 * @param trackedReads - Source file reads captured while the builder ran.
 *
 * @returns Source metadata, or the {@link ABSENT_FILE_STAMPS} sentinel when a
 * source disappeared.
 *
 * @example
 * ```ts
 * const sourceFiles = await sourceStampsForReads(['./AGENTS.md']);
 * ```
 */
async function sourceStampsForReads(
  trackedReads: readonly string[],
): Promise<StalenessEntry['sourceFiles'] | typeof ABSENT_FILE_STAMPS> {
  return await readFileStamps([
    ...configDependencyPaths(),
    ...trackedReads,
  ],);
}

/**
 * Records a fresh manifest entry after a builder computes and reconciles output:
 * gathers source stamps via {@link sourceStampsForReads}, destination stamps via
 * {@link destinationStamps}, and glob stamps via {@link normalizeGlobStamps},
 * hashes them with {@link hashSourceSet}, then merges the entry into the
 * manifest loaded by {@link loadManifest} and persists it with {@link writeManifest}.
 *
 * @param manifestPath - Resolved manifest path.
 *
 * @param key - Manifest key to update.
 *
 * @param kind - Entry kind to persist.
 *
 * @param trackedReads - Source file reads captured while the builder ran.
 *
 * @param trackedGlobs - Glob expansions captured while the builder ran.
 *
 * @param destinations - Destinations generated by the builder.
 *
 * @example
 * ```ts
 * await rememberFreshStalenessEntry({ manifestPath, key, kind: 'single', trackedReads, trackedGlobs, destinations });
 * ```
 */
export async function rememberFreshStalenessEntry(
  {
    manifestPath,
    key,
    kind,
    trackedReads,
    trackedGlobs,
    destinations,
  }: {
    readonly manifestPath: string;
    readonly key: string;
    readonly kind: StalenessEntryKind;
    readonly trackedReads: readonly string[];
    readonly trackedGlobs: readonly TrackedGlob[];
    readonly destinations: readonly StalenessDestination[];
  },
): Promise<void> {
  /**
   * Source file metadata, including the config file as an implicit dependency.
   */
  const sourceFiles = await sourceStampsForReads(trackedReads,);
  if (sourceFiles === ABSENT_FILE_STAMPS)
    return;

  /**
   * Destination metadata after reconciliation.
   */
  const destinationFiles = await destinationStamps(destinations,);
  if (destinationFiles === ABSENT_FILE_STAMPS)
    return;

  /**
   * Captured glob expansions.
   */
  const sourceGlobs = normalizeGlobStamps(trackedGlobs,);
  /**
   * Entry to persist.
   */
  const entry: StalenessEntry = {
    kind,
    sourceFiles,
    sourceGlobs,
    destinationFiles,
    sourceSetHash: hashSourceSet({
      sourceFiles,
      sourceGlobs,
    },),
    updatedAt: new Date().toISOString(),
  };
  /**
   * Mutable manifest object for this path.
   */
  const manifest = await loadManifest(manifestPath,);
  manifest.entries[key] = entry;
  await writeManifest({
    manifestPath,
    manifest,
  },);
}
