title = "Subtle"
description = "Personal Blog Theme for Astro"
author.name = "Aquaticat"
author.url = 'https://aquati.cat'
site = 'https://monochromatic.dev'
base = 'subtle'
license = 'CC-BY-SA-4.0'

[theming]
color = '#966783'
shiki.light = 'github-light'
shiki.dark = 'github-dark'

[socials]
'RSS Feed' = 'https://aquati.cat/rss'
'Email' = 'mailto:an@aquati.cat?subject=Email author of Monochromatic/Subtle'
'GitHub' = 'https://github.com/Aquaticat'
'Telegram' = 'https://t.me/Aquaticat'

[links]
'Catoverflow' = 'https://c-j.dev'
'dummy1' = 'https://example.com'
'big dummy2' = 'https://example.com'
'big big dummy1' = 'https://example.com'
'big big dummy2' = 'https://example.com'
'dummy3' = 'https://example.com'
'dummy4' = 'https://example.com'
'dummy5' = 'https://example.com'
'dummy6' = 'https://example.com'

[strings]
en.searchPlaceholder = 'Search tags, topics, or snippets with DuckDuckGo'
zh.searchPlaceholder = '搜索关键词，话题，或文段（DuckDuckGo）'
