[tasks.'build:js']
extends = "build:js"

# [tasks.'build:js:browser']
# run = "tsdown"

[tasks.'build:js:node']
extends = "build:js:node"

[tasks."build--watch:js"]
extends = "build--watch:js"

# [tasks.'build--watch:js:browser']
# run = "tsdown --watch"

[tasks.'build--watch:js:node']
extends = "build--watch:js:node"
