$schema: 'https://moonrepo.dev/schemas/project.json'
language: 'typescript'

tags:
- dual
- package

toolchain:
  typescript:
    # Cannot use project references because no other packages is guaranteed to be built when it's invoked.
    syncProjectReferences: false
