$schema: 'https://moonrepo.dev/schemas/project.json'
language: 'typescript'

tags:
- dual
- package

toolchain:
  typescript:
    # Should depend on no other projects.
    syncProjectReferences: false
