//! Native entry point for the read-only source-view implementation.

/// What: Import the app's GUI entry point and standard error envelope.
/// Why: Native startup returns diagnostics to the shell without silent exits.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import { run } from './native';
/// ```
mod native;

/// What: The table of language files this build embeds, generated by `build.rs` into Cargo's
///       `OUT_DIR`. `include!` is a macro that pastes that generated file here at compile time, and
///       `concat!(env!("OUT_DIR"), ...)` spells its path when the program is compiled.
/// Why: The application is one executable: its parser libraries, highlighting queries, manifest,
///      and license texts are compiled in, so it needs no files beside it.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import { EMBEDDED_RUNTIME } from './generated/embedded_runtime';
/// ```
mod embedded_runtime {
    include!(concat!(env!("OUT_DIR"), "/embedded_runtime.rs"));
}

/// The Wayland app id and the explicit window backend that carries it.
mod launcher;

/// Checks of the embedded table: every digest, every grammar unpacked and compiled.
#[cfg(test)]
#[path = "embedded_runtime_tests.rs"]
mod embedded_runtime_tests;

/// Parse help and usage before starting logging, filesystem reads, or a native display connection.
fn main() -> anyhow::Result<()> {
    // What: args_os retains native filename bytes; skip omits the executable name and collect owns the arguments.
    // Why: Non-UTF-8 project names must not be converted through lossy display strings.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const args = nativeArgv.slice(1);
    // ```
    let args: Vec<_> = std::env::args_os().skip(1).collect();
    // What: match extracts the parsed options or preserves the concrete clap error for its exit policy.
    // Why: Help/version exit successfully without creating a window; usage errors use status 2.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const options = parseOrPrintAndExit(args);
    // return run(options);
    // ```
    let options = match ide_app::cli::parse_args(&args) {
        Ok(options) => options,
        Err(error) => {
            if let Some(cli) = error.downcast_ref::<clap::Error>() {
                // Exit is clap's documented terminal operation; no application resources have been started.
                cli.exit();
            }
            return Err(error);
        }
    };
    return native::run(options);
}
