//! Native entry point for the read-only source-view implementation.

/// What:
///  Import the app's GUI entry point and standard error envelope.
/// Why:
///  Native startup returns diagnostics to the shell without silent exits.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import { run } from './native';
/// ```
mod native;

/// What:
///  The table of language files this build embeds,
///  generated by `build.rs` into Cargo's
///       `OUT_DIR`.
///  `include!` is a macro that pastes that generated file here at compile time,
///  and
///       `concat!(env!("OUT_DIR"), ...)` spells its path when the program is compiled.
/// Why:
///  The application is one executable:
///  its parser libraries,
///  highlighting queries,
///  manifest,
///      and license texts are compiled in,
///  so it needs no files beside it.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import { EMBEDDED_RUNTIME } from './generated/embedded_runtime';
/// ```
mod embedded_runtime {
    include!(concat!(env!("OUT_DIR"), "/embedded_runtime.rs"));
}

/// The Wayland app id and the explicit window backend that carries it.
mod launcher;

/// Checks of the embedded table:
///  every digest,
///  every grammar unpacked and compiled.
#[cfg(test)]
#[path = "embedded_runtime_tests.rs"]
mod embedded_runtime_tests;

/// What:
///  Print every license and notice text embedded in this executable to standard output.
///       `stdout().lock()` holds the stream for the whole listing;
///  `write_all` sends raw bytes.
/// Why:
///  `--licenses` must work without a project,
///  a home folder,
///  or a display.
///  Every text is
///      digest-checked first,
///  so a damaged executable reports the damage and prints no partial list.
///      A reader that stops early (`| head`) closes the pipe;
///  Rust reports that as a `BrokenPipe`
///      write error instead of ending the process,
///  and it is a normal end here.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// function printLicenses(): void { process.stdout.write(render(collect(EMBEDDED_RUNTIME))); }
/// ```
fn print_licenses() -> anyhow::Result<()> {
    let notices = ide_app::runtime::notices::collect(&embedded_runtime::EMBEDDED_RUNTIME)?;
    let mut out = std::io::stdout().lock();
    // What: `and_then(|()| ...)` flushes only after every text was written; `match` then sorts the
    //       one outcome into success, a closed pipe, or a real error.
    // Why: Output is buffered, so a write error can surface at the flush.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // try { write(notices, version, stdout); flush(stdout); } catch (error) { if (error.code !== 'EPIPE') throw error; }
    // ```
    let written = ide_app::runtime::notices::write(&notices, env!("CARGO_PKG_VERSION"), &mut out)
        .and_then(|()| return std::io::Write::flush(&mut out));
    return match written {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::BrokenPipe => Ok(()),
        Err(error) => Err(error.into()),
    };
}

/// Parse help and usage before starting logging,
///  filesystem reads,
///  or a native display connection.
fn main() -> anyhow::Result<()> {
    // What: args_os retains native filename bytes; skip omits the executable name and collect owns the arguments.
    // Why: Non-UTF-8 project names must not be converted through lossy display strings.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const args = nativeArgv.slice(1);
    // ```
    let args: Vec<_> = std::env::args_os().skip(1).collect();
    // What: match extracts the parsed options or preserves the concrete clap error for its exit policy.
    // Why: Help/version exit successfully without creating a window; usage errors use status 2.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const options = parseOrPrintAndExit(args);
    // return run(options);
    // ```
    let startup = match ide_app::cli::parse_args(&args) {
        Ok(startup) => startup,
        Err(error) => {
            if let Some(cli) = error.downcast_ref::<clap::Error>() {
                // Exit is clap's documented terminal operation; no application resources have been started.
                cli.exit();
            }
            return Err(error);
        }
    };
    // What: `match` on the two outcomes: open a window, or print the license texts and return.
    // Why: The license listing starts no logging, reads no project, and connects to no display.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // return startup.kind === 'open' ? run(startup.options) : printLicenses();
    // ```
    return match startup {
        ide_app::cli::Startup::Open(options) => native::run(options),
        ide_app::cli::Startup::Licenses => print_licenses(),
    };
}
