//! Source-view binding gate; filesystem and language integration follow separately.

/// What: Compile-generated Slint declarations live in an isolated module.
/// Why: The compiler emits implicit returns; the exception must not cover app code.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import * as Ui from './generated-ui';
/// ```
#[allow(clippy::implicit_return)]
mod ui {
    // This macro includes build output; no application source is generated by us.
    slint::include_modules!();
}

/// Native window and model row generated from the UI declaration.
use ui::{AppWindow, SourceGlyph};
/// Toolkit handles and models bridge owned Rust state to the window.
use slint::{ComponentHandle, ModelRc, SharedString, VecModel};
/// Source and display geometry use the same library interface tested headlessly.
use ide_app::{document::{Document, ReadingPosition}, view_model::{build_view, hit_test, StyleSpan}};
/// What: Rc shares one UI-thread owner; RefCell permits checked mutable borrowing.
/// Why: Callbacks need the same document without cross-thread Arc/Mutex overhead.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// const shared = { current: state };
/// ```
use std::{cell::RefCell, rc::Rc};

/// Shared UI-thread state; there is no project-writing operation.
struct State {
    /// Canonical source and current reading position.
    document: Document,
    /// Highlight ranges, populated by the syntax integration.
    styles: Vec<StyleSpan>,
    /// First materialized source line, including viewport overscan.
    first: usize,
    /// Bounded number of materialized source lines.
    count: usize,
}

/// Render a snapshot after releasing the state borrow before modifying Slint.
fn render(window: &AppWindow, state: &Rc<RefCell<State>>) {
    // What: borrow() lends shared access until this scope ends.
    // Why: Snapshot construction cannot race another UI mutation.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const current = state.current;
    // ```
    let current = state.borrow();
    let view = build_view(&current.document, current.first, current.count, &current.styles);
    let position = current.document.position();
    let source = current.document.text().to_string();
    let selected = current.document.selected_text();
    let revision = current.document.revision();
    let lines = current.document.text().len_lines();
    // What: Vec::new creates owned model rows, unlike a borrowed slice.
    // Why: Slint retains these rows after this function returns.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const rows: SourceGlyph[] = [];
    // ```
    let mut rows = Vec::new();
    for glyph in view.glyphs {
        rows.push(SourceGlyph {
            // SharedString owns toolkit text; it is not a borrow into the document.
            text: SharedString::from(glyph.text),
            row: glyph.row as i32,
            column: glyph.column as i32,
            cells: glyph.width as i32,
            selected: glyph.selected,
            style: glyph.style as i32,
        });
    }
    // Release the RefCell guard before property callbacks may re-enter Rust.
    drop(current);
    // What: Rc::new and ModelRc retain the model across the language boundary.
    // Why: The native view receives data, not a second copy of text-editing state.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // window.glyphs = new ArrayModel(rows);
    // ```
    window.set_glyphs(ModelRc::from(Rc::new(VecModel::from(rows))));
    window.set_source_text(SharedString::from(source));
    window.set_selected_text(SharedString::from(selected));
    window.set_total_lines(lines as i32);
    window.set_caret_row(view.caret_row as i32);
    window.set_caret_column(view.caret_column as i32);
    window.set_selection_anchor(position.anchor as i32);
    window.set_selection_head(position.head as i32);
    window.set_revision(revision as i32);
    window.set_status(SharedString::from(format!(
        "Read only · Revision {revision} · Selection {}:{} · Source-view gate",
        position.anchor, position.head
    )));
}

/// Bind pointer selection without letting the UI mutate source text.
fn bind_pointer(window: &AppWindow, state: &Rc<RefCell<State>>) {
    // What: clone shares Rc ownership, whereas cloning a String copies its bytes.
    // Why: The callback remains valid after this binding function returns.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // const callbackState = state;
    // ```
    let state = Rc::clone(state);
    let weak = window.as_weak();
    // What: move |...| transfers captured handles into a stored callback.
    // Why: Borrowed local variables would not outlive this function.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // window.onPointerHit((row, column, extend) => { ... });
    // ```
    window.on_pointer_hit(move |row, column, extend| {
        let mut current = state.borrow_mut();
        let view = build_view(&current.document, current.first, current.count, &current.styles);
        let head = hit_test(&current.document, &view, row.max(0) as usize, column);
        let mut position = current.document.position();
        if !extend {
            position.anchor = head;
        }
        position.head = head;
        current.document.select(position);
        drop(current);
        // What: upgrade returns Some only while the window still exists.
        // Why: Closing the app must not keep a hidden window alive through callbacks.
        //
        // In TS you'd write (pseudocode):
        // ```ts
        // const window = weak.deref(); if (window) render(window, state);
        // ```
        if let Some(window) = weak.upgrade() {
            render(&window, &state);
        }
    });
}

/// Bind viewport changes while retaining only visible rows and overscan.
fn bind_viewport(window: &AppWindow, state: &Rc<RefCell<State>>) {
    let state = Rc::clone(state);
    let weak = window.as_weak();
    window.on_viewport_changed(move |offset, height| {
        let first = (offset.max(0.0) / 24.0) as usize;
        let count = (height.max(0.0) / 24.0).ceil() as usize + 3;
        let mut current = state.borrow_mut();
        if current.first == first.saturating_sub(1) && current.count == count {
            return;
        }
        current.first = first.saturating_sub(1);
        current.count = count;
        let text = current.document.text();
        let line = first.min(text.len_lines().saturating_sub(1));
        let mut position = current.document.position();
        position.viewport = text.line_to_char(line);
        current.document.select(position);
        drop(current);
        if let Some(window) = weak.upgrade() {
            render(&window, &state);
        }
    });
}

/// Bind native keyboard caret movement and select-all.
fn bind_keys(window: &AppWindow, state: &Rc<RefCell<State>>) {
    let select_state = Rc::clone(state);
    let weak = window.as_weak();
    window.on_select_all_request(move || {
        let mut current = select_state.borrow_mut();
        let end = current.document.text().len_chars();
        current.document.select(ReadingPosition { anchor: 0, head: end, viewport: 0 });
        drop(current);
        if let Some(window) = weak.upgrade() {
            render(&window, &select_state);
        }
    });
    let state = Rc::clone(state);
    let weak = window.as_weak();
    window.on_key_input(move |key, control, shift, _alt| {
        let mut current = state.borrow_mut();
        let mut position = current.document.position();
        let text = current.document.text().slice(..);
        if key == slint::platform::Key::LeftArrow {
            position.head = helix_core::graphemes::prev_grapheme_boundary(text, position.head);
        } else if key == slint::platform::Key::RightArrow {
            position.head = helix_core::graphemes::next_grapheme_boundary(text, position.head);
        } else if key == slint::platform::Key::Home {
            if control { position.head = 0; }
            else { position.head = text.line_to_char(text.char_to_line(position.head)); }
        } else if key == slint::platform::Key::End {
            if control { position.head = text.len_chars(); }
            else {
                let row = text.char_to_line(position.head);
                let end = text.line_to_char((row + 1).min(text.len_lines()));
                position.head = end.saturating_sub(1).max(text.line_to_char(row));
            }
        } else {
            return;
        }
        if !shift { position.anchor = position.head; }
        current.document.select(position);
        drop(current);
        if let Some(window) = weak.upgrade() {
            render(&window, &state);
        }
    });
}

/// Run the source-view gate against a supplied file or its explicit fixture.
pub fn run() -> anyhow::Result<()> {
    tracing_subscriber::fmt().with_env_filter("ide=debug").init();
    let path = std::env::args().nth(1);
    let source;
    let label;
    // What: if let extracts a present command-line argument without unwrap.
    // Why: The fixture is explicit when no real source file was supplied.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // if (path !== undefined) { source = readFile(path); }
    // ```
    if let Some(path) = path {
        // What: ? returns an I/O failure to main, preserving its diagnostic.
        // Why: A failed open must not silently substitute the fixture.
        //
        // In TS you'd write (pseudocode):
        // ```ts
        // source = await readFile(path, 'utf8');
        // ```
        source = std::fs::read_to_string(&path)?;
        label = path;
    } else {
        source = "I am a big cat.\nSelect text and use the native Copy action.\n猫 and e\u{301} are grapheme test cases.".to_string();
        label = "Source-view gate fixture".to_string();
    }
    let window = AppWindow::new()?;
    let state = Rc::new(RefCell::new(State {
        document: Document::new(&source),
        styles: Vec::new(),
        first: 0,
        count: 32,
    }));
    window.set_file_label(SharedString::from(label));
    bind_pointer(&window, &state);
    bind_viewport(&window, &state);
    bind_keys(&window, &state);
    render(&window, &state);
    window.run()?;
    // What: Ok(()) reports success without a payload; Err would carry a failure.
    // Why: Clean window closure is not a process error.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // return;
    // ```
    return Ok(());
}
