//! Source-view binding gate; filesystem and language integration follow separately.

/// What: Compile-generated Slint declarations live in an isolated module.
/// Why: The compiler emits implicit returns; the exception must not cover app code.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// import * as Ui from './generated-ui';
/// ```
#[allow(clippy::implicit_return)]
mod ui {
    // This macro includes build output; no application source is generated by us.
    slint::include_modules!();
}

/// Native window and model row generated from the UI declaration.
use ui::AppWindow;
/// Toolkit handles and models bridge owned Rust state to the window.
use slint::{ComponentHandle, SharedString};
/// Source and display geometry use the same library interface tested headlessly.
use ide_app::{document::Document, source_style::SourceStyles};
/// Shared shaping replaces terminal-column assumptions in native hit testing.
use ide_app::shaped_text::{ShapedView, TextShaper};
/// Raster output retains the exact glyph positions used by selection.
use ide_app::text_raster::TextRaster;
/// Paint identity prevents caret movement from rebuilding source pixels.
use ide_app::source_frame::FrameStamp;
/// What: Rc shares one UI-thread owner; RefCell permits checked mutable borrowing.
/// Why: Callbacks need the same document without cross-thread Arc/Mutex overhead.
///
/// In TS you'd write (pseudocode):
/// ```ts
/// const shared = { current: state };
/// ```
use std::{cell::RefCell, path::PathBuf, rc::Rc};

/// Native rendering and input are split by their invalidation boundary.
mod render;
/// Source selection and keyboard callbacks.
mod input;
/// Fractional viewport movement and bounded tile materialization.
mod viewport;
/// Background source reads apply correspondence to the latest UI reading state.
mod reload;
/// Shared rendering entry point.
use render::render;
/// Bind caret and selection callbacks.
use input::{bind_keys, bind_pointer};
/// Bind viewport changes without line-snapping native scrolling.
use viewport::bind_viewport;

/// Shared UI-thread state; there is no project-writing operation.
struct State {
    /// Canonical source and current reading position.
    document: Document,
    /// Optional authoritative disk file; absent only for the explicit in-memory fixture.
    file_path: Option<PathBuf>,
    /// File-open identity rejects worker replies after future navigation.
    file_generation: u64,
    /// A failed refresh retains source and displays an actionable error only while needed.
    file_error: Option<String>,
    /// Highlight ranges, populated by the syntax integration.
    styles: SourceStyles,
    /// First materialized source line, including viewport overscan.
    first: usize,
    /// Bounded number of materialized source lines.
    count: usize,
    /// Logical width of the visible code area.
    width: f32,
    /// Horizontal tile origin; native Flickable supplies fractional movement.
    horizontal: f32,
    /// Widest measured line of the current document.
    document_width: f32,
    /// Reusable paragraph/font resources.
    shaper: TextShaper,
    /// Reusable outline raster resources.
    raster: TextRaster,
    /// Exact displayed geometry used by pointer input.
    shaped: Option<ShapedView>,
    /// Avoid cloning whole source for accessibility on each selection change.
    presented_revision: Option<u64>,
    /// Last materialized image inputs; reset when changing the displayed file.
    frame_stamp: Option<FrameStamp>,
}

/// Run the source-view gate against a supplied file or its explicit fixture.
pub fn run() -> anyhow::Result<()> {
    tracing_subscriber::fmt().with_env_filter("ide_app=debug,monochromatic_ide=debug").init();
    let file_path = std::env::args().nth(1).map(PathBuf::from);
    // What: if let extracts a present command-line argument without unwrap.
    // Why: The fixture is explicit when no real source file was supplied.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // if (path !== undefined) { source = readFile(path); }
    // ```
    let (source, label) = if let Some(path) = &file_path {
        // What: ? returns an I/O failure to main, preserving its diagnostic.
        // Why: A failed open must not silently substitute the fixture.
        //
        // In TS you'd write (pseudocode):
        // ```ts
        // source = await readFile(path, 'utf8');
        // ```
        (std::fs::read_to_string(path)?, path.display().to_string())
    } else {
        (
            "I am a big cat.\nSelect text and use the native Copy action.\n猫 and e\u{301} are grapheme test cases.".to_string(),
            "Source-view gate fixture".to_string(),
        )
    };
    let window = AppWindow::new()?;
    let state = Rc::new(RefCell::new(State {
        document: Document::new(&source),
        file_path,
        file_generation: 1,
        file_error: None,
        styles: SourceStyles::from([]),
        first: 0,
        count: 32,
        width: 1044.0,
        horizontal: 0.0,
        document_width: 0.0,
        shaper: TextShaper::new(),
        raster: TextRaster::new(),
        shaped: None,
        presented_revision: None,
        frame_stamp: None,
    }));
    window.set_file_label(SharedString::from(label));
    bind_pointer(&window, &state);
    bind_viewport(&window, &state);
    bind_keys(&window, &state);
    // Retain the timer until window shutdown; its Drop also closes and joins the worker.
    let _reload_timer = reload::bind(&window, &state)?;
    let theme_state = Rc::clone(&state);
    let theme_window = window.as_weak();
    window.on_theme_changed(move || {
        if let Some(window) = theme_window.upgrade() {
            render(&window, &theme_state);
        }
    });
    render(&window, &state);
    window.run()?;
    // What: Ok(()) reports success without a payload; Err would carry a failure.
    // Why: Clean window closure is not a process error.
    //
    // In TS you'd write (pseudocode):
    // ```ts
    // return;
    // ```
    return Ok(());
}
