//! Rasterize shared shaped rows; glyphs retain their common baseline and advances.

/// Font identity maps keep Swash's scaler caches stable between frames.
use std::collections::HashMap;
/// Propagate malformed font or oversized viewport diagnostics to the native shell.
use anyhow::{bail, Context, Result};
/// Positioned glyph runs come from the same layouts used for caret and hit testing.
use parley::PositionedLayoutItem;
/// Swash is already part of Slint's dependency graph and supports fallback/color glyphs.
use swash::{CacheKey, FontRef, scale::{image::Content, ScaleContext}};
/// Bounded glyph images prevent repeating outline rasterization on every viewport update.
use crate::glyph_cache::{GlyphCache, GlyphKey};
/// Source layout and geometry are independent of the native widget tree.
use crate::shaped_text::ShapedView;

/// Native palette values needed by code painting.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct CodeColors {
    /// Default source ink from the system palette.
    pub foreground: [u8; 4],
    /// Selected source ink from the system palette.
    pub selected: [u8; 4],
    /// Select the corresponding syntax-color variants.
    pub dark: bool,
}

/// A premultiplied RGBA source tile ready for Slint.
pub struct SourcePixels {
    /// Physical pixel width.
    pub width: u32,
    /// Physical pixel height.
    pub height: u32,
    /// Owned row-major RGBA bytes.
    pub bytes: Vec<u8>,
}

/// Reuse scaler allocations and font identities across viewport frames.
pub struct TextRaster {
    /// Font outline and bitmap scaler.
    scale: ScaleContext,
    /// Stable cache identity for each font blob/face.
    keys: HashMap<(u64, u32), CacheKey>,
    /// Color-independent alpha masks and embedded color glyph images.
    glyphs: GlyphCache,
}

impl Default for TextRaster {
    fn default() -> Self {
        return Self::new();
    }
}

/// Translate semantic paint roles into the selected system-theme palette.
fn ink(role: u32, colors: CodeColors) -> [u8; 4] {
    if role == 64 { return colors.selected; }
    if role == 1 || role == 8 || role == 10 {
        if colors.dark { return [199, 146, 234, 255]; }
        return [118, 54, 164, 255];
    }
    if role == 2 {
        if colors.dark { return [168, 204, 140, 255]; }
        return [50, 101, 32, 255];
    }
    if role == 3 {
        if colors.dark { return [160, 168, 176, 255]; }
        return [85, 92, 101, 255];
    }
    if role == 4 || role == 13 {
        if colors.dark { return [240, 188, 122, 255]; }
        return [139, 77, 4, 255];
    }
    if role == 5 || role == 12 {
        if colors.dark { return [130, 190, 235, 255]; }
        return [20, 86, 127, 255];
    }
    if role == 6 || role == 11 {
        if colors.dark { return [225, 212, 157, 255]; }
        return [113, 83, 16, 255];
    }
    return colors.foreground;
}

/// Composite straight RGBA input into a premultiplied destination pixel.
fn blend(bytes: &mut [u8], offset: usize, color: [u8; 4]) {
    let alpha = u32::from(color[3]);
    let inverse = 255 - alpha;
    for channel in 0..3 {
        let source = (u32::from(color[channel]) * alpha + 127) / 255;
        let destination = (u32::from(bytes[offset + channel]) * inverse + 127) / 255;
        bytes[offset + channel] = (source + destination).min(255) as u8;
    }
    bytes[offset + 3] = (alpha + (u32::from(bytes[offset + 3]) * inverse + 127) / 255).min(255) as u8;
}

impl TextRaster {
    /// Initialize caches without allocating a viewport image.
    pub fn new() -> Self {
        return Self { scale: ScaleContext::new(), keys: HashMap::new(), glyphs: GlyphCache::default() };
    }

    /// Paint only the bounded materialized viewport; horizontal offset stays fractional.
    pub fn paint(&mut self, view: &ShapedView, colors: CodeColors, horizontal: f32) -> Result<SourcePixels> {
        let length = u64::from(view.width) * u64::from(view.height) * 4;
        if length > 64 * 1024 * 1024 {
            bail!("Source viewport {}x{} exceeds the 64 MiB raster limit; reduce the window size or scale", view.width, view.height);
        }
        let mut bytes = vec![0; length as usize];
        let factor = view.viewport.scale;
        for row in &view.rows {
            let row_y = (row.row - view.viewport.first) as f32 * 24.0 * factor;
            for line in row.layout.lines() {
                for item in line.items() {
                    // Inline boxes are not generated by this source-layout path.
                    let PositionedLayoutItem::GlyphRun(glyph_run) = item else {
                        bail!("Unexpected inline box in source text layout");
                    };
                    let run = glyph_run.run();
                    let font = run.font();
                    let mut font_ref = FontRef::from_index(font.data.as_ref(), font.index as usize)
                        .context("Unable to read a shaped source font face")?;
                    let key = self.keys.entry((font.data.id(), font.index)).or_default();
                    font_ref.key = *key;
                    let mut scaler = self.scale.builder(font_ref)
                        .size(run.font_size()).hint(true)
                        .normalized_coords(run.normalized_coords().iter().copied()).build();
                    let foreground = ink(glyph_run.style().brush, colors);
                    for glyph in glyph_run.positioned_glyphs() {
                        let x = glyph.x - horizontal * factor;
                        let y = glyph.y + row_y + row.baseline_shift;
                        if x + glyph.advance < -32.0 || x > view.width as f32 + 32.0 { continue; }
                        let glyph_id = u16::try_from(glyph.id).context("Source glyph index exceeds OpenType range")?;
                        // What: to_bits retains exact float identity; to_vec owns variation coordinates.
                        // Why: Cached masks must distinguish scale, font face, and fractional placement.
                        //
                        // In TS you'd write (pseudocode):
                        // ```ts
                        // const key = { font, face, size, variations: [...coords], glyph, x, y };
                        // ```
                        let glyph_key = GlyphKey {
                            font: font.data.id(), face: font.index, size: run.font_size().to_bits(),
                            variations: run.normalized_coords().to_vec(), glyph: glyph_id,
                            x: x.fract().to_bits(), y: y.fract().to_bits(),
                        };
                        // Lend the scaler only on cache misses; ? preserves cache-limit diagnostics.
                        // Empty glyphs such as spaces legitimately have no ink image.
                        let Some(image) = self.glyphs.image(glyph_key, &mut scaler)? else { continue; };
                        let left = x.floor() as i32 + image.placement.left;
                        let top = y.floor() as i32 - image.placement.top;
                        for iy in 0..image.placement.height {
                            let py = top + iy as i32;
                            if py < 0 || py >= view.height as i32 { continue; }
                            for ix in 0..image.placement.width {
                                let px = left + ix as i32;
                                if px < 0 || px >= view.width as i32 { continue; }
                                let source = (iy * image.placement.width + ix) as usize;
                                // What: if is an expression whose branch value initializes color.
                                // Why: Every valid image format supplies a complete pixel; others fail.
                                //
                                // In TS you'd write (pseudocode):
                                // ```ts
                                // const color = isMask ? coloredAlphaMask : embeddedRgba;
                                // ```
                                let color = if image.content == Content::Mask {
                                    [foreground[0], foreground[1], foreground[2],
                                        ((u32::from(image.data[source]) * u32::from(foreground[3]) + 127) / 255) as u8]
                                } else if image.content == Content::Color {
                                    let offset = source * 4;
                                    [image.data[offset], image.data[offset + 1], image.data[offset + 2], image.data[offset + 3]]
                                } else {
                                    bail!("Unexpected subpixel mask when rasterizing source with alpha format");
                                };
                                let destination = (py as usize * view.width as usize + px as usize) * 4;
                                blend(&mut bytes, destination, color);
                            }
                        }
                    }
                }
            }
        }
        return Ok(SourcePixels { width: view.width, height: view.height, bytes });
    }
}
