[tasks.run]
description = "Run android-exempt-unused interactive CLI"
run = "node src/index.ts"

[tasks.build]
extends = "build"

[tasks.'build:js']
extends = "build:js"

[tasks.'build:js:node']
extends = "build:js:node"

[tasks.'watch:build']
extends = "watch:build"

[tasks.'watch:build:js']
extends = "watch:build:js"

[tasks.'watch:build:js:node']
extends = "watch:build:js:node"

[tasks.lint]
extends = "lint"

[tasks.'lint:types']
extends = "lint:types"

[tasks.'lint:oxlint']
extends = "lint:oxlint"

[tasks."format:oxlint"]
extends = "format:oxlint"

[tasks.'test:unit']
extends = "test:unit"
