[tasks.build]
description = "Bundle client JS then generate self-contained HTML"
run = ["mise run build:js:client", "node src/build.ts"]

[tasks."build:js:client"]
extends = "build:js:client"

[tasks.lint]
extends = "lint"

[tasks.'lint:types']
extends = "lint:types"

[tasks."lint:oxlint"]
extends = "lint:oxlint"

[tasks."format:oxlint"]
extends = "format:oxlint"
