import {
  expandAbbreviations,
  type LongOptionAlias,
} from '../abbrev.ts';

//region Clean option aliases

/**
 * Non-empty long-option alias list returned by abbreviation expansion.
 */
type LongOptionAliases = readonly [
  LongOptionAlias,
  ...LongOptionAlias[],
];

/**
 * Aliases that git accepts for `--dry-run` via long-option prefix matching,
 * generated by {@link expandAbbreviations}.
 */
export const DRY_RUN_ALIASES: LongOptionAliases = expandAbbreviations({
  longOption: '--dry-run',
},);

/**
 * Aliases that git accepts for `--no-dry-run`, generated by
 * {@link expandAbbreviations}.
 */
export const NO_DRY_RUN_ALIASES: LongOptionAliases = expandAbbreviations({
  longOption: '--no-dry-run',
  minStemLength: 4,
},);

/**
 * Aliases that git accepts for `--interactive`, generated by
 * {@link expandAbbreviations}.
 */
export const INTERACTIVE_ALIASES: LongOptionAliases = expandAbbreviations({
  longOption: '--interactive',
},);

/**
 * Aliases that git accepts for `--no-interactive`, generated by
 * {@link expandAbbreviations}.
 */
export const NO_INTERACTIVE_ALIASES: LongOptionAliases = expandAbbreviations({
  longOption: '--no-interactive',
  minStemLength: 4,
},);

/**
 * Aliases that git accepts for `--exclude`, generated by
 * {@link expandAbbreviations}.
 */
export const EXCLUDE_ALIASES: LongOptionAliases = expandAbbreviations({
  longOption: '--exclude',
},);

/**
 * Exact aliases that activate clean dry-run mode.
 */
export const DRY_RUN_ALIAS_SET: ReadonlySet<string> = new Set(DRY_RUN_ALIASES,);

/**
 * Exact aliases that deactivate clean dry-run mode.
 */
export const NO_DRY_RUN_ALIAS_SET: ReadonlySet<string> = new Set(
  NO_DRY_RUN_ALIASES,
);

/**
 * Exact aliases that activate clean interactive mode.
 */
export const INTERACTIVE_ALIAS_SET: ReadonlySet<string> = new Set(
  INTERACTIVE_ALIASES,
);

/**
 * Exact aliases that deactivate clean interactive mode.
 */
export const NO_INTERACTIVE_ALIAS_SET: ReadonlySet<string> = new Set(
  NO_INTERACTIVE_ALIASES,
);

/**
 * Exact aliases that consume an exclude pattern value.
 */
export const EXCLUDE_ALIAS_SET: ReadonlySet<string> = new Set(EXCLUDE_ALIASES,);

//endregion Clean option aliases
