/**
 * Sprite pack accessor.
 *
 * The build inlines `assets/sprites/manifest.json` as a JSON island
 * inside the HTML. This module reads that island once at boot and
 * exposes lookup helpers.
 */

/**
 * Pose-keyed sprite URLs (data URIs in the placeholder pack).
 */
type CharacterPoses = Record<string, string>;

/**
 * Per-character entry in the manifest.
 */
type ManifestCharacter = {
  /**
   * Display name shown in the dialogue box.
   */
  displayName: string;

  /**
   * Theme color used for accents.
   */
  color: string;

  /**
   * Pose-keyed image URLs.
   */
  poses: CharacterPoses;
};

/**
 * Top-level manifest shape.
 */
type Manifest = {
  /**
   * Pack name.
   */
  name: string;

  /**
   * License string, surfaced in About text.
   */
  license: string;

  /**
   * Attribution / credits.
   */
  attribution: string;

  /**
   * Characters keyed by id.
   */
  characters: Record<string, ManifestCharacter>;

  /**
   * Background images keyed by id.
   */
  backgrounds: Record<string, string>;
};

/**
 * Singleton-slot container holding the parsed manifest after first load.
 */
const manifestCache: { value: Manifest | undefined; } = { value: undefined, };

/**
 * Reads the JSON island from the document and caches it.
 *
 * @returns the cached parsed manifest
 *
 * @throws when the island element is missing or invalid JSON
 *
 * @example
 * ```ts
 * const pack = loadSpritePack();
 * console.error('pack name:', pack.name);
 * ```
 */
export function loadSpritePack(): Manifest {
  if (manifestCache.value
    !== undefined)
    return manifestCache.value;
  /**
   * JSON island element embedded by the build, source of the manifest text.
   */
  const island = document.querySelector<HTMLScriptElement>('#sprite-pack',);
  if (island === null)
    throw new Error('[sprite-pack] #sprite-pack island not found',);
  /**
   * Raw JSON text content of the island, defaulting to empty when missing.
   */
  const text = island.textContent
    ?? '';
  /*
   * The JSON island is generated by our own build, not user-supplied,
   * so the shape contract holds at this trust boundary.
   */
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  manifestCache.value = JSON.parse(text,) as Manifest;
  return manifestCache.value;
}

/**
 * Returns the URL for a character pose.
 *
 * Falls back to the `neutral` pose when the requested pose is missing.
 * Falls back to the first character defined when `id` is unknown.
 *
 * @param characterId - character key
 *
 * @param pose - pose key
 *
 * @returns image URL
 *
 * @example
 * ```ts
 * const src = getCharacterPose({ characterId: 'ruka', pose: 'happy' });
 * imgEl.src = src;
 * ```
 */
export function getCharacterPose(
  {
    characterId,
    pose,
  }: Readonly<{
    characterId: string;
    pose: string;
  }>,
): string {
  /**
   * Cached manifest used to resolve the character and pose.
   */
  const m = loadSpritePack();
  /**
   * Character entry chosen by id, falling back to the first defined character.
   */
  const character = m.characters[characterId]
    ?? Object
    .values(m.characters,)[0];
  if (character === undefined)
    throw new Error('[sprite-pack] no characters defined in manifest',);
  return character.poses[pose]
    ?? character
    .poses
    .neutral
    ?? Object
    .values(character.poses,)[0]
    ?? '';
}

/**
 * Returns the display name of a character.
 *
 * @param characterId - character key
 *
 * @returns the manifest-declared display name, or the id when missing
 *
 * @example
 * ```ts
 * speakerName.textContent = getCharacterName('ruka');
 * ```
 */
export function getCharacterName(characterId: string,): string {
  /**
   * Cached manifest used to look up the character entry.
   */
  const m = loadSpritePack();
  return m.characters[characterId]
    ?.displayName
    ?? characterId;
}

/**
 * Returns a background image URL by id.
 *
 * @param id - background key
 *
 * @returns the URL declared in the manifest, or an empty string when missing
 *
 * @example
 * ```ts
 * el({ tag: 'div', attrs: { style: `background-image: url("${getBackground('classroom')}")` } });
 * ```
 */
export function getBackground(id: string,): string {
  /**
   * Cached manifest used to look up the background entry.
   */
  const m = loadSpritePack();
  return m.backgrounds[id]
    ?? '';
}
