packages:
- packages/*/*
childConcurrency: 16
dedupeDirectDeps: true
disallowWorkspaceCycles: true
hoist: false
hoistWorkspacePackages: false
includeWorkspaceRoot: true
linkWorkspacePackages: true
autoInstallPeers: false
managePackageManagerVersions: false
nodeLinker: isolated
onlyBuiltDependencies:
- dprint
- esbuild
- sharp
preferWorkspacePackages: true
resolutionMode: highest
savePrefix: ''
saveWorkspaceProtocol: false
strictDepBuilds: true
strictPeerDependencies: true
supportedArchitectures:
  os: [win32, darwin, linux, current]
  cpu: [x64, arm64, current]
  libc: [glibc, musl, current]
verifyDepsBeforeRun: install
catalog:
  # Faster, more customizable formatter than prettier.
  dprint: '*'

  # MAYBE: Deprecate this package. Switch to Vite.
  esbuild: '*'

  # Git commit hooks
  husky: '*'

  # Faster linter than eslint.
  oxlint: '*'

  # Comprehensive linter for CSS.
  stylelint: '*'
  stylelint-config-standard: '*'

  typescript: '*'

  # MAYBE: Investigate if Vue is needed.
  vue-tsc: '*'

  # For serializing data to fs.
  '@ungap/structured-clone': '*'

  # Find files in parent directories
  find-up: '*'

  # Glob implementation that works.
  glob: '*'

  # Faster, more extensive resolver than lightningcss's built-in resolver.
  oxc-resolver: '*'

  # TOML parser.
  smol-toml: '*'

  # TODO: Deprecate this package. Switch to gunshi
  zod-opts: '*'

  # For building command line apps
  '@kazupon/gunshi': 'jsr:*'

  # types for Bun because we're using Bun.
  '@types/bun': '*'

  # For postcss processing in Astro files
  postcss-html: '*'

  # For MDX usage in Astro
  # TODO: Check if this is needed.
  '@types/mdx': '*'

  # Feature-complete bundler
  vite: '*'

  # Enforce everything to be in one file when using Vite
  vite-plugin-singlefile: '*'

  # PostCSS syntax lowering
  '@csstools/postcss-color-function': '*'
  '@csstools/postcss-color-mix-function': '*'
  '@csstools/postcss-contrast-color-function': '*'
  '@csstools/postcss-extract': '*'
  '@csstools/postcss-gradients-interpolation-method': '*'
  '@csstools/postcss-light-dark-function': '*'
  '@csstools/postcss-oklab-function': '*'
  '@csstools/postcss-relative-color-syntax': '*'
  '@csstools/custom-units': '*'
  'postcss-calc': '*'
  'postcss-color-functional-notation': '*'
  'postcss-color-hex-alpha': '*'
  'postcss-convert-values': '*'
  'postcss-custom-properties': '*'
  'postcss-custom-media': '*'
  'postcss-custom-selectors': '*'
  'postcss-discard-comments': '*'
  'postcss-discard-duplicates': '*'
  'postcss-discard-empty': '*'
  'postcss-discard-overridden': '*'
  'postcss-discard-unused': '*'
  'postcss-merge-idents': '*'
  'postcss-merge-longhand': '*'
  'postcss-merge-rules': '*'
  'postcss-minify-font-values': '*'
  'postcss-minify-gradients': '*'
  'postcss-minify-params': '*'
  'postcss-minify-selectors': '*'
  'postcss-mixins': '*'
  'postcss-nesting': '*'
  'postcss-normalize-charset': '*'
  'postcss-normalize-display-values': '*'
  'postcss-normalize-positions': '*'
  'postcss-normalize-repeat-style': '*'
  'postcss-normalize-string': '*'
  'postcss-normalize-timing-functions': '*'
  'postcss-normalize-unicode': '*'
  'postcss-normalize-url': '*'
  'postcss-normalize-whitespace': '*'
  'postcss-ordered-values': '*'

  # Figma plugin types
  '@figma/plugin-typings': '*'

  # Concurrency lib
  'lfi': '*'

  # Fast CSS lib
  lightningcss: '*'

  # Feature-complete CSS lib
  postcss: '*'

  # Logger
  '@logtape/logtape': '@jsr/*'
  '@logtape/file': '@jsr/*'

  # TypeScript extended type helpers
  'type-fest': '*'

  # Feature-complete child process
  'execa': '*'

  # Small process spawner
  'nano-spawn': '*'

  # Astro
  astro: '*'
  '@astrojs/mdx': '*'
  '@astrojs/rss': '*'

  # Syntax highlighter
  '@shikijs/transformers': '*'

  # local HTTPS server
  '@vitejs/plugin-basic-ssl': '*'

  # Unified
  unified: '*'
  to-vfile: '*'
  remark-github-blockquote-alert: '*'
  remark-sectionize: '*'
  rehype-stringify: '*'
  rehype-slug-custom-id: '*'
  rehype-preset-minify: '*'
  rehype-parse: '*'
  rehype-autolink-headings: '*'
