[tasks.build]
extends = "build"

[tasks."build:js"]
extends = "build:js"

[tasks."build:js:client"]
extends = "build:js:client"

[tasks."watch:build"]
extends = "watch:build"

[tasks."watch:build:js"]
extends = "watch:build:js"

[tasks."watch:build:js:client"]
extends = "watch:build:js:client"

[tasks.dev]
description = "Start RSS reader in watch mode"
run = "mise watch -w src -r -- node src/index.ts"

[tasks.lint]
extends = "lint"

[tasks."lint:oxlint"]
extends = "lint:oxlint"

[tasks."format:oxlint"]
extends = "format:oxlint"

[tasks."lint:types"]
extends = "lint:types"
