title = "Subtle"
siteTitle = "Subtle"
description = "Personal Blog SSG and Theme built with Vue 🤔"
site = 'https://monochromatic.dev'
license = 'CC-BY-SA-4.0'

# Defaults to en.
lang = 'en'

earliest = 2024-03-06

[author]
name = "Aquaticat"
url = 'https://aquati.cat'

[theming]
color = '#966783'

[socials]
'RSS Feed' = 'https://aquati.cat/rss'
'Email' = 'mailto:an@aquati.cat?subject=Email author of Monochromatic/Subtle'
'GitHub' = 'https://github.com/Aquaticat'
'Telegram' = 'https://t.me/Aquaticat'

[links]
'Catoverflow' = 'https://c-j.dev'
'dummy1' = 'https://example.com'
'big dummy2' = 'https://example.com'
'big big dummy1' = 'https://example.com'
'big big dummy2' = 'https://example.com'
'dummy3' = 'https://example.com'
'dummy4' = 'https://example.com'
'dummy5' = 'https://example.com'
'dummy6' = 'https://example.com'
