# https://bun.sh/docs/runtime/bunfig

logLevel = "debug"

[test]

coverage = true

coverageSkipTestFiles = true

[install]

# Bun workspace implementation cause lockfile to cause bun i to fail.
# See https://github.com/oven-sh/bun/issues/5688#issuecomment-1740931536
save = false

# Generate a yarn v1 lockfile in text format as well.
lockfile.print = "yarn"

[debug]

editor = "codium"
