/**
 * Pure CLI helpers for spawn-pi.
 *
 * @module
 */

import type {
  PidMapping,
  SpawnState,
} from './paths.ts';
import { splitWhitespace, } from '@monochromatic-dev/agent-harness-shared-text-scan/ts';

//region Constants

/**
 * Number of spawn-id characters shown in terminal title.
 */
const SPAWN_ID_TITLE_LENGTH = 8;

/**
 * Terminal title used when spawn-pi cannot link child results to a parent session.
 */
const UNLINKED_SPAWN_TITLE: string = 'spawn-pi unlinked';

/**
 * Warning printed when spawn-pi launches without result forwarding.
 */
const SESSION_NOT_FOUND_WARNING: string = [
  'Warning: Could not find calling Pi session.',
  'Launching child Pi without result forwarding.',
  'Load or reload the spawn-pi extension in the parent Pi session to enable forwarding.',
].join(' ',);

//endregion Constants

//region Types

/**
 * Parsed arguments used by spawn-pi launcher.
 */
type SpawnPiArgs = {
  /**
   * Additional Pi CLI arguments encoded like spawn-claude's extra arguments.
   */
  readonly extraArguments?: string;
  /**
   * Initial prompt sent to child Pi process.
   */
  readonly prompt: string;
};

/**
 * Built terminal-exec invocation.
 */
type TerminalInvocation = {
  /**
   * Executable name used to launch visible terminal.
   */
  readonly command: 'terminal-exec';
  /**
   * Arguments passed to terminal-exec.
   */
  readonly args: readonly string[];
};

//endregion Types

//region State construction

/**
 * Builds initial spawn state from parent identity and CLI arguments.
 *
 * @param spawnId - UUID generated by CLI.
 *
 * @param identity - resolved parent {@link PidMapping}.
 *
 * @param cwd - working directory selected for child process.
 *
 * @returns {@link SpawnState} ready for disk persistence.
 *
 * @example
 * ```typescript
 * initialSpawnState({ spawnId: 'abc', identity, cwd: '/repo' });
 * ```
 */
function initialSpawnState(
  {
    spawnId,
    identity,
    cwd,
  }: {
    readonly spawnId: string;
    readonly identity: PidMapping;
    readonly cwd: string;
  },
): SpawnState {
  return {
    spawnId,
    sessionId: '',
    sessionFile: '',
    parentSessionId: identity.sessionId,
    parentSessionFile: identity.sessionFile,
    cwd,
    status: 'running',
    lastMessage: '',
  };
}

//endregion State construction

//region Argument construction

/**
 * Builds optional child Pi extension arguments from parent mapping.
 *
 * @param identity - resolved parent {@link PidMapping}, when available.
 *
 * @returns `--extension` arguments when parent exposed extension path.
 *
 * @example
 * ```typescript
 * extensionArguments({ identity });
 * extensionArguments({});
 * ```
 */
function extensionArguments(
  {
    identity,
  }: {
    readonly identity?: PidMapping;
  },
): readonly string[] {
  if (identity === undefined)
    return [];

  /**
   * Extension path inherited from parent session mapping.
   */
  const { extensionPath, } = identity;

  return extensionPath.length > 0
    ? [
      '--extension',
      extensionPath,
    ]
    : [];
}

/**
 * Builds Pi command arguments passed after terminal-exec delimiter.
 *
 * @param args - parsed {@link SpawnPiArgs}.
 *
 * @param identity - resolved parent {@link PidMapping}, when available.
 *
 * @returns argv for child `pi` invocation.
 *
 * @example
 * ```typescript
 * piCommandArguments({ args: { prompt: 'work' }, identity });
 * piCommandArguments({ args: { prompt: 'work' } });
 * ```
 */
function piCommandArguments(
  {
    args,
    identity,
  }: {
    readonly args: SpawnPiArgs;
    readonly identity?: PidMapping;
  },
): readonly string[] {
  /**
   * Extra Pi CLI arguments split using spawn-claude-compatible whitespace semantics.
   */
  const extraArgs = splitWhitespace(args.extraArguments ?? '',);
  /**
   * Extension arguments included only when a parent mapping exists.
   */
  const childExtensionArguments = identity === undefined
    ? []
    : extensionArguments({ identity, },);

  return [
    'pi',
    ...childExtensionArguments,
    ...extraArgs,
    args.prompt,
  ];
}

/**
 * Builds terminal-exec invocation for visible child Pi session.
 *
 * @param spawnId - UUID generated by CLI when result forwarding is active.
 *
 * @param args - parsed {@link SpawnPiArgs}.
 *
 * @param identity - resolved parent {@link PidMapping}, when available.
 *
 * @returns {@link TerminalInvocation} command and arguments.
 *
 * @example
 * ```typescript
 * terminalInvocation({ spawnId: 'abc', args: { prompt: 'work' }, identity });
 * terminalInvocation({ args: { prompt: 'work' } });
 * ```
 */
function terminalInvocation(
  {
    spawnId,
    args,
    identity,
  }: {
    readonly spawnId?: string;
    readonly args: SpawnPiArgs;
    readonly identity?: PidMapping;
  },
): TerminalInvocation {
  /**
   * Terminal title that communicates linked or unlinked spawn mode.
   */
  const title = spawnId === undefined
    ? UNLINKED_SPAWN_TITLE
    : `spawn-pi ${spawnId.slice(
      0,
      SPAWN_ID_TITLE_LENGTH,
    )}`;
  /**
   * Child Pi command arguments, with identity omitted in fallback mode.
   */
  const commandArguments = identity === undefined
    ? piCommandArguments({ args, },)
    : piCommandArguments({
      args,
      identity,
    },);

  return {
    command: 'terminal-exec',
    args: [
      `--title=${title}`,
      '--',
      ...commandArguments,
    ],
  };
}

//endregion Argument construction

export {
  extensionArguments,
  initialSpawnState,
  piCommandArguments,
  SESSION_NOT_FOUND_WARNING,
  SPAWN_ID_TITLE_LENGTH,
  terminalInvocation,
  UNLINKED_SPAWN_TITLE,
};

export type {
  SpawnPiArgs,
  TerminalInvocation,
};
