/**
 * File path conventions for spawn-pi coordination.
 *
 * @module
 */

import { join, } from 'node:path';

//region Types

/**
 * Environment lookup object accepted by path helpers.
 */
type Environment = Readonly<NodeJS.ProcessEnv>;

/**
 * JSON written under `.by-pid/` so the CLI can resolve its parent Pi session.
 */
type PidMapping = {
  /**
   * Pi session identifier from SessionManager.
   */
  readonly sessionId: string;
  /**
   * Persisted session file path, or empty string for in-memory sessions.
   */
  readonly sessionFile: string;
  /**
   * Working directory for the Pi session.
   */
  readonly cwd: string;
  /**
   * Extension entry path inherited by spawned children via `--extension`.
   */
  readonly extensionPath: string;
};

/**
 * JSON written under `spawns/` for one visible child Pi session.
 */
type SpawnState = {
  /**
   * UUID generated by spawn-pi CLI.
   */
  readonly spawnId: string;
  /**
   * Child Pi session identifier after child extension claims the spawn.
   */
  readonly sessionId: string;
  /**
   * Child Pi session file path after child extension claims the spawn.
   */
  readonly sessionFile: string;
  /**
   * Parent Pi session identifier resolved by spawn-pi CLI.
   */
  readonly parentSessionId: string;
  /**
   * Parent Pi session file path resolved by spawn-pi CLI.
   */
  readonly parentSessionFile: string;
  /**
   * Child process working directory.
   */
  readonly cwd: string;
  /**
   * Current lifecycle state for first result forwarding.
   */
  readonly status: 'running' | 'stopped';
  /**
   * Last assistant text from child Pi agent loop.
   */
  readonly lastMessage: string;
};

//endregion Types

//region Path helpers

/**
 * Resolves Pi agent configuration directory from environment.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns Pi agent directory path.
 *
 * @example
 * ```typescript
 * piAgentDir({ HOME: '/home/me' }); // '/home/me/.pi/agent'
 * ```
 */
function piAgentDir(env: Environment = process.env,): string {
  return env.PI_CODING_AGENT_DIR
    ?? join(
      env.HOME
        ?? '/tmp',
      '.pi',
      'agent',
    );
}

/**
 * Resolves root directory for spawn-pi coordination files.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns spawn-pi result directory path.
 *
 * @example
 * ```typescript
 * spawnResultsDir({ PI_CODING_AGENT_DIR: '/tmp/pi' });
 * // '/tmp/pi/spawn-results'
 * ```
 */
function spawnResultsDir(env: Environment = process.env,): string {
  return join(
    piAgentDir(env,),
    'spawn-results',
  );
}

/**
 * Resolves PID mapping directory for current environment.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns `.by-pid` directory path.
 *
 * @example
 * ```typescript
 * byPidDir({ PI_CODING_AGENT_DIR: '/tmp/pi' });
 * ```
 */
function byPidDir(env: Environment = process.env,): string {
  return join(
    spawnResultsDir(env,),
    '.by-pid',
  );
}

/**
 * Resolves spawn state directory for current environment.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns `spawns` directory path.
 *
 * @example
 * ```typescript
 * spawnsDir({ PI_CODING_AGENT_DIR: '/tmp/pi' });
 * ```
 */
function spawnsDir(env: Environment = process.env,): string {
  return join(
    spawnResultsDir(env,),
    'spawns',
  );
}

/**
 * Resolves JSON state path for a spawn identifier.
 *
 * @param spawnId - spawn identifier generated by CLI.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns absolute path to spawn JSON file.
 *
 * @example
 * ```typescript
 * spawnStatePath({ spawnId: 'abc' });
 * ```
 */
function spawnStatePath(
  {
    spawnId,
    env = process.env,
  }: {
    readonly spawnId: string;
    readonly env?: Environment;
  },
): string {
  return join(
    spawnsDir(env,),
    `${spawnId}.json`,
  );
}

/**
 * Resolves reported marker path for a spawn identifier.
 *
 * @param spawnId - spawn identifier generated by CLI.
 *
 * @param env - {@link Environment} values to inspect.
 *
 * @returns absolute path to consumed spawn marker file.
 *
 * @example
 * ```typescript
 * reportedStatePath({ spawnId: 'abc' });
 * ```
 */
function reportedStatePath(
  {
    spawnId,
    env = process.env,
  }: {
    readonly spawnId: string;
    readonly env?: Environment;
  },
): string {
  return join(
    spawnsDir(env,),
    `${spawnId}.reported`,
  );
}

//endregion Path helpers

export {
  byPidDir,
  piAgentDir,
  reportedStatePath,
  spawnResultsDir,
  spawnsDir,
  spawnStatePath,
};

export type {
  Environment,
  PidMapping,
  SpawnState,
};
