#!/bin/sh
# First-boot init for the stress-test Garage container.
#
# Boots `garage server` in the background, waits for it to be ready,
# creates a `fragments` bucket, generates an access key, writes the
# credentials to `/secrets/garage-credentials.env` (a named volume so
# the host harness can read them), then `wait`s on the server.
#
# On subsequent boots the bucket and key already exist; we skip
# re-creating them and just print the existing credentials.

set -e

CRED_FILE=/secrets/garage-credentials.env
BUCKET=fragments
KEY_NAME=stress-key

mkdir -p /secrets

# Start the server in the background.
garage -c /etc/garage.toml server &
GARAGE_PID=$!

# Wait for the admin API to come up.
for i in 1 2 3 4 5 6 7 8 9 10; do
  if garage -c /etc/garage.toml status >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if [ -f "$CRED_FILE" ]; then
  echo "garage already initialised; reusing credentials in $CRED_FILE"
  cat "$CRED_FILE"
  wait "$GARAGE_PID"
  exit 0
fi

# Single-node layout assignment.
NODE_ID=$(garage -c /etc/garage.toml status | awk 'NR > 2 && $1 != "" {print $1; exit}')
if [ -z "$NODE_ID" ]; then
  echo "ERROR: could not resolve garage node id" >&2
  exit 1
fi

garage -c /etc/garage.toml layout assign "$NODE_ID" -z dc1 -c 1G
garage -c /etc/garage.toml layout apply --version 1

# Bucket + key.
garage -c /etc/garage.toml bucket create "$BUCKET"
KEY_OUTPUT=$(garage -c /etc/garage.toml key create "$KEY_NAME")
ACCESS_KEY_ID=$(echo "$KEY_OUTPUT" | awk -F': ' '/Key ID:/ {print $2}' | tr -d ' ')
SECRET_KEY=$(echo "$KEY_OUTPUT" | awk -F': ' '/Secret key:/ {print $2}' | tr -d ' ')
garage -c /etc/garage.toml bucket allow --read --write --owner "$BUCKET" --key "$ACCESS_KEY_ID"

# Emit credentials in shell-import form.
{
  echo "# Auto-generated by stress/garage-init.sh"
  echo "GARAGE_ENDPOINT=http://localhost:3900"
  echo "GARAGE_BUCKET=$BUCKET"
  echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID"
  echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY"
  echo "AWS_REGION=garage"
} > "$CRED_FILE"

cat "$CRED_FILE"

wait "$GARAGE_PID"
