packages:
- packages/*/*
childConcurrency: 16
dedupeDirectDeps: true
disallowWorkspaceCycles: true
hoist: false
hoistWorkspacePackages: false
includeWorkspaceRoot: true
linkWorkspacePackages: true
autoInstallPeers: false
managePackageManagerVersions: false
nodeLinker: isolated
onlyBuiltDependencies:
- dprint
- esbuild
- sharp
preferWorkspacePackages: true
resolutionMode: highest
savePrefix: ''
saveWorkspaceProtocol: false
strictDepBuilds: true
strictPeerDependencies: true
supportedArchitectures:
  os: [win32, darwin, linux, current]
  cpu: [x64, arm64, current]
  libc: [glibc, musl, current]
verifyDepsBeforeRun: install
catalog:
  # Faster, more customizable formatter than prettier.
  dprint: '*'

  # MAYBE: Deprecate this package. Switch to Vite.
  esbuild: '*'

  # Git commit hooks
  husky: '*'

  # Faster linter than eslint.
  oxlint: '*'

  # Comprehensive linter for CSS.
  stylelint: '*'

  typescript: '*'

  # MAYBE: Investigate if Vue is needed.
  vue-tsc: '*'

  # For serializing data to fs.
  '@ungap/structured-clone': '*'

  # Find files in parent directories
  find-up: '*'

  # Glob implementation that works.
  glob: '*'

  # Faster, more extensive resolver than lightningcss's built-in resolver.
  oxc-resolver: '*'

  # TOML parser.
  smol-toml: '*'

  # TODO: Deprecate this package. Switch to gunshi
  zod-opts: '*'

  # For building command line apps
  '@kazupon/gunshi': 'jsr:*'

  # types for Bun because we're using Bun.
  '@types/bun': '*'


  # For postcss processing in Astro files
  postcss-html: '*'
