/**
 * Build script: generates the single self-contained glass corridor demo.
 *
 * Reads the pre-bundled client JS from rolldown output, then assembles
 * HTML/CSS/JS into one file.
 *
 * Requires `mise run build:js:client` to have run first so
 * `dist/client/main.js` exists.
 */
import {
  mkdir,
  readFile,
  writeFile,
} from 'node:fs/promises';
import { join, } from 'node:path';

import { renderPage, } from './page.ts';
import { renderStyles, } from './styles.ts';

export {};

/**
 * Absolute path to this package's root directory
 */
const PACKAGE_DIR: string = new URL(
  '..',
  import.meta.url,
)
  .pathname;

/**
 * Output directory for the generated site
 */
const DIST_DIR = join(
  PACKAGE_DIR,
  'dist',
  'final',
);

console.error('[web-demo-glass] building...',);

/**
 * CSS stylesheet, generated by {@link renderStyles}
 */
const css = renderStyles();

/**
 * Client-side demo script, pre-bundled by rolldown
 */
const js = await readFile(
  join(
    PACKAGE_DIR,
    'dist',
    'client',
    'main.js',
  ),
  'utf8',
);

/**
 * Complete self-contained HTML document, assembled by {@link renderPage}
 */
const html = renderPage({
  css,
  js,
},);

await mkdir(
  DIST_DIR,
  { recursive: true, },
);
await writeFile(
  join(
    DIST_DIR,
    'index.html',
  ),
  html,
  'utf8',
);

console.error(`[web-demo-glass] wrote ${
  join(
    DIST_DIR,
    'index.html',
  )
}`,);
