cloneConcurrency: 4

defaultSemverRangePrefix: ""

enableTelemetry: false

enableTimers: false

httpTimeout: 6000

logFilters:
  - text: ESM support for PnP uses the experimental loader API and is therefore experimental
    level: discard
  - text: Completed
    level: discard
  - pattern: "* must be built because it never has been before or the last one failed"
    level: discard

nmMode: hardlinks-local

winLinkType: symlinks

pnpEnableEsmLoader: true

pnpEnableInlining: false

preferReuse: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

enableMessageNames: false

# So that Yarn pnp patched TypeScript works, even though we ran Yarn install in dev container.
enableGlobalCache: false
