logLevel = 'warn'
telemetry = false

# We're not using Bun's test runner
# [test]
# coverage = true

[install]
auto = 'force'
scopes.jsr = 'https://npm.jsr.io'
print = 'yarn'

[run]
# Always use Bun's shell
shell = 'bun'

# Auto alias node to bun
# Abandon everything not working with Bun.
bun = true

silent = true
