[tasks.'build']
run = [{ tasks = ["build:*"] }]

[tasks.'build:site']
run = "pnpm exec astro build"

[tasks."build--watch:site"]
run = "pnpm exec astro build --watch"

[tasks."lint:types"]
hide = true
description = "TypeScript"
run = "pnpm exec tsgo --build"

[tasks."lint--allowFailure:types"]
hide = true
description = "TypeScript"
run = "try { pnpm exec tsgo --build } catch { |e| print -e $e.rendered }"

[tasks."dev:site"]
description = "Start development server"
run = "pnpm exec astro dev"

[tasks."_astro:sync"]
description = "Sync Astro"
run = "pnpm exec astro sync"

[tasks."_astro:check"]
description = "Check Astro"
run = "pnpm exec astro check"
