[task_config]
includes = [
  "../../../mise-shared/lint-types.toml",
  "../../../mise-shared/lint.toml",
  "../../../mise-shared/oxlint.toml",
  "../../../mise-shared/test-unit.toml",
  "../../../mise-shared/test.toml",
]
