[tasks.lint]
extends = "lint"

[tasks."lint:oxlint"]
extends = "lint:oxlint"

[tasks."format:oxlint"]
extends = "format:oxlint"

[tasks."lint:types"]
extends = "lint:types"

[tasks.test]
extends = "test"

[tasks."test:unit"]
extends = "test:unit"
