[tasks.build]
extends = "build"

[tasks.'build:js']
extends = "build:js"

[tasks.'build:js:browser']
extends = "build:js:browser"

[tasks.'build:js:node']
extends = "build:js:node"

[tasks.build--watch]
extends = "build--watch"

[tasks."build--watch:js"]
extends = "build--watch:js"

[tasks.'build--watch:js:browser']
extends = "build--watch:js:browser"

[tasks.'build--watch:js:node']
extends = "build--watch:js:node"

[tasks."lint:types"]
extends = "lint:types"
hide = true

[tasks."lint--watch:types"]
extends = "lint--watch:types"
hide = true

[tasks."lint:oxlint"]
extends = "lint:oxlint"
