[tasks.'build:js']
run = [{ tasks = ["build:js:*"] }]

[tasks.'build:js:browser']
run = "tsdown"

[tasks.'build:js:node']
run = "tsdown --config tsdown.node.config.ts"

[tasks."build--watch:js"]
run = [{ tasks = ["build--watch:js:*"] }]

[tasks.'build--watch:js:browser']
run = "tsdown --watch"

[tasks.'build--watch:js:node']
run = "tsdown --watch --config tsdown.node.config.ts"

[tasks."lint:types"]
hide = true
description = "TypeScript"
run = "tsgo --build"

[tasks."lint--allowFailure:types"]
hide = true
description = "TypeScript"
run = "try { tsgo --build } catch { |e| print -e $e.rendered }"

[tasks."lint--watch:types"]
hide = true
description = "Type check in watch mode"
run = "tsgo --watch"
