// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales =
  | 'en'
  | 'zh';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * A​q​u​a​t​i​c​a​t
   */
  siteName: string;
  /**
   * C​h​a​n​g​i​n​g​ ​t​h​e​ ​w​o​r​l​d​,​ ​o​n​e​ ​d​e​s​i​g​n​ ​a​t​ ​a​ ​t​i​m​e
   */
  siteDescription: string;
  /**
   * c​h​o​o​s​e​ ​a​ ​l​a​n​g​u​a​g​e
   */
  chooseALang: string;
  /**
   * S​e​a​r​c​h​ ​k​e​y​w​o​r​d​,​ ​t​o​p​i​c​,​ ​t​e​x​t
   */
  searchPlaceholder: string;
  /**
   * N​o​ ​r​e​s​u​l​t​s
   */
  noResults: string;
  /**
   * p​a​g​e
   */
  page: string;
  /**
   * P​o​s​t​ ​d​o​e​s​n​'​t​ ​e​x​i​s​t​ ​i​n​ ​s​p​e​c​i​f​i​e​d​ ​l​a​n​g​u​a​g​e
   */
  postNotInLang: string;
  /**
   * C​h​o​o​s​e​ ​a​ ​l​a​n​g​u​a​g​e​ ​f​o​r
   */
  redirectingToLangChooser: string;
};

export type TranslationFunctions = {
  /**
   * Aquaticat
   */
  siteName: () => LocalizedString;
  /**
   * Changing the world, one design at a time
   */
  siteDescription: () => LocalizedString;
  /**
   * choose a language
   */
  chooseALang: () => LocalizedString;
  /**
   * Search keyword, topic, text
   */
  searchPlaceholder: () => LocalizedString;
  /**
   * No results
   */
  noResults: () => LocalizedString;
  /**
   * page
   */
  page: () => LocalizedString;
  /**
   * Post doesn't exist in specified language
   */
  postNotInLang: () => LocalizedString;
  /**
   * Choose a language for
   */
  redirectingToLangChooser: () => LocalizedString;
};

export type Formatters = {};
