[task_config]
includes = [
  "../../../mise-shared/build-js.toml",
  "../../../mise-shared/build.toml",
  "../../../mise-shared/lint-types.toml",
  "../../../mise-shared/lint.toml",
  "../../../mise-shared/node.toml",
  "../../../mise-shared/oxlint.toml",
  "../../../mise-shared/test-unit.toml",
  "../../../mise-shared/watch-build.toml",
]
