[tasks.run]
description = "Run cli-fy"
usage = 'arg "[args]" var=#true help="Specifier, export name, and arguments"'
run = "bun src/index.ts ...($env.usage_args? | default '' | split row ' ' | where {|part| $part != '' })"

[tasks.'lint:types']
extends = "lint:types"

[tasks.'lint:oxlint']
extends = "lint:oxlint"
