$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  js_node:
    command: 'vite build --config vite.config.ts --mode production,node'
    options:
      outputStyle: buffer-only-failure

  js_nodeWatch:
    command: 'vite build --config vite.config.ts --mode production,node --watch'
    local: true

  js:
    deps:
    - js_default
    - js_node

  jsWatch:
    deps:
    - js_defaultWatch
    - js_nodeWatch
    local: true
