$schema: 'https://moonrepo.dev/schemas/tasks.json'

taskOptions:

tasks:
  #"b:iframeFrontend": "vite build --mode production --config vite.config.iframe.ts",
  js_default:
    command: 'vite build --mode production --config vite.config.iframe.ts'

  #"b:backend": "vite build --mode production --config vite.config.backend.ts",
  js_backend:
    command: 'vite build --mode production --config vite.config.backend.ts'

  js:
    deps:
    - js_default
    - js_backend
