/**
 * Sprite pack accessor.
 *
 * The build inlines `assets/sprites/manifest.json` as a JSON island
 * inside the HTML. This module reads that island once at boot and
 * exposes lookup helpers.
 */

/** Pose-keyed sprite URLs (data URIs in the placeholder pack). */
type CharacterPoses = Record<string, string>;

/** Per-character entry in the manifest. */
type ManifestCharacter = {
  /** Display name shown in the dialogue box. */
  displayName: string;

  /** Theme color used for accents. */
  color: string;

  /** Pose-keyed image URLs. */
  poses: CharacterPoses;
};

/** Top-level manifest shape. */
type Manifest = {
  /** Pack name. */
  name: string;

  /** License string, surfaced in About text. */
  license: string;

  /** Attribution / credits. */
  attribution: string;

  /** Characters keyed by id. */
  characters: Record<string, ManifestCharacter>;

  /** Background images keyed by id. */
  backgrounds: Record<string, string>;
};

/** Singleton parsed manifest. */
let manifest: Manifest | undefined;

/**
 * Reads the JSON island from the document and caches it.
 *
 * @throws when the island element is missing or invalid JSON
 */
export function loadSpritePack(): Manifest {
  if (manifest !== undefined)
    return manifest;
  const island = document.querySelector('#sprite-pack',);
  if (island === null)
    throw new Error('[sprite-pack] #sprite-pack island not found',);
  const text = island.textContent ?? '';
  /*
   * The JSON island is generated by our own build, not user-supplied,
   * so the shape contract holds at this trust boundary.
   */
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  manifest = JSON.parse(text,) as Manifest;
  return manifest;
}

/**
 * Returns the URL for a character pose.
 *
 * Falls back to the `neutral` pose when the requested pose is missing.
 * Falls back to the first character defined when `id` is unknown.
 *
 * @param characterId - character key
 *
 * @param pose - pose key
 *
 * @returns image URL
 */
export function getCharacterPose(
  characterId: string,
  pose: string,
): string {
  const m = loadSpritePack();
  const character = m.characters[characterId]
    ?? Object.values(m.characters,)[0];
  if (character === undefined)
    throw new Error('[sprite-pack] no characters defined in manifest',);
  return character.poses[pose]
    ?? character.poses['neutral']
    ?? Object.values(character.poses,)[0]
    ?? '';
}

/** Returns the display name of a character. */
export function getCharacterName(characterId: string,): string {
  const m = loadSpritePack();
  return m.characters[characterId]?.displayName ?? characterId;
}

/** Returns a background image URL by id. */
export function getBackground(id: string,): string {
  const m = loadSpritePack();
  return m.backgrounds[id] ?? '';
}
