[tasks.'build']
extends = "build"

[tasks.'build:site']
run = [{ tasks = ["build:site:css"] }, { tasks = ["build:site:astro"] }]

[tasks.'build:site:css']
run = "bun ../../build-tool/css/src/cli.ts src/styles/main.css dist/bundle.css"

[tasks.'build:site:astro']
run = "bun exec astro build"

[tasks."watch:build"]
extends = "watch:build"

[tasks."watch:build:site"]
run = [{ tasks = ["watch:build:site:*"] }]

[tasks."watch:build:site:css"]
run = "bun ../../build-tool/css/src/cli.ts src/styles/main.css dist/bundle.css --watch"

[tasks."watch:build:site:astro"]
run = "bun exec astro build --watch"

[tasks."lint:types"]
extends = "lint:types"
hide = true

[tasks."dev:site"]
description = "Start development server"
run = "bun exec astro dev"

[tasks."_astro:sync"]
description = "Sync Astro"
run = "bun exec astro sync"

[tasks."_astro:check"]
description = "Check Astro"
run = "bun exec astro check"

[tasks."lint:oxlint"]
extends = "lint:oxlint"
