import { readFile, } from 'node:fs/promises';
import { resolve, } from 'node:path';

import {
  describe,
  expect,
  it,
} from '@monochromatic-dev/module-test/ts';

//region Generated policy contract fixtures

/**
 * Repository root containing canonical and generated policy sources.
 */
const REPOSITORY_ROOT = resolve(
  import.meta.dirname,
  '../../../..',
);

/**
 * Contract retained at canonical lazy-provider ownership boundaries.
 */
const LAZY_PROVIDER_MUTATION_CONTRACT = '@mutates context through context.git.candidates lazy provider invocation';

/**
 * Canonical source and generated mirror expected to differ at ownership boundary.
 */
type PolicyMirrorContractFixture = Readonly<{
  /**
   * Canonical policy source that owns lazy provider invocation.
   */
  canonicalPath: string;

  /**
   * Generated mirror with locally provable inlined effects.
   */
  generatedPath: string;
}>;

/**
 * Policy mirror pairs generated by root file-enforcer configuration.
 */
const POLICY_MIRROR_CONTRACT_FIXTURES = [
  {
    canonicalPath: 'packages/git-policies/repository/src/index.ts',
    generatedPath: 'packages/git-policies/cli/src/optional/repository-policy.ts',
  },
  {
    canonicalPath: 'packages/git-policies/forbidden-strings/src/index.ts',
    generatedPath: 'packages/git-policies/cli/src/optional/forbidden-strings/index.ts',
  },
] as const satisfies readonly PolicyMirrorContractFixture[];

//endregion Generated policy contract fixtures

await describe({
  name: 'generated Git policy mutation contracts',
  children: POLICY_MIRROR_CONTRACT_FIXTURES.map(function createPolicyMirrorContractTest(fixture,) {
    return it({
      name: `retains canonical contract and omits generated contract for ${fixture.generatedPath}`,
      fn: async function verifiesGeneratedPolicyContractBoundary(): Promise<void> {
        const [canonicalSource, generatedSource,] = await Promise.all([
          readFile(resolve(REPOSITORY_ROOT, fixture.canonicalPath,), 'utf8',),
          readFile(resolve(REPOSITORY_ROOT, fixture.generatedPath,), 'utf8',),
        ],);

        expect(canonicalSource.includes(LAZY_PROVIDER_MUTATION_CONTRACT,),).toBe(true,);
        expect(generatedSource.includes(LAZY_PROVIDER_MUTATION_CONTRACT,),).toBe(false,);
      },
    },);
  },),
},);
