[tasks.build]
description = "Generate static dashboard from canary history and artifacts"
# FIXME: I mis-understood how Mise's "depends" work. I thought it would run once but apparently it runs every time. Need a proper "depends" that runs the depended tasks once until the depended tasks themselves' dependencies changed or output not proper.
# depends = ["inference-canary-run"]
run = ["bun src/build.ts"]

[tasks.inference-canary-run]
run =  ["mise run //packages/dev-script/inference-canary:run"]

[tasks.'dev:watch']
description = "Rebuild dashboard on source or canary-lint changes"
run = "mise watch -w src -w ../inference-canary/src/canary-lint --no-vcs-ignore --debounce 1sec -r -- build"

[tasks.'dev:serve']
description = "Serve the built dashboard locally"
run = "bun ./dist/final/index.html"

[tasks.dev]
description = "Watch and serve the dashboard"
run = [{tasks = ["dev:*"]}]

[tasks.'lint:types']
extends = "lint:types"

[tasks."lint:oxlint"]
extends = "lint:oxlint"
