#![no_main]

//! Drives scanner-owned runtime-cache envelope decoder with arbitrary bytes.

/// Imports fuzz macro that repeatedly calls target closure with generated bytes.
use libfuzzer_sys::fuzz_target;

/// One artifact/source pair supplied by libFuzzer.
#[derive(arbitrary::Arbitrary, Debug)]
struct Input<'a> {
    /// Arbitrary potentially hostile artifact bytes.
    artifact: &'a [u8],
    /// Arbitrary authoritative source bytes used for digest identity.
    source: &'a [u8],
}

// What:     `fuzz_target!(|input: Input| { ... })` declares libFuzzer entry.
// Why:      Every framing offset and length field must reject safely without panic.
//
// In TS you'd write (pseudocode):
// ```ts
// for (const input of generatedInputs) decodeArtifact(input.artifact, input.source);
// ```
fuzz_target!(|input: Input<'_>| {
    let _ = forbidden_strings::fuzz_api::decode_artifact_for_fuzzing(
        input.artifact,
        input.source,
    );
});
