#!/usr/bin/env pwsh
$ErrorActionPreference = 'Stop'
$PSNativeCommandErrorActionPreference = $true

Set-Item -Path "Env:ARG0" -Value "$PSCommandPath"
for ($i = 0; $i -lt $args.Count; $i++) {
  Set-Item -Path "Env:ARG$($i + 1)" -Value "$($args[$i])"
}

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

moon run validate

if ($LASTEXITCODE -ne 0) {
  exit $LASTEXITCODE
}


