name: build on host machine

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: yarn set version stable

      - uses: actions/checkout@main

      - name: remove conflicting yarn path
        run: echo "$(grep -v '^yarnPath:' .yarnrc.yml)" > .yarnrc.yml

      - uses: actions/setup-node@main
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - run: yarn
      - run: yarn -T -B monochromatic build
        working-directory: ./packages/theme/subtle
