name: test building themes on host machine

on:
  - push

jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: install non-npm dependency caddy
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy

      - name: install other non-npm dependencies
        run: |
          sudo apt-get install brotli graphviz imagemagick patch plantuml librsvg2-2 librsvg2-bin librsvg2-common unzip

      - uses: actions/checkout@main

      - name: remove conflicting yarn path
        run: echo "$(grep -v '^yarnPath:' .yarnrc.yml)" > .yarnrc.yml

      - name: remove unnecessary packageManager field in 'package.json'
        run: echo "$(grep -v '"packageManager":' package.json)" > package.json

      - name: setup correct npm dependencies package manager version
        run: yarn set version stable

      - name: setup correct node version and npm dependencies package manager cache
        uses: actions/setup-node@main
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: install npm dependencies
        run: yarn

      - name: test building subtle theme
        run: yarn run -T -B monochromatic build
        working-directory: ./packages/theme/subtle
