# Publish a package to GitHub Packages when a release is created
# See: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    paths:
      - '.github/workflfows/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm config set registry https://npm.pkg.github.com/
      - run: pnpm config set //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
      - run: pnpm -r publish --access public --no-git-checks --force --report-summary
