# Publish a package to GitHub Packages when a release is created
# See: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: pub

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    paths:
      - '.github/workflfows/**'
      - '**/package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      # Otherwise I get cannot resolve workspace protocol error.
      - run: pnpm i

      # From https://github.com/pnpm/pnpm/issues/3141#issuecomment-1305563972
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Set provenance
        run: pnpm config set provenance true

      # See https://github.com/npm/cli/issues/1637#issuecomment-1507559322
      - name: Publish workspace
        run: pnpm -r publish --access public --no-git-checks --force --report-summary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
