/**
 * Current persisted staleness manifest schema version.
 */
export const MANIFEST_VERSION = 1;

/**
 * Manifest-key prefix for single-destination writes.
 */
export const SINGLE_ENTRY_PREFIX = 'single:';

/**
 * Manifest-key prefix for glob-mirror writes.
 */
export const EACH_ENTRY_PREFIX = 'each:';

/**
 * Directory under `node_modules/.cache` used by file-enforcer.
 */
export const CACHE_DIRECTORY_NAME = 'file-enforcer';

/**
 * Persisted staleness manifest filename.
 */
export const MANIFEST_FILE_NAME = 'staleness-manifest.json';

/**
 * Sentinel returned during staleness validation when a tracked path has no
 * filesystem metadata (the file disappeared since it was recorded).
 */
export const ABSENT_FILE_STAMPS: unique symbol = Symbol('file-enforcer/io/staleness: absent filesystem metadata for a tracked path',);

/**
 * Supported manifest entry categories.
 */
export type StalenessEntryKind = 'single' | 'each';

/**
 * Optional staleness-cache controls accepted by write APIs.
 */
export type StalenessOptions = {
  /**
   * Custom manifest path, mainly for tests and throwaway benchmark fixtures.
   */
  readonly manifestPath?: string;
};

/**
 * Destination content used when recording a fresh manifest entry.
 */
export type StalenessDestination = {
  /**
   * Destination path written by file-enforcer.
   */
  readonly path: string;

  /**
   * Candidate content for the destination, used only to persist a content hash.
   */
  readonly content: string;
};

/**
 * File metadata persisted for skip validation.
 */
export type FileStamp = {
  /**
   * Absolute file path.
   */
  readonly path: string;

  /**
   * File size in bytes.
   */
  readonly size: number;

  /**
   * Modification time in milliseconds.
   */
  readonly mtimeMs: number;
};

/**
 * Destination metadata plus candidate content hash.
 */
export type DestinationStamp = FileStamp & {
  /**
   * SHA-256 hash of the destination content generated by the builder.
   */
  readonly hash: string;
};

/**
 * Glob expansion captured while a lazy builder executed.
 */
export type GlobStamp = {
  /**
   * Glob pattern passed to {@link cat}.
   */
  readonly pattern: string;

  /**
   * Absolute paths matched by the glob when the entry was recorded.
   */
  readonly paths: readonly string[];
};

/**
 * Persisted staleness entry for a single builder call.
 */
export type StalenessEntry = {
  /**
   * Entry schema discriminator.
   */
  readonly kind: StalenessEntryKind;

  /**
   * Source files whose metadata invalidates the builder.
   */
  readonly sourceFiles: readonly FileStamp[];

  /**
   * Glob expansions whose path sets invalidate the builder.
   */
  readonly sourceGlobs: readonly GlobStamp[];

  /**
   * Destination files whose metadata invalidates the builder.
   */
  readonly destinationFiles: readonly DestinationStamp[];

  /**
   * Hash of the source metadata set for human inspection and equality debugging.
   */
  readonly sourceSetHash: string;

  /**
   * ISO timestamp for diagnostics.
   */
  readonly updatedAt: string;
};

/**
 * Persisted staleness manifest shape.
 */
export type StalenessManifest = {
  /**
   * Manifest schema version.
   */
  readonly version: number;

  /**
   * Entries keyed by destination or destination glob.
   */
  entries: Record<string, StalenessEntry>;
};
