import { resolve, } from 'node:path';
import { hashContent, } from './staleness-hash.ts';
import { readFileStamps, } from './staleness-stamps.ts';
import {
  ABSENT_FILE_STAMPS,
  type DestinationStamp,
  type StalenessDestination,
} from './staleness-types.ts';

/**
 * Returns destination stamps with content hashes attached.
 *
 * @param destinations - Destinations generated by a builder.
 *
 * @returns Persistable destination metadata, or sentinel when a destination is absent.
 *
 * @example
 * ```ts
 * const stamps = await destinationStamps([{ path: './out', content: 'x' }]);
 * ```
 */
export function destinationStamps(
  destinations: readonly StalenessDestination[],
): readonly DestinationStamp[] | typeof ABSENT_FILE_STAMPS {
  /**
   * Metadata for each destination path.
   */
  const destinationPaths = destinations.map(function destinationPath(destination,): string {
    return destination.path;
  },);
  /**
   * Filesystem metadata for destination paths.
   */
  const stamps = readFileStamps(destinationPaths,);
  if (stamps === ABSENT_FILE_STAMPS)
    return ABSENT_FILE_STAMPS;

  /**
   * Content hashes keyed by absolute destination path.
   */
  const hashesByPath = new Map<string, string>(
    destinations.map(function destinationHash(destination,): readonly [
      string,
      string,
    ] {
      return [
        resolve(destination.path,),
        hashContent(destination.content,),
      ];
    },),
  );

  return stamps.map(function attachHash(stamp,): DestinationStamp {
    return {
      ...stamp,
      hash: hashesByPath.get(stamp.path,)
        ?? hashContent('',),
    };
  },);
}
